/*
 Highmaps JS v9.1.2 (2021-07-09)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(u){b(u);b.Highcharts=u;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function u(b,f,m,n){b.hasOwnProperty(f)||(b[f]=n.apply(null,m))}b=b?b._modules:{};u(b,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(b){var f=this,m=b?"show":"hide";
f.visible=f.options.visible=!!b;["graphic","dataLabel"].forEach(function(b){if(f[b])f[b][m]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var b=this,f=this.options.nullColor,m=this.colorAxis,n=this.colorKey;(this.data.length?this.data:this.points).forEach(function(l){var q=l.getNestedProperty(n);(q=l.options.color||(l.isNull||null===l.value?f:m&&"undefined"!==typeof q?m.toColor(q,l):l.color||b.color))&&l.color!==q&&(l.color=q,"point"===
b.options.legendType&&l.legendItem&&b.chart.legend.colorizeItem(l,l.visible))})}}}});u(b,"Core/Axis/ColorAxis.js",[b["Core/Axis/Axis.js"],b["Core/Chart/Chart.js"],b["Core/Color/Color.js"],b["Mixins/ColorSeries.js"],b["Core/Animation/Fx.js"],b["Core/Globals.js"],b["Core/Legend.js"],b["Mixins/LegendSymbol.js"],b["Core/Color/Palette.js"],b["Core/Series/Point.js"],b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,f,m,n,l,q,y,H,C,e,h,z){var G=this&&this.__extends||function(){var g=function(a,
c){g=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,v){c.__proto__=v}||function(c,v){for(var d in v)v.hasOwnProperty(d)&&(c[d]=v[d])};return g(a,c)};return function(a,c){function k(){this.constructor=a}g(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),p=m.parse;m=n.colorPointMixin;n=n.colorSeriesMixin;var D=q.noop,w=z.addEvent,A=z.extend,r=z.isNumber,E=z.merge,B=z.pick,x=z.splat;"";A(h.prototype,n);A(e.prototype,m);f.prototype.collectionsWithUpdate.push("colorAxis");
f.prototype.collectionsWithInit.colorAxis=[f.prototype.addColorAxis];var a=function(g){function a(a,k){var c=g.call(this,a,k)||this;c.beforePadding=!1;c.chart=void 0;c.coll="colorAxis";c.dataClasses=void 0;c.legendItem=void 0;c.legendItems=void 0;c.name="";c.options=void 0;c.stops=void 0;c.visible=!0;c.init(a,k);return c}G(a,g);a.prototype.init=function(c,k){var v=c.options.legend||{},d=k.layout?"vertical"!==k.layout:"vertical"!==v.layout;v=E(a.defaultColorAxisOptions,k,{showEmpty:!1,title:null,visible:v.enabled&&
(k?!1!==k.visible:!0)});this.coll="colorAxis";this.side=k.side||d?2:1;this.reversed=k.reversed||!d;this.opposite=!d;g.prototype.init.call(this,c,v);k.dataClasses&&this.initDataClasses(k);this.initStops();this.horiz=d;this.zoomEnabled=!1};a.prototype.initDataClasses=function(c){var a=this.chart,g,d=0,b=a.options.chart.colorCount,e=this.options,h=c.dataClasses.length;this.dataClasses=g=[];this.legendItems=[];c.dataClasses.forEach(function(c,k){c=E(c);g.push(c);if(a.styledMode||!c.color)"category"===
e.dataClassColor?(a.styledMode||(k=a.options.colors,b=k.length,c.color=k[d]),c.colorIndex=d,d++,d===b&&(d=0)):c.color=p(e.minColor).tweenTo(p(e.maxColor),2>h?.5:k/(h-1))})};a.prototype.hasData=function(){return!!(this.tickPositions||[]).length};a.prototype.setTickPositions=function(){if(!this.dataClasses)return g.prototype.setTickPositions.call(this)};a.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(c){c.color=
p(c[1])})};a.prototype.setOptions=function(c){g.prototype.setOptions.call(this,c);this.options.crosshair=this.options.marker};a.prototype.setAxisSize=function(){var c=this.legendSymbol,k=this.chart,g=k.options.legend||{},d,b;c?(this.left=g=c.attr("x"),this.top=d=c.attr("y"),this.width=b=c.attr("width"),this.height=c=c.attr("height"),this.right=k.chartWidth-g-b,this.bottom=k.chartHeight-d-c,this.len=this.horiz?b:c,this.pos=this.horiz?g:d):this.len=(this.horiz?g.symbolWidth:g.symbolHeight)||a.defaultLegendLength};
a.prototype.normalizedValue=function(c){this.logarithmic&&(c=this.logarithmic.log2lin(c));return 1-(this.max-c)/(this.max-this.min||1)};a.prototype.toColor=function(c,a){var k=this.dataClasses,d=this.stops,g;if(k)for(g=k.length;g--;){var b=k[g];var e=b.from;d=b.to;if(("undefined"===typeof e||c>=e)&&("undefined"===typeof d||c<=d)){var h=b.color;a&&(a.dataClass=g,a.colorIndex=b.colorIndex);break}}else{c=this.normalizedValue(c);for(g=d.length;g--&&!(c>d[g][0]););e=d[g]||d[g+1];d=d[g+1]||e;c=1-(d[0]-
c)/(d[0]-e[0]||1);h=e.color.tweenTo(d.color,c)}return h};a.prototype.getOffset=function(){var c=this.legendGroup,a=this.chart.axisOffset[this.side];c&&(this.axisParent=c,g.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=a)};a.prototype.setLegendColor=function(){var c=this.reversed,a=c?1:0;c=c?0:1;a=this.horiz?[a,0,c,0]:[0,c,0,a];this.legendColor={linearGradient:{x1:a[0],y1:a[1],x2:a[2],y2:a[3]},stops:this.stops}};
a.prototype.drawLegendSymbol=function(c,g){var k=c.padding,d=c.options,b=this.horiz,e=B(d.symbolWidth,b?a.defaultLegendLength:12),h=B(d.symbolHeight,b?12:a.defaultLegendLength),t=B(d.labelPadding,b?16:30);d=B(d.itemDistance,10);this.setLegendColor();g.legendSymbol=this.chart.renderer.rect(0,c.baseline-11,e,h).attr({zIndex:1}).add(g.legendGroup);this.legendItemWidth=e+k+(b?d:t);this.legendItemHeight=h+k+(b?t:0)};a.prototype.setState=function(a){this.series.forEach(function(c){c.setState(a)})};a.prototype.setVisible=
function(){};a.prototype.getSeriesExtremes=function(){var a=this.series,g=a.length,b;this.dataMin=Infinity;for(this.dataMax=-Infinity;g--;){var d=a[g];var e=d.colorKey=B(d.options.colorKey,d.colorKey,d.pointValKey,d.zoneAxis,"y");var t=d.pointArrayMap;var f=d[e+"Min"]&&d[e+"Max"];if(d[e+"Data"])var x=d[e+"Data"];else if(t){x=[];t=t.indexOf(e);var l=d.yData;if(0<=t&&l)for(b=0;b<l.length;b++)x.push(B(l[b][t],l[b]))}else x=d.yData;f?(d.minColorValue=d[e+"Min"],d.maxColorValue=d[e+"Max"]):(x=h.prototype.getExtremes.call(d,
x),d.minColorValue=x.dataMin,d.maxColorValue=x.dataMax);"undefined"!==typeof d.minColorValue&&(this.dataMin=Math.min(this.dataMin,d.minColorValue),this.dataMax=Math.max(this.dataMax,d.maxColorValue));f||h.prototype.applyExtremes.call(d)}};a.prototype.drawCrosshair=function(a,k){var c=k&&k.plotX,d=k&&k.plotY,b=this.pos,e=this.len;if(k){var h=this.toPixels(k.getNestedProperty(k.series.colorKey));h<b?h=b-2:h>b+e&&(h=b+e+2);k.plotX=h;k.plotY=this.len-h;g.prototype.drawCrosshair.call(this,a,k);k.plotX=
c;k.plotY=d;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};a.prototype.getPlotLinePath=function(a){var c=this.left,b=a.translatedValue,d=this.top;return r(b)?this.horiz?[["M",b-4,d-6],["L",b+4,d-6],["L",b,d],["Z"]]:[["M",c,b],["L",c-6,b+6],["L",c-6,b-6],["Z"]]:g.prototype.getPlotLinePath.call(this,
a)};a.prototype.update=function(a,b){var c=this.chart.legend;this.series.forEach(function(a){a.isDirtyData=!0});(a.dataClasses&&c.allItems||this.dataClasses)&&this.destroyItems();g.prototype.update.call(this,a,b);this.legendItem&&(this.setLegendColor(),c.colorizeItem(this,!0))};a.prototype.destroyItems=function(){var a=this.chart;this.legendItem?a.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(c){a.legend.destroyItem(c)});a.isDirtyLegend=!0};a.prototype.destroy=function(){this.chart.isDirtyLegend=
!0;this.destroyItems();g.prototype.destroy.apply(this,[].slice.call(arguments))};a.prototype.remove=function(a){this.destroyItems();g.prototype.remove.call(this,a)};a.prototype.getDataClassLegendSymbols=function(){var a=this,g=a.chart,b=a.legendItems,d=g.options.legend,e=d.valueDecimals,h=d.valueSuffix||"",t;b.length||a.dataClasses.forEach(function(c,d){var k=!0,v=c.from,x=c.to,f=g.numberFormatter;t="";"undefined"===typeof v?t="< ":"undefined"===typeof x&&(t="> ");"undefined"!==typeof v&&(t+=f(v,
e)+h);"undefined"!==typeof v&&"undefined"!==typeof x&&(t+=" - ");"undefined"!==typeof x&&(t+=f(x,e)+h);b.push(A({chart:g,name:t,options:{},drawLegendSymbol:H.drawRectangle,visible:!0,setState:D,isDataClass:!0,setVisible:function(){k=a.visible=!k;a.series.forEach(function(a){a.points.forEach(function(a){a.dataClass===d&&a.setVisible(k)})});g.legend.colorizeItem(this,k)}},c))});return b};a.defaultLegendLength=200;a.defaultColorAxisOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,
startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:C.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:C.highlightColor10,maxColor:C.highlightColor100,tickLength:5,showInLegend:!0};a.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return a}(b);Array.prototype.push.apply(b.keepProps,a.keepProps);q.ColorAxis=a;["fill","stroke"].forEach(function(a){l.prototype[a+"Setter"]=function(){this.elem.attr(a,p(this.start).tweenTo(p(this.end),
this.pos),null,!0)}});w(f,"afterGetAxes",function(){var g=this,b=g.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=x(b.colorAxis),b.colorAxis.forEach(function(c,b){c.index=b;new a(g,c)}))});w(h,"bindAxes",function(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]});w(y,"afterGetAllItems",function(a){var b=this,c=[],g,e,d=function(c){c=a.allItems.indexOf(c);-1!==c&&(b.destroyItem(a.allItems[c]),a.allItems.splice(c,1))};(this.chart.colorAxis||
[]).forEach(function(a){(g=a.options)&&g.showInLegend&&(g.dataClasses&&g.visible?c=c.concat(a.getDataClassLegendSymbols()):g.visible&&c.push(a),a.series.forEach(function(a){if(!a.options.showInLegend||g.dataClasses)"point"===a.options.legendType?a.points.forEach(function(a){d(a)}):d(a)}))});for(e=c.length;e--;)a.allItems.unshift(c[e])});w(y,"afterColorizeItem",function(a){a.visible&&a.item.legendColor&&a.item.legendSymbol.attr({fill:a.item.legendColor})});w(y,"afterUpdate",function(){var a=this.chart.colorAxis;
a&&a.forEach(function(a,c,b){a.update({},b)})});w(h,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});return a});u(b,"Mixins/ColorMapSeries.js",[b["Core/Globals.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,f,m){var n=m.defined;m=m.addEvent;var l=b.noop;b=b.seriesTypes;m(f,"afterSetState",function(b){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:b&&"hover"===b.state?1:0})});return{colorMapPointMixin:{dataLabelOnNull:!0,
moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:l,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:b.column.prototype.pointAttribs,colorAttribs:function(b){var f={};!n(b.color)||b.state&&"normal"!==b.state||(f[this.colorProp||"fill"]=b.color);return f}}}});u(b,"Series/Heatmap/HeatmapPoint.js",
[b["Mixins/ColorMapSeries.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,m){var n=this&&this.__extends||function(){var b=function(f,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var h in e)e.hasOwnProperty(h)&&(b[h]=e[h])};return b(f,e)};return function(f,e){function h(){this.constructor=f}b(f,e);f.prototype=null===e?Object.create(e):(h.prototype=e.prototype,new h)}}();b=b.colorMapPointMixin;var l=m.clamp,
q=m.extend,y=m.pick;f=function(b){function f(){var e=null!==b&&b.apply(this,arguments)||this;e.options=void 0;e.series=void 0;e.value=void 0;e.x=void 0;e.y=void 0;return e}n(f,b);f.prototype.applyOptions=function(e,h){e=b.prototype.applyOptions.call(this,e,h);e.formatPrefix=e.isNull||null===e.value?"null":"point";return e};f.prototype.getCellAttributes=function(){var b=this.series,h=b.options,f=(h.colsize||1)/2,m=(h.rowsize||1)/2,p=b.xAxis,n=b.yAxis,w=this.options.marker||b.options.marker;b=b.pointPlacementToXValue();
var q=y(this.pointPadding,h.pointPadding,0),r={x1:l(Math.round(p.len-(p.translate(this.x-f,!1,!0,!1,!0,-b)||0)),-p.len,2*p.len),x2:l(Math.round(p.len-(p.translate(this.x+f,!1,!0,!1,!0,-b)||0)),-p.len,2*p.len),y1:l(Math.round(n.translate(this.y-m,!1,!0,!1,!0)||0),-n.len,2*n.len),y2:l(Math.round(n.translate(this.y+m,!1,!0,!1,!0)||0),-n.len,2*n.len)};[["width","x"],["height","y"]].forEach(function(b){var e=b[0];b=b[1];var f=b+"1",a=b+"2",g=Math.abs(r[f]-r[a]),h=w&&w.lineWidth||0,c=Math.abs(r[f]+r[a])/
2;w[e]&&w[e]<g&&(r[f]=c-w[e]/2-h/2,r[a]=c+w[e]/2+h/2);q&&("y"===b&&(f=a,a=b+"1"),r[f]+=q,r[a]-=q)});return r};f.prototype.haloPath=function(b){if(!b)return[];var e=this.shapeArgs;return["M",e.x-b,e.y-b,"L",e.x-b,e.y+e.height+b,e.x+e.width+b,e.y+e.height+b,e.x+e.width+b,e.y-b,"Z"]};f.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return f}(f.seriesTypes.scatter.prototype.pointClass);q(f.prototype,{dataLabelOnNull:b.dataLabelOnNull,moveToTopOnHover:b.moveToTopOnHover});
return f});u(b,"Series/Heatmap/HeatmapSeries.js",[b["Core/Color/Color.js"],b["Mixins/ColorMapSeries.js"],b["Series/Heatmap/HeatmapPoint.js"],b["Mixins/LegendSymbol.js"],b["Core/Color/Palette.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,f,m,n,l,q,y,u){var C=this&&this.__extends||function(){var b=function(e,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c])};return b(e,a)};return function(e,a){function g(){this.constructor=e}b(e,a);e.prototype=null===a?Object.create(a):(g.prototype=a.prototype,new g)}}();f=f.colorMapSeriesMixin;var e=q.series,h=q.seriesTypes,z=h.column,F=h.scatter,p=y.prototype.symbols,D=u.extend,w=u.fireEvent,A=u.isNumber,r=u.merge,E=u.pick;y=function(f){function h(){var a=null!==f&&f.apply(this,arguments)||this;a.colorAxis=void 0;a.data=void 0;a.options=void 0;a.points=void 0;a.valueMax=NaN;a.valueMin=NaN;return a}C(h,
f);h.prototype.drawPoints=function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)e.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&(b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b)),a.options.borderRadius&&b.graphic.attr({r:a.options.borderRadius}),null===b.value&&b.graphic.addClass("highcharts-null-point"))})};h.prototype.getExtremes=function(){var a=e.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;A(b)&&
(this.valueMin=b);A(a)&&(this.valueMax=a);return e.prototype.getExtremes.call(this)};h.prototype.getValidPoints=function(a,b){return e.prototype.getValidPoints.call(this,a,b,!0)};h.prototype.hasData=function(){return!!this.processedXData.length};h.prototype.init=function(){e.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=E(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;p.ellipse=p.circle};h.prototype.markerAttribs=function(a,b){var e=a.marker||{},c=this.options.marker||
{},g=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var d=c.states[b]||{};var h=e.states&&e.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(h[a[0]]||d[a[0]]||g[a[0]])+(h[a[0]+"Plus"]||d[a[0]+"Plus"]||0);f[a[1]]=g[a[1]]+(g[a[0]]-f[a[0]])/2})}return b?f:g};h.prototype.pointAttribs=function(a,g){var f=e.prototype.pointAttribs.call(this,a,g),c=this.options||{},k=this.chart.options.plotOptions||{},h=k.series||{},d=k.heatmap||{};k=a&&a.options.borderColor||
c.borderColor||d.borderColor||h.borderColor;h=a&&a.options.borderWidth||c.borderWidth||d.borderWidth||h.borderWidth||f["stroke-width"];f.stroke=a&&a.marker&&a.marker.lineColor||c.marker&&c.marker.lineColor||k||this.color;f["stroke-width"]=h;g&&(a=r(c.states[g],c.marker&&c.marker.states[g],a&&a.options.states&&a.options.states[g]||{}),g=a.brightness,f.fill=a.color||b.parse(f.fill).brighten(g||0).get(),f.stroke=a.lineColor);return f};h.prototype.setClip=function(a){var b=this.chart;e.prototype.setClip.apply(this,
arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?b.sharedClips[this.sharedClipKey]:b.clipRect)};h.prototype.translate=function(){var a=this.options,b=a.marker&&a.marker.symbol||"rect",e=p[b]?b:"rect",c=-1!==["circle","square"].indexOf(e);this.generatePoints();this.points.forEach(function(a){var f=a.getCellAttributes(),d={};d.x=Math.min(f.x1,f.x2);d.y=Math.min(f.y1,f.y2);d.width=Math.max(Math.abs(f.x2-f.x1),0);d.height=Math.max(Math.abs(f.y2-f.y1),
0);var g=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(c){var h=Math.abs(d.width-d.height);d.x=Math.min(f.x1,f.x2)+(d.width<d.height?0:h/2);d.y=Math.min(f.y1,f.y2)+(d.width<d.height?h/2:0);d.width=d.height=Math.min(d.width,d.height)}h={plotX:(f.x1+f.x2)/2,plotY:(f.y1+f.y2)/2,clientX:(f.x1+f.x2)/2,shapeType:"path",shapeArgs:r(!0,d,{d:p[e](d.x,d.y,d.width,d.height)})};g&&(a.marker={width:d.width,height:d.height});D(a,h)});w(this,"afterTranslate")};h.defaultOptions=r(F.defaultOptions,
{animation:!1,borderRadius:0,borderWidth:0,nullColor:l.neutralColor3,dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return A(b)?a(b,-1):""},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}});return h}(F);D(y.prototype,{alignDataLabel:z.prototype.alignDataLabel,
axisTypes:f.axisTypes,colorAttribs:f.colorAttribs,colorKey:f.colorKey,directTouch:!0,drawLegendSymbol:n.drawRectangle,getExtremesFromAll:!0,getSymbol:e.prototype.getSymbol,parallelArrays:f.parallelArrays,pointArrayMap:["y","value"],pointClass:m,trackerGroups:f.trackerGroups});q.registerSeriesType("heatmap",y);"";"";return y});u(b,"masters/modules/heatmap.src.js",[],function(){})});
//# sourceMappingURL=heatmap.js.map