/*
 Highmaps JS v9.1.2 (2021-07-09)

 Highmaps as a plugin for Highcharts or Highcharts Stock.

 (c) 2011-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(w){a(w);a.Highcharts=w;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function w(a,k,l,g){a.hasOwnProperty(k)||(a[k]=g.apply(null,l))}a=a?a._modules:{};w(a,"Core/Axis/MapAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,k){var l=k.addEvent,g=k.pick,q=function(){return function(a){this.axis=
a}}();k=function(){function a(){}a.compose=function(h){h.keepProps.push("mapAxis");l(h,"init",function(){this.mapAxis||(this.mapAxis=new q(this))});l(h,"getSeriesExtremes",function(){if(this.mapAxis){var c=[];this.isXAxis&&(this.series.forEach(function(f,b){f.useMapGeometry&&(c[b]=f.xData,f.xData=[])}),this.mapAxis.seriesXData=c)}});l(h,"afterGetSeriesExtremes",function(){if(this.mapAxis){var c=this.mapAxis.seriesXData||[],f;if(this.isXAxis){var b=g(this.dataMin,Number.MAX_VALUE);var e=g(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(d,h){d.useMapGeometry&&(b=Math.min(b,g(d.minX,b)),e=Math.max(e,g(d.maxX,e)),d.xData=c[h],f=!0)});f&&(this.dataMin=b,this.dataMax=e);this.mapAxis.seriesXData=void 0}}});l(h,"afterSetAxisTranslation",function(){if(this.mapAxis){var c=this.chart,f=c.plotWidth/c.plotHeight;c=c.xAxis[0];var b;"yAxis"===this.coll&&"undefined"!==typeof c.transA&&this.series.forEach(function(c){c.preserveAspectRatio&&(b=!0)});if(b&&(this.transA=c.transA=Math.min(this.transA,
c.transA),f/=(c.max-c.min)/(this.max-this.min),f=1>f?this:c,c=(f.max-f.min)*f.transA,f.mapAxis.pixelPadding=f.len-c,f.minPixelPadding=f.mapAxis.pixelPadding/2,c=f.mapAxis.fixTo)){c=c[1]-f.toValue(c[0],!0);c*=f.transA;if(Math.abs(c)>f.minPixelPadding||f.min===f.dataMin&&f.max===f.dataMax)c=0;f.minPixelPadding-=c}}});l(h,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();k.compose(a);return k});w(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var k=
this,l=a?"show":"hide";k.visible=k.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(k[a])k[a][l]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,k=this.options.nullColor,l=this.colorAxis,g=this.colorKey;(this.data.length?this.data:this.points).forEach(function(q){var r=q.getNestedProperty(g);(r=q.options.color||(q.isNull||null===q.value?k:l&&"undefined"!==typeof r?l.toColor(r,q):q.color||a.color))&&q.color!==
r&&(q.color=r,"point"===a.options.legendType&&q.legendItem&&a.chart.legend.colorizeItem(q,q.visible))})}}}});w(a,"Core/Axis/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Animation/Fx.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Mixins/LegendSymbol.js"],a["Core/Color/Palette.js"],a["Core/Series/Point.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,k,l,g,q,r,h,c,f,b,e,d){var A=this&&this.__extends||function(){var d=
function(b,c){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,m){d.__proto__=m}||function(d,m){for(var b in m)m.hasOwnProperty(b)&&(d[b]=m[b])};return d(b,c)};return function(b,c){function p(){this.constructor=b}d(b,c);b.prototype=null===c?Object.create(c):(p.prototype=c.prototype,new p)}}(),n=l.parse;l=g.colorPointMixin;g=g.colorSeriesMixin;var x=r.noop,z=d.addEvent,y=d.extend,v=d.isNumber,C=d.merge,u=d.pick,D=d.splat;"";y(e.prototype,g);y(b.prototype,l);k.prototype.collectionsWithUpdate.push("colorAxis");
k.prototype.collectionsWithInit.colorAxis=[k.prototype.addColorAxis];var t=function(d){function b(b,c){var m=d.call(this,b,c)||this;m.beforePadding=!1;m.chart=void 0;m.coll="colorAxis";m.dataClasses=void 0;m.legendItem=void 0;m.legendItems=void 0;m.name="";m.options=void 0;m.stops=void 0;m.visible=!0;m.init(b,c);return m}A(b,d);b.prototype.init=function(c,e){var m=c.options.legend||{},B=e.layout?"vertical"!==e.layout:"vertical"!==m.layout;m=C(b.defaultColorAxisOptions,e,{showEmpty:!1,title:null,visible:m.enabled&&
(e?!1!==e.visible:!0)});this.coll="colorAxis";this.side=e.side||B?2:1;this.reversed=e.reversed||!B;this.opposite=!B;d.prototype.init.call(this,c,m);e.dataClasses&&this.initDataClasses(e);this.initStops();this.horiz=B;this.zoomEnabled=!1};b.prototype.initDataClasses=function(b){var d=this.chart,m,c=0,e=d.options.chart.colorCount,f=this.options,p=b.dataClasses.length;this.dataClasses=m=[];this.legendItems=[];b.dataClasses.forEach(function(b,B){b=C(b);m.push(b);if(d.styledMode||!b.color)"category"===
f.dataClassColor?(d.styledMode||(B=d.options.colors,e=B.length,b.color=B[c]),b.colorIndex=c,c++,c===e&&(c=0)):b.color=n(f.minColor).tweenTo(n(f.maxColor),2>p?.5:B/(p-1))})};b.prototype.hasData=function(){return!!(this.tickPositions||[]).length};b.prototype.setTickPositions=function(){if(!this.dataClasses)return d.prototype.setTickPositions.call(this)};b.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=
n(b[1])})};b.prototype.setOptions=function(b){d.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker};b.prototype.setAxisSize=function(){var d=this.legendSymbol,c=this.chart,m=c.options.legend||{},B,e;d?(this.left=m=d.attr("x"),this.top=B=d.attr("y"),this.width=e=d.attr("width"),this.height=d=d.attr("height"),this.right=c.chartWidth-m-e,this.bottom=c.chartHeight-B-d,this.len=this.horiz?e:d,this.pos=this.horiz?m:B):this.len=(this.horiz?m.symbolWidth:m.symbolHeight)||b.defaultLegendLength};
b.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)};b.prototype.toColor=function(b,d){var m=this.dataClasses,c=this.stops,e;if(m)for(e=m.length;e--;){var f=m[e];var p=f.from;c=f.to;if(("undefined"===typeof p||b>=p)&&("undefined"===typeof c||b<=c)){var h=f.color;d&&(d.dataClass=e,d.colorIndex=f.colorIndex);break}}else{b=this.normalizedValue(b);for(e=c.length;e--&&!(b>c[e][0]););p=c[e]||c[e+1];c=c[e+1]||p;b=1-(c[0]-
b)/(c[0]-p[0]||1);h=p.color.tweenTo(c.color,b)}return h};b.prototype.getOffset=function(){var b=this.legendGroup,c=this.chart.axisOffset[this.side];b&&(this.axisParent=b,d.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=c)};b.prototype.setLegendColor=function(){var b=this.reversed,d=b?1:0;b=b?0:1;d=this.horiz?[d,0,b,0]:[0,b,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}};
b.prototype.drawLegendSymbol=function(d,c){var m=d.padding,e=d.options,f=this.horiz,p=u(e.symbolWidth,f?b.defaultLegendLength:12),h=u(e.symbolHeight,f?12:b.defaultLegendLength),a=u(e.labelPadding,f?16:30);e=u(e.itemDistance,10);this.setLegendColor();c.legendSymbol=this.chart.renderer.rect(0,d.baseline-11,p,h).attr({zIndex:1}).add(c.legendGroup);this.legendItemWidth=p+m+(f?e:a);this.legendItemHeight=h+m+(f?a:0)};b.prototype.setState=function(b){this.series.forEach(function(d){d.setState(b)})};b.prototype.setVisible=
function(){};b.prototype.getSeriesExtremes=function(){var b=this.series,d=b.length,m;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var c=b[d];var f=c.colorKey=u(c.options.colorKey,c.colorKey,c.pointValKey,c.zoneAxis,"y");var p=c.pointArrayMap;var h=c[f+"Min"]&&c[f+"Max"];if(c[f+"Data"])var a=c[f+"Data"];else if(p){a=[];p=p.indexOf(f);var n=c.yData;if(0<=p&&n)for(m=0;m<n.length;m++)a.push(u(n[m][p],n[m]))}else a=c.yData;h?(c.minColorValue=c[f+"Min"],c.maxColorValue=c[f+"Max"]):(a=e.prototype.getExtremes.call(c,
a),c.minColorValue=a.dataMin,c.maxColorValue=a.dataMax);"undefined"!==typeof c.minColorValue&&(this.dataMin=Math.min(this.dataMin,c.minColorValue),this.dataMax=Math.max(this.dataMax,c.maxColorValue));h||e.prototype.applyExtremes.call(c)}};b.prototype.drawCrosshair=function(b,c){var m=c&&c.plotX,e=c&&c.plotY,f=this.pos,p=this.len;if(c){var a=this.toPixels(c.getNestedProperty(c.series.colorKey));a<f?a=f-2:a>f+p&&(a=f+p+2);c.plotX=a;c.plotY=this.len-a;d.prototype.drawCrosshair.call(this,b,c);c.plotX=
m;c.plotY=e;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};b.prototype.getPlotLinePath=function(b){var c=this.left,m=b.translatedValue,e=this.top;return v(m)?this.horiz?[["M",m-4,e-6],["L",m+4,e-6],["L",m,e],["Z"]]:[["M",c,m],["L",c-6,m+6],["L",c-6,m-6],["Z"]]:d.prototype.getPlotLinePath.call(this,
b)};b.prototype.update=function(b,c){var m=this.chart.legend;this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&m.allItems||this.dataClasses)&&this.destroyItems();d.prototype.update.call(this,b,c);this.legendItem&&(this.setLegendColor(),m.colorizeItem(this,!0))};b.prototype.destroyItems=function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(c){b.legend.destroyItem(c)});b.isDirtyLegend=!0};b.prototype.destroy=function(){this.chart.isDirtyLegend=
!0;this.destroyItems();d.prototype.destroy.apply(this,[].slice.call(arguments))};b.prototype.remove=function(b){this.destroyItems();d.prototype.remove.call(this,b)};b.prototype.getDataClassLegendSymbols=function(){var b=this,d=b.chart,m=b.legendItems,e=d.options.legend,f=e.valueDecimals,p=e.valueSuffix||"",a;m.length||b.dataClasses.forEach(function(e,h){var n=!0,t=e.from,A=e.to,B=d.numberFormatter;a="";"undefined"===typeof t?a="< ":"undefined"===typeof A&&(a="> ");"undefined"!==typeof t&&(a+=B(t,
f)+p);"undefined"!==typeof t&&"undefined"!==typeof A&&(a+=" - ");"undefined"!==typeof A&&(a+=B(A,f)+p);m.push(y({chart:d,name:a,options:{},drawLegendSymbol:c.drawRectangle,visible:!0,setState:x,isDataClass:!0,setVisible:function(){n=b.visible=!n;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===h&&b.setVisible(n)})});d.legend.colorizeItem(this,n)}},e))});return m};b.defaultLegendLength=200;b.defaultColorAxisOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,
startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:f.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:f.highlightColor10,maxColor:f.highlightColor100,tickLength:5,showInLegend:!0};b.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return b}(a);Array.prototype.push.apply(a.keepProps,t.keepProps);r.ColorAxis=t;["fill","stroke"].forEach(function(b){q.prototype[b+"Setter"]=function(){this.elem.attr(b,n(this.start).tweenTo(n(this.end),
this.pos),null,!0)}});z(k,"afterGetAxes",function(){var b=this,c=b.options;this.colorAxis=[];c.colorAxis&&(c.colorAxis=D(c.colorAxis),c.colorAxis.forEach(function(c,d){c.index=d;new t(b,c)}))});z(e,"bindAxes",function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});z(h,"afterGetAllItems",function(b){var c=this,d=[],e,m,f=function(d){d=b.allItems.indexOf(d);-1!==d&&(c.destroyItem(b.allItems[d]),b.allItems.splice(d,1))};(this.chart.colorAxis||
[]).forEach(function(b){(e=b.options)&&e.showInLegend&&(e.dataClasses&&e.visible?d=d.concat(b.getDataClassLegendSymbols()):e.visible&&d.push(b),b.series.forEach(function(b){if(!b.options.showInLegend||e.dataClasses)"point"===b.options.legendType?b.points.forEach(function(b){f(b)}):f(b)}))});for(m=d.length;m--;)b.allItems.unshift(d[m])});z(h,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});z(h,"afterUpdate",function(){var b=this.chart.colorAxis;
b&&b.forEach(function(b,c,d){b.update({},d)})});z(e,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});return t});w(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,k,l){var g=l.defined;l=l.addEvent;var q=a.noop;a=a.seriesTypes;l(k,"afterSetState",function(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})});return{colorMapPointMixin:{dataLabelOnNull:!0,
moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:q,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.column.prototype.pointAttribs,colorAttribs:function(a){var h={};!g(a.color)||a.state&&"normal"!==a.state||(h[this.colorProp||"fill"]=a.color);return h}}}});w(a,"Maps/MapNavigationOptionsDefault.js",
[a["Core/DefaultOptions.js"],a["Core/Utilities.js"]],function(a,k){k=k.extend;var l={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};k(a.defaultOptions.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});return a.defaultOptions.mapNavigation=
l});w(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,k,l){function g(b){b&&(b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),b.cancelBubble=!0)}function q(b){this.init(b)}var r=k.doc,h=l.addEvent,c=l.extend,f=l.merge,b=l.objectEach,e=l.pick;q.prototype.init=function(b){this.chart=b;b.mapNavButtons=[]};q.prototype.update=function(d){var a=this.chart,n=a.options.mapNavigation,x,l,y,v,k=function(b){this.handler.call(a,
b);g(b)},u=a.mapNavButtons;d&&(n=a.options.mapNavigation=f(a.options.mapNavigation,d));for(;u.length;)u.pop().destroy();e(n.enableButtons,n.enabled)&&!a.renderer.forExport&&b(n.buttons,function(b,d){b=f(n.buttonOptions,b);!a.styledMode&&b.theme&&(x=b.theme,x.style=f(b.theme.style,b.style),y=(l=x.states)&&l.hover,v=l&&l.select,delete x.states);var e=a.renderer.button(b.text||"",0,0,k,x,y,v,void 0,"zoomIn"===d?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",
zoomOut:"zoom-out"}[d]).attr({width:b.width,height:b.height,title:a.options.lang[d],padding:b.padding,zIndex:5}).add();e.handler=b.onclick;h(e.element,"dblclick",g);u.push(e);c(b,{width:e.width,height:2*e.height});if(a.hasLoaded)e.align(b,!1,b.alignTo);else var t=h(a,"load",function(){e.element&&e.align(b,!1,b.alignTo);t()})});this.updateEvents(n)};q.prototype.updateEvents=function(b){var c=this.chart;e(b.enableDoubleClickZoom,b.enabled)||b.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||
h(c.container,"dblclick",function(b){c.pointer.onContainerDblClick(b)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());e(b.enableMouseWheelZoom,b.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||h(c.container,void 0!==r.onwheel?"wheel":void 0!==r.onmousewheel?"mousewheel":"DOMMouseScroll",function(b){c.pointer.inClass(b.target,"highcharts-no-mousewheel")||(c.pointer.onContainerMouseWheel(b),g(b));return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};
c(a.prototype,{fitToBox:function(b,c){[["x","width"],["y","height"]].forEach(function(d){var e=d[0];d=d[1];b[e]+b[d]>c[e]+c[d]&&(b[d]>c[d]?(b[d]=c[d],b[e]=c[e]):b[e]=c[e]+c[d]-b[d]);b[d]>c[d]&&(b[d]=c[d]);b[e]<c[e]&&(b[e]=c[e])});return b},mapZoom:function(b,c,a,f,h,l){var d=this.xAxis[0],n=d.max-d.min,u=e(c,d.min+n/2),x=n*b;n=this.yAxis[0];var t=n.max-n.min,p=e(a,n.min+t/2);t*=b;u=this.fitToBox({x:u-x*(f?(f-d.pos)/d.len:.5),y:p-t*(h?(h-n.pos)/n.len:.5),width:x,height:t},{x:d.dataMin,y:n.dataMin,
width:d.dataMax-d.dataMin,height:n.dataMax-n.dataMin});x=u.x<=d.dataMin&&u.width>=d.dataMax-d.dataMin&&u.y<=n.dataMin&&u.height>=n.dataMax-n.dataMin;f&&d.mapAxis&&(d.mapAxis.fixTo=[f-d.pos,c]);h&&n.mapAxis&&(n.mapAxis.fixTo=[h-n.pos,a]);"undefined"===typeof b||x?(d.setExtremes(void 0,void 0,!1),n.setExtremes(void 0,void 0,!1)):(d.setExtremes(u.x,u.x+u.width,!1),n.setExtremes(u.y,u.y+u.height,!1));this.redraw(l)}});h(a,"beforeRender",function(){this.mapNavigation=new q(this);this.mapNavigation.update()});
k.MapNavigation=q});w(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],function(a,k){var l=k.extend,g=k.pick;k=k.wrap;var q=0,r;l(a.prototype,{onContainerDblClick:function(a){var c=this.chart;a=this.normalize(a);c.options.mapNavigation.enableDoubleClickZoomTo?c.pointer.inClass(a.target,"highcharts-tracker")&&c.hoverPoint&&c.hoverPoint.zoomTo():c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(.5,c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,
a.chartY)},onContainerMouseWheel:function(a){var c=this.chart;a=this.normalize(a);var f=a.deltaY||a.detail||-(a.wheelDelta/120);1<=Math.abs(f)&&(q+=Math.abs(f),r&&clearTimeout(r),r=setTimeout(function(){q=0},50));10>q&&c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(Math.pow(c.options.mapNavigation.mouseWheelSensitivity,f),c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,a.chartY,1>Math.abs(f)?!1:void 0)}});k(a.prototype,"zoomOption",function(a){var c=this.chart.options.mapNavigation;
g(c.enableTouchZoom,c.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});k(a.prototype,"pinchTranslate",function(a,c,f,b,e,d,l){a.call(this,c,f,b,e,d,l);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=b.scaleX>b.scaleY,this.pinchTranslateDirection(!a,c,f,b,e,d,l,a?b.scaleX:b.scaleY))})});w(a,"Maps/MapSymbols.js",[a["Core/Renderer/SVG/SVGRenderer.js"]],function(a){function k(a,g,k,r,h,c,f,b){return[["M",a+h,g],["L",a+k-c,g],["C",a+k-c/2,g,a+k,g+c/
2,a+k,g+c],["L",a+k,g+r-f],["C",a+k,g+r-f/2,a+k-f/2,g+r,a+k-f,g+r],["L",a+b,g+r],["C",a+b/2,g+r,a,g+r-b/2,a,g+r-b],["L",a,g+h],["C",a,g+h/2,a+h/2,g,a+h,g],["Z"]]}a=a.prototype.symbols;a.bottombutton=function(a,g,q,r,h){h=h&&h.r||0;return k(a-1,g-1,q,r,0,0,h,h)};a.topbutton=function(a,g,q,r,h){h=h&&h.r||0;return k(a-1,g-1,q,r,h,h,0,0)};return a});w(a,"Core/Chart/MapChart.js",[a["Core/Chart/Chart.js"],a["Core/DefaultOptions.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,
k,l,g){var q=this&&this.__extends||function(){var c=function(b,a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,c){b.__proto__=c}||function(b,c){for(var a in c)c.hasOwnProperty(a)&&(b[a]=c[a])};return c(b,a)};return function(b,a){function d(){this.constructor=b}c(b,a);b.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)}}(),r=k.getOptions,h=g.merge,c=g.pick;a=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}q(b,a);b.prototype.init=function(b,
d){var e={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},f=r().credits;b=h({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:c(f.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:c(f.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:e,yAxis:h(e,{reversed:!0})},b,{chart:{inverted:!1,alignTicks:!1}});a.prototype.init.call(this,b,d)};return b}(a);(function(c){c.maps={};c.mapChart=function(b,a,d){return new c(b,
a,d)};c.splitPath=function(b){"string"===typeof b&&(b=b.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),b=b.split(/[ ,;]+/).map(function(b){return/[A-za-z]/.test(b)?b:parseFloat(b)}));return l.prototype.pathToSegments(b)}})(a||(a={}));return a});w(a,"Series/Map/MapPoint.js",[a["Mixins/ColorMapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k,l){var g=this&&this.__extends||function(){var a=function(h,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(h,c)};return function(h,c){function f(){this.constructor=h}a(h,c);h.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}();a=a.colorMapPointMixin;var q=l.extend;k=function(a){function h(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.path=void 0;c.series=void 0;return c}g(h,a);h.prototype.applyOptions=function(c,f){var b=this.series;c=a.prototype.applyOptions.call(this,
c,f);f=b.joinBy;b.mapData&&b.mapMap&&(f=a.prototype.getNestedProperty.call(c,f[1]),(f="undefined"!==typeof f&&b.mapMap[f])?(b.xyFromShape&&(c.x=f._midX,c.y=f._midY),q(c,f)):c.value=c.value||null);return c};h.prototype.onMouseOver=function(c){l.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)a.prototype.onMouseOver.call(this,c);else this.series.onMouseOut(c)};h.prototype.zoomTo=function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,
this._maxY,!1);a.chart.redraw()};return h}(k.seriesTypes.scatter.prototype.pointClass);q(k.prototype,{dataLabelOnNull:a.dataLabelOnNull,isValid:a.isValid,moveToTopOnHover:a.moveToTopOnHover});return k});w(a,"Series/Map/MapSeries.js",[a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],a["Core/Chart/MapChart.js"],a["Series/Map/MapPoint.js"],a["Core/Color/Palette.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],
function(a,k,l,g,q,r,h,c,f,b){var e=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function d(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}();a=a.colorMapSeriesMixin;var d=k.noop,A=g.maps,n=g.splitPath;g=c.seriesTypes;var x=g.column,F=g.scatter;g=b.extend;
var y=b.fireEvent,v=b.getNestedProperty,C=b.isArray,u=b.isNumber,D=b.merge,t=b.objectEach,p=b.pick,E=b.splat;b=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.baseTrans=void 0;a.chart=void 0;a.data=void 0;a.group=void 0;a.joinBy=void 0;a.options=void 0;a.points=void 0;a.transformGroup=void 0;return a}e(a,b);a.prototype.animate=function(b){var a=this.options.animation,c=this.group,d=this.xAxis,e=this.yAxis,m=d.pos,f=e.pos;this.chart.renderer.isSVG&&(!0===a&&(a={duration:1E3}),
b?c.attr({translateX:m+d.len/2,translateY:f+e.len/2,scaleX:.001,scaleY:.001}):c.animate({translateX:m,translateY:f,scaleX:1,scaleY:1},a))};a.prototype.animateDrilldown=function(b){var a=this.chart.plotBox,c=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],d=c.bBox,e=this.chart.options.drilldown.animation;b||(b=Math.min(d.width/a.width,d.height/a.height),c.shapeArgs={scaleX:b,scaleY:b,translateX:d.x,translateY:d.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(c.shapeArgs).animate({scaleX:1,
scaleY:1,translateX:0,translateY:0},e)}))};a.prototype.animateDrillupFrom=function(b){x.prototype.animateDrillupFrom.call(this,b)};a.prototype.animateDrillupTo=function(b){x.prototype.animateDrillupTo.call(this,b)};a.prototype.doFullTranslate=function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans};a.prototype.drawMapDataLabels=function(){h.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};a.prototype.drawPoints=
function(){var b=this,a=b.xAxis,c=b.yAxis,d=b.group,e=b.chart,f=e.renderer,n=this.baseTrans;b.transformGroup||(b.transformGroup=f.g().attr({scaleX:1,scaleY:1}).add(d),b.transformGroup.survive=!0);if(b.doFullTranslate())e.hasRendered&&!e.styledMode&&b.points.forEach(function(a){a.shapeArgs&&(a.shapeArgs.fill=b.pointAttribs(a,a.state).fill)}),b.group=b.transformGroup,x.prototype.drawPoints.apply(b),b.group=d,b.points.forEach(function(a){if(a.graphic){var c="";a.name&&(c+="highcharts-name-"+a.name.replace(/ /g,
"-").toLowerCase());a.properties&&a.properties["hc-key"]&&(c+=" highcharts-key-"+a.properties["hc-key"].toLowerCase());c&&a.graphic.addClass(c);e.styledMode&&a.graphic.css(b.pointAttribs(a,a.selected&&"select"||void 0))}}),this.baseTrans={originX:a.min-a.minPixelPadding/a.transA,originY:c.min-c.minPixelPadding/c.transA+(c.reversed?0:c.len/c.transA),transAX:a.transA,transAY:c.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1});else{var h=a.transA/n.transAX;var t=c.transA/
n.transAY;var u=a.toPixels(n.originX,!0);var k=c.toPixels(n.originY,!0);.99<h&&1.01>h&&.99<t&&1.01>t&&(t=h=1,u=Math.round(u),k=Math.round(k));var g=this.transformGroup;if(e.renderer.globalAnimation){var v=g.attr("translateX");var y=g.attr("translateY");var D=g.attr("scaleX");var A=g.attr("scaleY");g.attr({animator:0}).animate({animator:1},{step:function(b,a){g.attr({translateX:v+(u-v)*a.pos,translateY:y+(k-y)*a.pos,scaleX:D+(h-D)*a.pos,scaleY:A+(t-A)*a.pos})}})}else g.attr({translateX:u,translateY:k,
scaleX:h,scaleY:t})}e.styledMode||d.element.setAttribute("stroke-width",p(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(h||1));this.drawMapDataLabels()};a.prototype.getBox=function(b){var a=Number.MAX_VALUE,c=-a,d=a,e=-a,m=a,h=a,t=this.xAxis,u=this.yAxis,x;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path?b.path=n(b.path):"M"===b.path[0]&&(b.path=f.prototype.pathToSegments(b.path));var t=b.path||[],u=-a,k=a,g=-a,v=a,y=b.properties;b._foundBox||
(t.forEach(function(b){var a=b[b.length-2];b=b[b.length-1];"number"===typeof a&&"number"===typeof b&&(k=Math.min(k,a),u=Math.max(u,a),v=Math.min(v,b),g=Math.max(g,b))}),b._midX=k+(u-k)*p(b.middleX,y&&y["hc-middle-x"],.5),b._midY=v+(g-v)*p(b.middleY,y&&y["hc-middle-y"],.5),b._maxX=u,b._minX=k,b._maxY=g,b._minY=v,b.labelrank=p(b.labelrank,(u-k)*(g-v)),b._foundBox=!0);c=Math.max(c,b._maxX);d=Math.min(d,b._minX);e=Math.max(e,b._maxY);m=Math.min(m,b._minY);h=Math.min(b._maxX-b._minX,b._maxY-b._minY,h);
x=!0}});x&&(this.minY=Math.min(m,p(this.minY,a)),this.maxY=Math.max(e,p(this.maxY,-a)),this.minX=Math.min(d,p(this.minX,a)),this.maxX=Math.max(c,p(this.maxX,-a)),t&&"undefined"===typeof t.options.minRange&&(t.minRange=Math.min(5*h,(this.maxX-this.minX)/5,t.minRange||a)),u&&"undefined"===typeof u.options.minRange&&(u.minRange=Math.min(5*h,(this.maxY-this.minY)/5,u.minRange||a)))};a.prototype.getExtremes=function(){var b=h.prototype.getExtremes.call(this,this.valueData),a=b.dataMin;b=b.dataMax;this.chart.hasRendered&&
this.isDirtyData&&this.getBox(this.options.data);u(a)&&(this.valueMin=a);u(b)&&(this.valueMax=b);return{dataMin:this.minY,dataMax:this.maxY}};a.prototype.hasData=function(){return!!this.processedXData.length};a.prototype.pointAttribs=function(b,a){a=b.series.chart.styledMode?this.colorAttribs(b):x.prototype.pointAttribs.call(this,b,a);a["stroke-width"]=p(b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return a};a.prototype.render=function(){var b=
this,a=h.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?setTimeout(function(){a.call(b)}):a.call(b)};a.prototype.setData=function(b,a,c,d){var e=this.options,f=this.chart.options.chart,n=f&&f.map,p=e.mapData,m=this.joinBy,x=e.keys||this.pointArrayMap,g=[],y={},l=this.chart.mapTransforms;!p&&n&&(p="string"===typeof n?A[n]:n);b&&b.forEach(function(a,c){var d=0;if(u(a))b[c]={value:a};else if(C(a)){b[c]={};!e.keys&&a.length>x.length&&"string"===typeof a[0]&&(b[c]["hc-key"]=a[0],++d);for(var f=
0;f<x.length;++f,++d)x[f]&&"undefined"!==typeof a[d]&&(0<x[f].indexOf(".")?q.prototype.setNestedProperty(b[c],a[d],x[f]):b[c][x[f]]=a[d])}m&&"_i"===m[0]&&(b[c]._i=c)});this.getBox(b);(this.chart.mapTransforms=l=f.mapTransforms||p&&p["hc-transform"]||l)&&t(l,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),b.sinAngle=Math.sin(b.rotation))});if(p){"FeatureCollection"===p.type&&(this.mapTitle=p.title,p=k.geojson(p,this.type,this));this.mapData=p;this.mapMap={};for(l=0;l<p.length;l++)f=p[l],n=
f.properties,f._i=l,m[0]&&n&&n[m[0]]&&(f[m[0]]=n[m[0]]),y[f[m[0]]]=f;this.mapMap=y;if(b&&m[1]){var r=m[1];b.forEach(function(b){b=v(r,b);y[b]&&g.push(y[b])})}if(e.allAreas){this.getBox(p);b=b||[];if(m[1]){var E=m[1];b.forEach(function(b){g.push(v(E,b))})}g="|"+g.map(function(b){return b&&b[m[0]]}).join("|")+"|";p.forEach(function(a){m[0]&&-1!==g.indexOf("|"+a[m[0]]+"|")||(b.push(D(a,{value:null})),d=!1)})}else this.getBox(g)}h.prototype.setData.call(this,b,a,c,d)};a.prototype.setOptions=function(b){b=
h.prototype.setOptions.call(this,b);var a=b.joinBy;null===a&&(a="_i");a=this.joinBy=E(a);a[1]||(a[1]=a[0]);return b};a.prototype.translate=function(){var b=this,a=b.xAxis,c=b.yAxis,d=b.doFullTranslate();b.generatePoints();b.data.forEach(function(e){u(e._midX)&&u(e._midY)&&(e.plotX=a.toPixels(e._midX,!0),e.plotY=c.toPixels(e._midY,!0));d&&(e.shapeType="path",e.shapeArgs={d:b.translatePath(e.path)})});y(b,"afterTranslate")};a.prototype.translatePath=function(b){var a=this.xAxis,c=this.yAxis,d=a.min,
e=a.transA,f=a.minPixelPadding,p=c.min,n=c.transA,h=c.minPixelPadding,t=[];b&&b.forEach(function(b){"M"===b[0]?t.push(["M",(b[1]-(d||0))*e+f,(b[2]-(p||0))*n+h]):"L"===b[0]?t.push(["L",(b[1]-(d||0))*e+f,(b[2]-(p||0))*n+h]):"C"===b[0]?t.push(["C",(b[1]-(d||0))*e+f,(b[2]-(p||0))*n+h,(b[3]-(d||0))*e+f,(b[4]-(p||0))*n+h,(b[5]-(d||0))*e+f,(b[6]-(p||0))*n+h]):"Q"===b[0]?t.push(["Q",(b[1]-(d||0))*e+f,(b[2]-(p||0))*n+h,(b[3]-(d||0))*e+f,(b[4]-(p||0))*n+h]):"Z"===b[0]&&t.push(["Z"])});return t};a.defaultOptions=
D(F.defaultOptions,{animation:!1,dataLabels:{crop:!1,formatter:function(){var b=this.series.chart.numberFormatter,a=this.point.value;return u(a)?b(a,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:r.neutralColor3,stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:r.neutralColor20,borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:r.neutralColor20},
inactive:{opacity:1}}});return a}(F);g(b.prototype,{type:"map",axisTypes:a.axisTypes,colorAttribs:a.colorAttribs,colorKey:a.colorKey,directTouch:!0,drawDataLabels:d,drawGraph:d,drawLegendSymbol:l.drawRectangle,forceDL:!0,getExtremesFromAll:!0,getSymbol:a.getSymbol,parallelArrays:a.parallelArrays,pointArrayMap:a.pointArrayMap,pointClass:q,preserveAspectRatio:!0,searchPoint:d,trackerGroups:a.trackerGroups,useMapGeometry:!0});c.registerSeriesType("map",b);"";return b});w(a,"Series/MapLine/MapLineSeries.js",
[a["Series/Map/MapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k,l){var g=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),q=k.series,r=l.extend,h=l.merge;l=function(c){function f(){var b=
null!==c&&c.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(f,c);f.prototype.pointAttribs=function(b,c){b=a.prototype.pointAttribs.call(this,b,c);b.fill=this.options.fillColor;return b};f.defaultOptions=h(a.defaultOptions,{lineWidth:1,fillColor:"none"});return f}(a);r(l.prototype,{type:"mapline",colorProp:"stroke",drawLegendSymbol:q.prototype.drawLegendSymbol,pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"}});k.registerSeriesType("mapline",l);"";
return l});w(a,"Series/MapPoint/MapPointPoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k){var l=this&&this.__extends||function(){var a=function(g,h){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var b in f)f.hasOwnProperty(b)&&(a[b]=f[b])};return a(g,h)};return function(g,h){function c(){this.constructor=g}a(g,h);g.prototype=null===h?Object.create(h):(c.prototype=h.prototype,new c)}}(),g=k.merge;return function(a){function k(){var h=
null!==a&&a.apply(this,arguments)||this;h.options=void 0;h.series=void 0;return h}l(k,a);k.prototype.applyOptions=function(h,c){h="undefined"!==typeof h.lat&&"undefined"!==typeof h.lon?g(h,this.series.chart.fromLatLonToPoint(h)):h;return a.prototype.applyOptions.call(this,h,c)};return k}(a.seriesTypes.scatter.prototype.pointClass)});w(a,"Series/MapPoint/MapPointSeries.js",[a["Series/MapPoint/MapPointPoint.js"],a["Core/Color/Palette.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,
k,l,g){var q=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),r=l.seriesTypes.scatter,h=g.extend,c=g.merge;g=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=
void 0;b.points=void 0;return b}q(b,a);b.prototype.drawDataLabels=function(){a.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};b.defaultOptions=c(r.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:k.neutralColor100}}});return b}(r);h(g.prototype,{type:"mappoint",forceDL:!0,pointClass:a});l.registerSeriesType("mappoint",g);"";return g});w(a,"Series/Bubble/BubbleLegendDefaults.js",
[a["Core/Color/Palette.js"]],function(a){return{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"10px",color:a.neutralColor100},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,
zThreshold:0}});w(a,"Series/Bubble/BubbleLegendItem.js",[a["Core/Color/Color.js"],a["Core/FormatUtilities.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,k,l,g){var q=a.parse,r=l.noop,h=g.arrayMax,c=g.arrayMin,f=g.isNumber,b=g.merge,e=g.pick,d=g.stableSort;"";return function(){function a(b,a){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=
this.fontMetrics=this.chart=void 0;this.setState=r;this.init(b,a)}a.prototype.init=function(b,a){this.options=b;this.visible=!0;this.chart=a.chart;this.legend=a};a.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(b){var a=this.chart,c=this.options,h=e(b.options.itemDistance,20),n=c.ranges,g=c.connectorDistance;this.fontMetrics=a.renderer.fontMetrics(c.labels.style.fontSize);n&&n.length&&f(n[0].value)?(d(n,function(b,a){return a.value-
b.value}),this.ranges=n,this.setOptions(),this.render(),b=this.getMaxLabelSize(),n=this.ranges[0].radius,a=2*n,g=g-n+b.width,g=0<g?g:0,this.maxLabel=b,this.movementX="left"===c.labels.align?g:0,this.legendItemWidth=a+g+h,this.legendItemHeight=a+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=this.ranges,c=this.options,d=this.chart.series[c.seriesIndex],f=this.legend.baseline,h={zIndex:c.zIndex,"stroke-width":c.borderWidth},g={zIndex:c.zIndex,"stroke-width":c.connectorWidth},
u={align:this.legend.options.rtl||"left"===c.labels.align?"right":"left",zIndex:c.zIndex},k=d.options.marker.fillOpacity,t=this.chart.styledMode;a.forEach(function(p,n){t||(h.stroke=e(p.borderColor,c.borderColor,d.color),h.fill=e(p.color,c.color,1!==k?q(d.color).setOpacity(k).get("rgba"):d.color),g.stroke=e(p.connectorColor,c.connectorColor,d.color));a[n].radius=this.getRangeRadius(p.value);a[n]=b(a[n],{center:a[0].radius-a[n].radius+f});t||b(!0,a[n],{bubbleAttribs:b(h),connectorAttribs:b(g),labelAttribs:u})},
this)};a.prototype.getRangeRadius=function(b){var a=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,b)};a.prototype.render=function(){var b=this.chart.renderer,a=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=
0;this.ranges.forEach(function(b){b.value>=a&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(b){var a=this.options,c=a.labels,d=this.chart,e=d.series[a.seriesIndex],f=d.renderer,h=this.symbols;d=h.labels;var n=b.center,t=Math.abs(b.radius),p=a.connectorDistance||0,g=c.align,k=a.connectorWidth,l=this.ranges[0].radius||0,m=n-t-a.borderWidth/2+k/2,q=this.fontMetrics;q=q.f/2-(q.h-q.f)/
2;var r=f.styledMode;p=this.legend.options.rtl||"left"===g?-p:p;"center"===g&&(p=0,a.connectorDistance=0,b.labelAttribs.align="center");g=m+a.labels.y;var A=l+p+a.labels.x;h.bubbleItems.push(f.circle(l,n+((m%1?1:.5)-(k%2?0:.5)),t).attr(r?{}:b.bubbleAttribs).addClass((r?"highcharts-color-"+e.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(a.className||"")).add(this.legendSymbol));h.connectors.push(f.path(f.crispLine([["M",l,m],["L",l+p,m]],a.connectorWidth)).attr(r?{}:b.connectorAttribs).addClass((r?
"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(a.connectorClassName||"")).add(this.legendSymbol));b=f.text(this.formatLabel(b),A,g+q).attr(r?{}:b.labelAttribs).css(r?{}:c.style).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);d.push(b);b.placed=!0;b.alignAttr={x:A,y:g+q}};a.prototype.getMaxLabelSize=function(){var b,a;this.symbols.labels.forEach(function(c){a=c.getBBox(!0);b=b?a.width>b.width?a:b:a});return b||
{}};a.prototype.formatLabel=function(b){var a=this.options,c=a.labels.formatter;a=a.labels.format;var d=this.chart.numberFormatter;return a?k.format(a,b):c?c.call(b):d(b.value,1)};a.prototype.hideOverlappingLabels=function(){var b=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(b.hideOverlappingLabels(a.labels),a.labels.forEach(function(b,c){b.newOpacity?b.newOpacity!==b.oldOpacity&&a.connectors[c].show():a.connectors[c].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,
d=a.options.ranges,g,k=Number.MAX_VALUE,l=-Number.MAX_VALUE;a.chart.series.forEach(function(b){b.isBubble&&!b.ignoreSeries&&(g=b.zData.filter(f),g.length&&(k=e(b.options.zMin,Math.min(k,Math.max(c(g),!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),l=e(b.options.zMax,Math.max(l,h(g)))))});var q=k===l?[{value:l}]:[{value:k},{value:(k+l)/2},{value:l,autoRanges:!0}];d.length&&d[0].radius&&q.reverse();q.forEach(function(a,c){d&&d[c]&&(q[c]=b(d[c],a))});return q};a.prototype.predictBubbleSizes=
function(){var b=this.chart,a=this.fontMetrics,c=b.legend.options,d="horizontal"===c.layout,e=d?b.legend.lastLineHeight:0,f=b.plotSizeX,h=b.plotSizeY,g=b.series[this.options.seriesIndex];b=Math.ceil(g.minPxSize);var t=Math.ceil(g.maxPxSize),p=Math.min(h,f);g=g.options.maxSize;if(c.floating||!/%$/.test(g))a=t;else if(g=parseFloat(g),a=(p+e-a.h/2)*g/100/(g/100+1),d&&h-a>=f||!d&&f-a>=h)a=t;return[b,Math.ceil(a)]};a.prototype.updateRanges=function(b,a){var c=this.legend.options.bubbleLegend;c.minSize=
b;c.maxSize=a;c.ranges=this.getRanges()};a.prototype.correctSizes=function(){var b=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),b.render())};return a}()});w(a,"Series/Bubble/BubbleLegendComposition.js",[a["Series/Bubble/BubbleLegendDefaults.js"],a["Series/Bubble/BubbleLegendItem.js"],a["Core/DefaultOptions.js"],a["Core/Utilities.js"]],function(a,k,l,g){var q=l.setOptions,r=g.addEvent,
h=g.objectEach,c=g.wrap,f;(function(b){function e(b,a,c){var e=this.legend,g=0<=d(this);if(e&&e.options.enabled&&e.bubbleLegend&&e.options.bubbleLegend.autoRanges&&g){var t=e.bubbleLegend.options;g=e.bubbleLegend.predictBubbleSizes();e.bubbleLegend.updateRanges(g[0],g[1]);t.placed||(e.group.placed=!1,e.allItems.forEach(function(b){b.legendGroup.translateY=null}));e.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();t.placed||(b.setScale(),b.updateNames(),h(b.ticks,function(b){b.isNew=
!0;b.isNewLabel=!0}))});t.placed=!0;this.getMargins();b.call(this,a,c);e.bubbleLegend.correctSizes();z(e,f(e))}else b.call(this,a,c),e&&e.options.enabled&&e.bubbleLegend&&(e.render(),z(e,f(e)))}function d(b){b=b.series;for(var a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;a++}return-1}function f(b){b=b.allItems;var a=[],c=b.length,d,e=0;for(d=0;d<c;d++)if(b[d].legendItemHeight&&(b[d].itemHeight=b[d].legendItemHeight),b[d]===b[c-1]||b[d+1]&&b[d]._legendItemPos[1]!==
b[d+1]._legendItemPos[1]){a.push({height:0});var f=a[a.length-1];for(e;e<=d;e++)b[e].itemHeight>f.height&&(f.height=b[e].itemHeight);f.step=d}return a}function g(b){var a=this.bubbleLegend,c=this.options,e=c.bubbleLegend,f=d(this.chart);a&&a.ranges&&a.ranges.length&&(e.ranges.length&&(e.autoRanges=!!e.ranges[0].autoRanges),this.destroyItem(a));0<=f&&c.enabled&&e.enabled&&(e.seriesIndex=f,this.bubbleLegend=new k(e,this),this.bubbleLegend.addToLegend(b.allItems))}function l(){var b=this.chart,a=this.visible,
c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=d(b),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)}function z(b,a){var c=b.options.rtl,d,e,f,h=0;b.allItems.forEach(function(b,g){d=b.legendGroup.translateX;e=b._legendItemPos[1];if((f=b.movementX)||c&&b.ranges)f=c?d-b.options.maxSize/2:d+f,b.legendGroup.attr({translateX:f});g>a[h].step&&h++;b.legendGroup.attr({translateY:Math.round(e+a[h].height/2)});b._legendItemPos[1]=
e+a[h].height/2})}b.compose=function(b,d,f){q({legend:{bubbleLegend:a}});r(d,"afterGetAllItems",g);r(f,"legendItemClick",l);c(b.prototype,"drawChartBox",e)}})(f||(f={}));return f});w(a,"Series/Bubble/BubblePoint.js",[a["Core/Series/Point.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k,l){var g=this&&this.__extends||function(){var a=function(g,h){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var b in f)f.hasOwnProperty(b)&&
(a[b]=f[b])};return a(g,h)};return function(g,h){function c(){this.constructor=g}a(g,h);g.prototype=null===h?Object.create(h):(c.prototype=h.prototype,new c)}}();l=l.extend;k=function(k){function l(){var a=null!==k&&k.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}g(l,k);l.prototype.haloPath=function(h){return a.prototype.haloPath.call(this,0===h?0:(this.marker?this.marker.radius||0:0)+h)};return l}(k.seriesTypes.scatter.prototype.pointClass);l(k.prototype,{ttBelow:!1});return k});
w(a,"Series/Bubble/BubbleSeries.js",[a["Core/Axis/Axis.js"],a["Series/Bubble/BubbleLegendComposition.js"],a["Series/Bubble/BubblePoint.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k,l,g,q,r,h,c){var f=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};
return b(a,c)};return function(a,c){function d(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),b=g.parse;g=q.noop;var e=h.seriesTypes;q=e.column;var d=e.scatter,A=c.arrayMax,n=c.arrayMin,x=c.clamp,z=c.extend,y=c.isNumber,v=c.merge,w=c.pick,u=c.pInt;c=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.maxPxSize=void 0;b.minPxSize=void 0;b.options=void 0;b.points=void 0;b.radii=void 0;b.yData=void 0;b.zData=void 0;
return b}f(c,a);c.prototype.animate=function(b){!b&&this.points.length<this.options.animationLimit&&this.points.forEach(function(b){var a=b.graphic;a&&a.width&&(this.hasRendered||a.attr({x:b.plotX,y:b.plotY,width:1,height:1}),a.animate(this.markerAttribs(b),this.options.animation))},this)};c.prototype.getRadii=function(b,a,c){var d=this.zData,e=this.yData,f=c.minPxSize,h=c.maxPxSize,g=[];var p=0;for(c=d.length;p<c;p++){var k=d[p];g.push(this.getRadius(b,a,f,h,k,e[p]))}this.radii=g};c.prototype.getRadius=
function(b,a,c,d,e,f){var h=this.options,g="width"!==h.sizeBy,p=h.zThreshold,k=a-b,m=.5;if(null===f||null===e)return null;if(y(e)){h.sizeByAbsoluteValue&&(e=Math.abs(e-p),k=Math.max(a-p,Math.abs(b-p)),b=0);if(e<b)return c/2-1;0<k&&(m=(e-b)/k)}g&&0<=m&&(m=Math.sqrt(m));return Math.ceil(c+m*(d-c))/2};c.prototype.hasData=function(){return!!this.processedXData.length};c.prototype.pointAttribs=function(a,c){var d=this.options.marker.fillOpacity;a=r.prototype.pointAttribs.call(this,a,c);1!==d&&(a.fill=
b(a.fill).setOpacity(d).get("rgba"));return a};c.prototype.translate=function(){var b,c=this.data,d=this.radii;a.prototype.translate.call(this);for(b=c.length;b--;){var e=c[b];var f=d?d[b]:0;y(f)&&f>=this.minPxSize/2?(e.marker=z(e.marker,{radius:f,width:2*f,height:2*f}),e.dlBox={x:e.plotX-f,y:e.plotY-f,width:2*f,height:2*f}):e.shapeArgs=e.plotY=e.dlBox=void 0}};c.compose=k.compose;c.defaultOptions=v(d.defaultOptions,{dataLabels:{formatter:function(){var b=this.series.chart.numberFormatter,a=this.point.z;
return y(a)?b(a,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});return c}(d);z(c.prototype,{alignDataLabel:q.prototype.alignDataLabel,applyZones:g,bubblePadding:!0,buildKDTree:g,directTouch:!0,isBubble:!0,
pointArrayMap:["y","z"],pointClass:l,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});a.prototype.beforePadding=function(){var b=this,a=this.len,c=this.chart,d=0,e=a,f=this.isXAxis,h=f?"xData":"yData",g=this.min,k={},l=Math.min(c.plotWidth,c.plotHeight),q=Number.MAX_VALUE,r=-Number.MAX_VALUE,v=this.max-g,z=a/v,C=[];this.series.forEach(function(a){var d=a.options;!a.bubblePadding||!a.visible&&c.options.chart.ignoreHiddenSeries||(b.allowZoomOutside=
!0,C.push(a),f&&(["minSize","maxSize"].forEach(function(b){var a=d[b],c=/%$/.test(a);a=u(a);k[b]=c?l*a/100:a}),a.minPxSize=k.minSize,a.maxPxSize=Math.max(k.maxSize,k.minSize),a=a.zData.filter(y),a.length&&(q=w(d.zMin,x(n(a),!1===d.displayNegative?d.zThreshold:-Number.MAX_VALUE,q)),r=w(d.zMax,Math.max(r,A(a))))))});C.forEach(function(a){var c=a[h],k=c.length;f&&a.getRadii(q,r,a);if(0<v)for(;k--;)if(y(c[k])&&b.dataMin<=c[k]&&c[k]<=b.max){var p=a.radii?a.radii[k]:0;d=Math.min((c[k]-g)*z-p,d);e=Math.max((c[k]-
g)*z+p,e)}});C.length&&0<v&&!this.logarithmic&&(e-=a,z*=(a+Math.max(0,d)-Math.min(e,a))/a,[["min","userMin",d],["max","userMax",e]].forEach(function(a){"undefined"===typeof w(b.options[a[0]],b[a[1]])&&(b[a[0]]+=a[2]/z)}))};h.registerSeriesType("bubble",c);"";"";return c});w(a,"Series/MapBubble/MapBubblePoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k){var l=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,f)};return function(c,f){function b(){this.constructor=c}a(c,f);c.prototype=null===f?Object.create(f):(b.prototype=f.prototype,new b)}}(),g=a.seriesTypes,q=g.map;a=k.extend;var r=k.merge;k=function(a){function c(){return null!==a&&a.apply(this,arguments)||this}l(c,a);c.prototype.applyOptions=function(c,b){return c&&"undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?a.prototype.applyOptions.call(this,
r(c,this.series.chart.fromLatLonToPoint(c)),b):q.prototype.pointClass.prototype.applyOptions.call(this,c,b)};c.prototype.isValid=function(){return"number"===typeof this.z};return c}(g.bubble.prototype.pointClass);a(k.prototype,{ttBelow:!1});return k});w(a,"Series/MapBubble/MapBubbleSeries.js",[a["Series/Bubble/BubbleSeries.js"],a["Series/MapBubble/MapBubblePoint.js"],a["Series/Map/MapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k,l,g,q){var r=this&&this.__extends||
function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),h=q.extend,c=q.merge;q=function(f){function b(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(b,f);b.defaultOptions=
c(a.defaultOptions,{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}});return b}(a);h(q.prototype,{type:"mapbubble",getBox:l.prototype.getBox,pointArrayMap:["z"],pointClass:k,setData:l.prototype.setData,setOptions:l.prototype.setOptions,xyFromShape:!0});g.registerSeriesType("mapbubble",q);"";return q});w(a,"Series/Heatmap/HeatmapPoint.js",[a["Mixins/ColorMapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,k,l){var g=this&&this.__extends||function(){var a=
function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}();a=a.colorMapPointMixin;var q=l.clamp,r=l.extend,h=l.pick;k=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.options=void 0;b.series=void 0;b.value=void 0;b.x=void 0;
b.y=void 0;return b}g(c,a);c.prototype.applyOptions=function(b,c){b=a.prototype.applyOptions.call(this,b,c);b.formatPrefix=b.isNull||null===b.value?"null":"point";return b};c.prototype.getCellAttributes=function(){var b=this.series,a=b.options,c=(a.colsize||1)/2,f=(a.rowsize||1)/2,g=b.xAxis,k=b.yAxis,l=this.options.marker||b.options.marker;b=b.pointPlacementToXValue();var r=h(this.pointPadding,a.pointPadding,0),v={x1:q(Math.round(g.len-(g.translate(this.x-c,!1,!0,!1,!0,-b)||0)),-g.len,2*g.len),x2:q(Math.round(g.len-
(g.translate(this.x+c,!1,!0,!1,!0,-b)||0)),-g.len,2*g.len),y1:q(Math.round(k.translate(this.y-f,!1,!0,!1,!0)||0),-k.len,2*k.len),y2:q(Math.round(k.translate(this.y+f,!1,!0,!1,!0)||0),-k.len,2*k.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var c=a+"1",d=a+"2",e=Math.abs(v[c]-v[d]),f=l&&l.lineWidth||0,g=Math.abs(v[c]+v[d])/2;l[b]&&l[b]<e&&(v[c]=g-l[b]/2-f/2,v[d]=g+l[b]/2+f/2);r&&("y"===a&&(c=d,d=a+"1"),v[c]+=r,v[d]-=r)});return v};c.prototype.haloPath=function(a){if(!a)return[];
var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]};c.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return c}(k.seriesTypes.scatter.prototype.pointClass);r(k.prototype,{dataLabelOnNull:a.dataLabelOnNull,moveToTopOnHover:a.moveToTopOnHover});return k});w(a,"Series/Heatmap/HeatmapSeries.js",[a["Core/Color/Color.js"],a["Mixins/ColorMapSeries.js"],a["Series/Heatmap/HeatmapPoint.js"],a["Mixins/LegendSymbol.js"],
a["Core/Color/Palette.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,k,l,g,q,r,h,c){var f=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}();
k=k.colorMapSeriesMixin;var b=r.series,e=r.seriesTypes,d=e.column,A=e.scatter,n=h.prototype.symbols,x=c.extend,w=c.fireEvent,y=c.isNumber,v=c.merge,z=c.pick;h=function(c){function d(){var a=null!==c&&c.apply(this,arguments)||this;a.colorAxis=void 0;a.data=void 0;a.options=void 0;a.points=void 0;a.valueMax=NaN;a.valueMin=NaN;return a}f(d,c);d.prototype.drawPoints=function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)b.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&
(b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b)),a.options.borderRadius&&b.graphic.attr({r:a.options.borderRadius}),null===b.value&&b.graphic.addClass("highcharts-null-point"))})};d.prototype.getExtremes=function(){var a=b.prototype.getExtremes.call(this,this.valueData),c=a.dataMin;a=a.dataMax;y(c)&&(this.valueMin=c);y(a)&&(this.valueMax=a);return b.prototype.getExtremes.call(this)};d.prototype.getValidPoints=function(a,c){return b.prototype.getValidPoints.call(this,a,c,!0)};d.prototype.hasData=
function(){return!!this.processedXData.length};d.prototype.init=function(){b.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=z(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;n.ellipse=n.circle};d.prototype.markerAttribs=function(a,b){var c=a.marker||{},d=this.options.marker||{},e=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var g=d.states[b]||{};var h=c.states&&c.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=
(h[a[0]]||g[a[0]]||e[a[0]])+(h[a[0]+"Plus"]||g[a[0]+"Plus"]||0);f[a[1]]=e[a[1]]+(e[a[0]]-f[a[0]])/2})}return b?f:e};d.prototype.pointAttribs=function(c,d){var e=b.prototype.pointAttribs.call(this,c,d),f=this.options||{},g=this.chart.options.plotOptions||{},h=g.series||{},k=g.heatmap||{};g=c&&c.options.borderColor||f.borderColor||k.borderColor||h.borderColor;h=c&&c.options.borderWidth||f.borderWidth||k.borderWidth||h.borderWidth||e["stroke-width"];e.stroke=c&&c.marker&&c.marker.lineColor||f.marker&&
f.marker.lineColor||g||this.color;e["stroke-width"]=h;d&&(c=v(f.states[d],f.marker&&f.marker.states[d],c&&c.options.states&&c.options.states[d]||{}),d=c.brightness,e.fill=c.color||a.parse(e.fill).brighten(d||0).get(),e.stroke=c.lineColor);return e};d.prototype.setClip=function(a){var c=this.chart;b.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?c.sharedClips[this.sharedClipKey]:c.clipRect)};d.prototype.translate=function(){var a=
this.options,b=a.marker&&a.marker.symbol||"rect",c=n[b]?b:"rect",d=-1!==["circle","square"].indexOf(c);this.generatePoints();this.points.forEach(function(a){var e=a.getCellAttributes(),f={};f.x=Math.min(e.x1,e.x2);f.y=Math.min(e.y1,e.y2);f.width=Math.max(Math.abs(e.x2-e.x1),0);f.height=Math.max(Math.abs(e.y2-e.y1),0);var g=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(d){var h=Math.abs(f.width-f.height);f.x=Math.min(e.x1,e.x2)+(f.width<f.height?0:h/2);f.y=Math.min(e.y1,e.y2)+
(f.width<f.height?h/2:0);f.width=f.height=Math.min(f.width,f.height)}h={plotX:(e.x1+e.x2)/2,plotY:(e.y1+e.y2)/2,clientX:(e.x1+e.x2)/2,shapeType:"path",shapeArgs:v(!0,f,{d:n[c](f.x,f.y,f.width,f.height)})};g&&(a.marker={width:f.width,height:f.height});x(a,h)});w(this,"afterTranslate")};d.defaultOptions=v(A.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,nullColor:q.neutralColor3,dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return y(b)?a(b,-1):
""},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}});return d}(A);x(h.prototype,{alignDataLabel:d.prototype.alignDataLabel,axisTypes:k.axisTypes,colorAttribs:k.colorAttribs,colorKey:k.colorKey,directTouch:!0,drawLegendSymbol:g.drawRectangle,getExtremesFromAll:!0,getSymbol:b.prototype.getSymbol,
parallelArrays:k.parallelArrays,pointArrayMap:["y","value"],pointClass:l,trackerGroups:k.trackerGroups});r.registerSeriesType("heatmap",h);"";"";return h});w(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/FormatUtilities.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,k,l,g){function q(a,b){var c,d=!1,e=a.x,f=a.y;a=0;for(c=b.length-1;a<b.length;c=a++){var g=b[a][1]>f;var h=b[c][1]>f;g!==h&&e<(b[c][0]-b[a][0])*(f-b[a][1])/(b[c][1]-b[a][1])+b[a][0]&&(d=!d)}return d}var r=k.format,
h=l.win,c=g.error,f=g.extend,b=g.merge;k=g.wrap;"";a.prototype.transformFromLatLon=function(a,b){var d=this.userOptions.chart&&this.userOptions.chart.proj4||h.proj4;if(!d)return c(21,!1,this),{x:0,y:null};a=d(b.crs,[a.lon,a.lat]);d=b.cosAngle||b.rotation&&Math.cos(b.rotation);var e=b.sinAngle||b.rotation&&Math.sin(b.rotation);a=b.rotation?[a[0]*d+a[1]*e,-a[0]*e+a[1]*d]:a;return{x:((a[0]-(b.xoffset||0))*(b.scale||1)+(b.xpan||0))*(b.jsonres||1)+(b.jsonmarginX||0),y:(((b.yoffset||0)-a[1])*(b.scale||
1)+(b.ypan||0))*(b.jsonres||1)-(b.jsonmarginY||0)}};a.prototype.transformToLatLon=function(a,b){if("undefined"===typeof h.proj4)c(21,!1,this);else{a={x:((a.x-(b.jsonmarginX||0))/(b.jsonres||1)-(b.xpan||0))/(b.scale||1)+(b.xoffset||0),y:((-a.y-(b.jsonmarginY||0))/(b.jsonres||1)+(b.ypan||0))/(b.scale||1)+(b.yoffset||0)};var d=b.cosAngle||b.rotation&&Math.cos(b.rotation),e=b.sinAngle||b.rotation&&Math.sin(b.rotation);b=h.proj4(b.crs,"WGS84",b.rotation?{x:a.x*d+a.y*-e,y:a.x*e+a.y*d}:a);return{lat:b.y,
lon:b.x}}};a.prototype.fromPointToLatLon=function(a){var b=this.mapTransforms,e;if(b){for(e in b)if(Object.hasOwnProperty.call(b,e)&&b[e].hitZone&&q({x:a.x,y:-a.y},b[e].hitZone.coordinates[0]))return this.transformToLatLon(a,b[e]);return this.transformToLatLon(a,b["default"])}c(22,!1,this)};a.prototype.fromLatLonToPoint=function(a){var b=this.mapTransforms,e;if(!b)return c(22,!1,this),{x:0,y:null};for(e in b)if(Object.hasOwnProperty.call(b,e)&&b[e].hitZone){var f=this.transformFromLatLon(a,b[e]);
if(q({x:f.x,y:-f.y},b[e].hitZone.coordinates[0]))return f}return this.transformFromLatLon(a,b["default"])};l.geojson=function(a,b,c){var d=[],e=[],g=function(a){a.forEach(function(a,b){0===b?e.push(["M",a[0],-a[1]]):e.push(["L",a[0],-a[1]])})};b=b||"map";a.features.forEach(function(a){var c=a.geometry,h=c.type;c=c.coordinates;a=a.properties;var k;e=[];"map"===b||"mapbubble"===b?("Polygon"===h?(c.forEach(g),e.push(["Z"])):"MultiPolygon"===h&&(c.forEach(function(a){a.forEach(g)}),e.push(["Z"])),e.length&&
(k={path:e})):"mapline"===b?("LineString"===h?g(c):"MultiLineString"===h&&c.forEach(g),e.length&&(k={path:e})):"mappoint"===b&&"Point"===h&&(k={x:c[0],y:-c[1]});k&&d.push(f(k,{name:a.name||a.NAME,properties:a}))});c&&a.copyrightShort&&(c.chart.mapCredits=r(c.chart.options.credits.mapText,{geojson:a}),c.chart.mapCreditsFull=r(c.chart.options.credits.mapTextFull,{geojson:a}));return d};k(a.prototype,"addCredits",function(a,c){c=b(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,
c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});w(a,"masters/modules/map.src.js",[a["Core/Globals.js"],a["Core/Chart/MapChart.js"]],function(a,k){a.MapChart=k;a.mapChart=a.Map=k.mapChart;a.maps=k.maps})});
//# sourceMappingURL=map.js.map