/*
 Highstock JS v9.1.2 (2021-07-09)

 Highcharts Stock as a plugin for Highcharts

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(G){a(G);a.Highcharts=G;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function G(a,p,w,v){a.hasOwnProperty(p)||(a[p]=v.apply(null,w))}a=a?a._modules:{};G(a,"Core/Axis/NavigatorAxis.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,p){var w=a.isTouchDevice,v=p.addEvent,
g=p.correctFloat,H=p.defined,u=p.isNumber,D=p.pick,c=function(){function b(b){this.axis=b}b.prototype.destroy=function(){this.axis=void 0};b.prototype.toFixedRange=function(b,c,a,K){var h=this.axis,z=h.chart;z=z&&z.fixedRange;var Q=(h.pointRange||0)/2;b=D(a,h.translate(b,!0,!h.horiz));c=D(K,h.translate(c,!0,!h.horiz));h=z&&(c-b)/z;H(a)||(b=g(b+Q));H(K)||(c=g(c-Q));.7<h&&1.3>h&&(K?b=c-z:c=b+z);u(b)&&u(c)||(b=c=void 0);return{min:b,max:c}};return b}();return function(){function b(){}b.compose=function(b){b.keepProps.push("navigatorAxis");
v(b,"init",function(){this.navigatorAxis||(this.navigatorAxis=new c(this))});v(b,"zoom",function(b){var c=this.chart.options,a=c.navigator,h=this.navigatorAxis,z=c.chart.pinchType,Q=c.rangeSelector;c=c.chart.zoomType;this.isXAxis&&(a&&a.enabled||Q&&Q.enabled)&&("y"===c?b.zoomed=!1:(!w&&"xy"===c||w&&"xy"===z)&&this.options.range&&(a=h.previousZoom,H(b.newMin)?h.previousZoom=[this.min,this.max]:a&&(b.newMin=a[0],b.newMax=a[1],h.previousZoom=void 0)));"undefined"!==typeof b.zoomed&&b.preventDefault()})};
b.AdditionsClass=c;return b}()});G(a,"Core/Axis/ScrollbarAxis.js",[a["Core/Utilities.js"]],function(a){var p=a.addEvent,w=a.defined,v=a.pick;return function(){function a(){}a.compose=function(g,u){if(-1===a.composed.indexOf(g))a.composed.push(g);else return g;var D=function(c){var b=v(c.options&&c.options.min,c.min),a=v(c.options&&c.options.max,c.max);return{axisMin:b,axisMax:a,scrollMin:w(c.dataMin)?Math.min(b,c.min,c.dataMin,v(c.threshold,Infinity)):b,scrollMax:w(c.dataMax)?Math.max(a,c.max,c.dataMax,
v(c.threshold,-Infinity)):a}};p(g,"afterInit",function(){var c=this;c.options&&c.options.scrollbar&&c.options.scrollbar.enabled&&(c.options.scrollbar.vertical=!c.horiz,c.options.startOnTick=c.options.endOnTick=!1,c.scrollbar=new u(c.chart.renderer,c.options.scrollbar,c.chart),p(c.scrollbar,"changed",function(b){var a=D(c),h=a.axisMax,B=a.scrollMin,g=a.scrollMax-B;w(a.axisMin)&&w(h)&&(c.horiz&&!c.reversed||!c.horiz&&c.reversed?(a=B+g*this.to,B+=g*this.from):(a=B+g*(1-this.from),B+=g*(1-this.to)),this.shouldUpdateExtremes(b.DOMType)?
c.setExtremes(B,a,!0,"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType,b):this.setRange(this.from,this.to))}))});p(g,"afterRender",function(){var c=D(this),b=c.scrollMin,a=c.scrollMax;c=this.scrollbar;var h=this.axisTitleMargin+(this.titleOffset||0),g=this.chart.scrollbarsOffsets,u=this.options.margin||0;c&&(this.horiz?(this.opposite||(g[1]+=h),c.position(this.left,this.top+this.height+2+g[1]-(this.opposite?u:0),this.width,this.height),this.opposite||(g[1]+=u),h=1):(this.opposite&&(g[0]+=h),c.position(this.left+
this.width+2+g[0]-(this.opposite?0:u),this.top,this.width,this.height),this.opposite&&(g[0]+=u),h=0),g[h]+=c.size+c.options.margin,isNaN(b)||isNaN(a)||!w(this.min)||!w(this.max)||this.min===this.max?c.setRange(0,1):(g=(this.min-b)/(a-b),b=(this.max-b)/(a-b),this.horiz&&!this.reversed||!this.horiz&&this.reversed?c.setRange(g,b):c.setRange(1-b,1-g)))});p(g,"afterGetOffset",function(){var c=this.horiz?2:1,b=this.scrollbar;b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=b.size+b.options.margin)});
return g};a.composed=[];return a}()});G(a,"Core/ScrollbarDefaults.js",[a["Core/Globals.js"],a["Core/Color/Palette.js"]],function(a,p){return{height:a.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:p.neutralColor20,barBorderWidth:1,barBorderColor:p.neutralColor20,buttonArrowColor:p.neutralColor80,buttonBackgroundColor:p.neutralColor10,buttonBorderColor:p.neutralColor20,buttonBorderWidth:1,rifleColor:p.neutralColor80,
trackBackgroundColor:p.neutralColor5,trackBorderColor:p.neutralColor5,trackBorderWidth:1}});G(a,"Core/Scrollbar.js",[a["Core/DefaultOptions.js"],a["Core/Globals.js"],a["Core/Axis/ScrollbarAxis.js"],a["Core/ScrollbarDefaults.js"],a["Core/Utilities.js"]],function(a,p,w,v,g){var H=a.defaultOptions,u=g.addEvent,D=g.correctFloat,c=g.defined,b=g.destroyObjectProperties,C=g.fireEvent,h=g.merge,B=g.pick,K=g.removeEvent;a=function(){function a(a,b,A){this._events=[];this.chart=void 0;this.from=this.chartY=
this.chartX=0;this.scrollbar=this.renderer=this.options=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions=void 0;this.y=this.x=0;this.init(a,b,A)}a.compose=function(b){w.compose(b,a)};a.swapXY=function(a,b){b&&a.forEach(function(a){for(var b=a.length,x,l=0;l<b;l+=2)x=a[l+1],"number"===typeof x&&(a[l+1]=a[l+
2],a[l+2]=x)});return a};a.prototype.addEvents=function(){var a=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,c=this.scrollbarGroup.element,I=this.track.element,x=this.mouseDownHandler.bind(this),l=this.mouseMoveHandler.bind(this),m=this.mouseUpHandler.bind(this);a=[[b[a[0]].element,"click",this.buttonToMinClick.bind(this)],[b[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[I,"click",this.trackClick.bind(this)],[c,"mousedown",x],[c.ownerDocument,"mousemove",l],[c.ownerDocument,
"mouseup",m]];p.hasTouch&&a.push([c,"touchstart",x],[c.ownerDocument,"touchmove",l],[c.ownerDocument,"touchend",m]);a.forEach(function(a){u.apply(null,a)});this._events=a};a.prototype.buttonToMaxClick=function(a){var b=(this.to-this.from)*B(this.options.step,.2);this.updatePosition(this.from+b,this.to+b);C(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.buttonToMinClick=function(a){var b=D(this.to-this.from)*B(this.options.step,.2);this.updatePosition(D(this.from-
b),D(this.to-b));C(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.cursorToScrollbarPosition=function(a){var b=this.options;b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}};a.prototype.destroy=function(){var a=this,c=a.chart.scroller;a.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(b){a[b]&&
a[b].destroy&&(a[b]=a[b].destroy())});c&&a===c.scrollbar&&(c.scrollbar=null,b(c.scrollbarButtons))};a.prototype.drawScrollbarButton=function(b){var c=this.renderer,A=this.scrollbarButtons,z=this.options,x=this.size,l=c.g().add(this.group);A.push(l);l=c.rect().addClass("highcharts-scrollbar-button").add(l);this.chart.styledMode||l.attr({stroke:z.buttonBorderColor,"stroke-width":z.buttonBorderWidth,fill:z.buttonBackgroundColor});l.attr(l.crisp({x:-.5,y:-.5,width:x+1,height:x+1,r:z.buttonBorderRadius},
l.strokeWidth()));l=c.path(a.swapXY([["M",x/2+(b?-1:1),x/2-3],["L",x/2+(b?-1:1),x/2+3],["L",x/2+(b?2:-2),x/2]],z.vertical)).addClass("highcharts-scrollbar-arrow").add(A[b]);this.chart.styledMode||l.attr({fill:z.buttonArrowColor})};a.prototype.init=function(a,b,c){this.scrollbarButtons=[];this.renderer=a;this.userOptions=b;this.options=h(v,H.scrollbar,b);this.chart=c;this.size=B(this.options.size,this.options.height);b.enabled&&(this.render(),this.addEvents())};a.prototype.mouseDownHandler=function(a){a=
this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};a.prototype.mouseMoveHandler=function(a){var b=this.chart.pointer.normalize(a),c=this.options.vertical?"chartY":"chartX",z=this.initPositions||[];!this.grabbedCenter||a.touches&&0===a.touches[0][c]||(b=this.cursorToScrollbarPosition(b)[c],c=this[c],c=b-c,this.hasDragged=!0,this.updatePosition(z[0]+c,z[1]+c),this.hasDragged&&C(this,
"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};a.prototype.mouseUpHandler=function(a){this.hasDragged&&C(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};a.prototype.position=function(a,b,c,h){var x=this.options.vertical,l=this.rendered?"animate":"attr",m=0;this.x=a;this.y=b+this.trackBorderWidth;this.width=c;this.xOffset=this.height=h;this.yOffset=m;x?
(this.width=this.yOffset=c=m=this.size,this.xOffset=b=0,this.barWidth=h-2*c,this.x=a+=this.options.margin):(this.height=this.xOffset=h=b=this.size,this.barWidth=c-2*h,this.y+=this.options.margin);this.group[l]({translateX:a,translateY:this.y});this.track[l]({width:c,height:h});this.scrollbarButtons[1][l]({translateX:x?0:c-b,translateY:x?h-m:0})};a.prototype.removeEvents=function(){this._events.forEach(function(a){K.apply(null,a)});this._events.length=0};a.prototype.render=function(){var b=this.renderer,
c=this.options,A=this.size,h=this.chart.styledMode,x=b.g("scrollbar").attr({zIndex:c.zIndex,translateY:-99999}).add();this.group=x;this.track=b.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:c.trackBorderRadius||0,height:A,width:A}).add(x);h||this.track.attr({fill:c.trackBackgroundColor,stroke:c.trackBorderColor,"stroke-width":c.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=b.g().add(x);this.scrollbar=
b.rect().addClass("highcharts-scrollbar-thumb").attr({height:A,width:A,r:c.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=b.path(a.swapXY([["M",-3,A/4],["L",-3,2*A/3],["M",0,A/4],["L",0,2*A/3],["M",3,A/4],["L",3,2*A/3]],c.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);h||(this.scrollbar.attr({fill:c.barBackgroundColor,stroke:c.barBorderColor,"stroke-width":c.barBorderWidth}),this.scrollbarRifles.attr({stroke:c.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=
this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};a.prototype.setRange=function(a,b){var A=this.options,h=A.vertical,x=A.minWidth,l=this.barWidth,m=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(c(l)){var q=l*Math.min(b,1);a=Math.max(a,0);var J=Math.ceil(l*a);this.calculatedWidth=q=D(q-J);q<x&&(J=(l-x+q)*a,q=x);
x=Math.floor(J+this.xOffset+this.yOffset);l=q/2-.5;this.from=a;this.to=b;h?(this.scrollbarGroup[m]({translateY:x}),this.scrollbar[m]({height:q}),this.scrollbarRifles[m]({translateY:l}),this.scrollbarTop=x,this.scrollbarLeft=0):(this.scrollbarGroup[m]({translateX:x}),this.scrollbar[m]({width:q}),this.scrollbarRifles[m]({translateX:l}),this.scrollbarLeft=x,this.scrollbarTop=0);12>=q?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===A.showFull&&(0>=a&&1<=b?this.group.hide():this.group.show());
this.rendered=!0}};a.prototype.shouldUpdateExtremes=function(a){return B(this.options.liveRedraw,p.svg&&!p.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===a||"touchend"===a||!c(a)};a.prototype.trackClick=function(a){var b=this.chart.pointer.normalize(a),c=this.to-this.from,h=this.y+this.scrollbarTop,x=this.x+this.scrollbarLeft;this.options.vertical&&b.chartY>h||!this.options.vertical&&b.chartX>x?this.updatePosition(this.from+c,this.to+c):this.updatePosition(this.from-c,this.to-c);C(this,"changed",
{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.update=function(a){this.destroy();this.init(this.chart.renderer,h(!0,this.options,a),this.chart)};a.prototype.updatePosition=function(a,b){1<b&&(a=D(1-D(b-a)),b=1);0>a&&(b=D(b-a),a=0);this.from=a;this.to=b};a.defaultOptions=v;return a}();H.scrollbar=h(!0,a.defaultOptions,H.scrollbar);return a});G(a,"Core/Navigator.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Axis/NavigatorAxis.js"],
a["Core/DefaultOptions.js"],a["Core/Color/Palette.js"],a["Core/Renderer/RendererRegistry.js"],a["Core/Scrollbar.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,w,v,g,H,u,D,c,b,C,h){w=w.parse;var B=v.hasTouch,K=v.isTouchDevice,P=H.defaultOptions,z=h.addEvent,Q=h.clamp,A=h.correctFloat,I=h.defined,x=h.destroyObjectProperties,l=h.erase,m=h.extend,q=h.find,J=h.isArray,N=h.isNumber,F=h.merge,r=h.pick,E=h.removeEvent,t=h.splat,k=function(e){for(var d=
[],f=1;f<arguments.length;f++)d[f-1]=arguments[f];d=[].filter.call(d,N);if(d.length)return Math[e].apply(0,d)};H="undefined"===typeof C.seriesTypes.areaspline?"line":"areaspline";m(P,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:u.neutralColor5,borderColor:u.neutralColor40},maskFill:w(u.highlightColor60).setOpacity(.3).get(),outlineColor:u.neutralColor20,outlineWidth:1,series:{type:H,
fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,firstAnchor:"firstPoint",anchor:"middle",lastAnchor:"lastPoint",units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},
threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:u.neutralColor10,gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:u.neutralColor40},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});D.getRendererType().prototype.symbols["navigator-handle"]=
function(e,d,f,y,k){e=(k&&k.width||0)/2;d=Math.round(e/3)+.5;k=k&&k.height||0;return[["M",-e-1,.5],["L",e,.5],["L",e,k+.5],["L",-e-1,k+.5],["L",-e-1,.5],["M",-d,4],["L",-d,k-3],["M",d-1,4],["L",d-1,k-3]]};var n=function(){function e(d){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=
this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(d)}e.prototype.drawHandle=function(d,f,e,k){var y=this.navigatorOptions.handles.height;this.handles[f][k](e?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(d,10)+.5-y)}:{translateX:Math.round(this.left+parseInt(d,10)),translateY:Math.round(this.top+this.height/2-y/2-1)})};e.prototype.drawOutline=function(d,f,e,k){var y=this.navigatorOptions.maskInside,n=this.outline.strokeWidth(),a=n/2,b=n%
2/2;n=this.outlineHeight;var t=this.scrollbarHeight||0,L=this.size,c=this.left-t,r=this.top;e?(c-=a,e=r+f+b,f=r+d+b,b=[["M",c+n,r-t-b],["L",c+n,e],["L",c,e],["L",c,f],["L",c+n,f],["L",c+n,r+L+t]],y&&b.push(["M",c+n,e-a],["L",c+n,f+a])):(d+=c+t-b,f+=c+t-b,r+=a,b=[["M",c,r],["L",d,r],["L",d,r+n],["L",f,r+n],["L",f,r],["L",c+L+2*t,r]],y&&b.push(["M",d-a,r],["L",f+a,r]));this.outline[k]({d:b})};e.prototype.drawMasks=function(d,f,e,k){var y=this.left,n=this.top,a=this.height;if(e){var b=[y,y,y];var t=
[n,n+d,n+f];var c=[a,a,a];var L=[d,f-d,this.size-f]}else b=[y,y+d,y+f],t=[n,n,n],c=[d,f-d,this.size-f],L=[a,a,a];this.shades.forEach(function(d,f){d[k]({x:b[f],y:t[f],width:c[f],height:L[f]})})};e.prototype.renderElements=function(){var d=this,f=d.navigatorOptions,e=f.maskInside,k=d.chart,n=k.renderer,a,b={cursor:k.inverted?"ns-resize":"ew-resize"};d.navigatorGroup=a=n.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!e,e,!e].forEach(function(e,y){d.shades[y]=n.rect().addClass("highcharts-navigator-mask"+
(1===y?"-inside":"-outside")).add(a);k.styledMode||d.shades[y].attr({fill:e?f.maskFill:"rgba(0,0,0,0)"}).css(1===y&&b)});d.outline=n.path().addClass("highcharts-navigator-outline").add(a);k.styledMode||d.outline.attr({"stroke-width":f.outlineWidth,stroke:f.outlineColor});f.handles.enabled&&[0,1].forEach(function(e){f.handles.inverted=k.inverted;d.handles[e]=n.symbol(f.handles.symbols[e],-f.handles.width/2-1,0,f.handles.width,f.handles.height,f.handles);d.handles[e].attr({zIndex:7-e}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+
["left","right"][e]).add(a);if(!k.styledMode){var y=f.handles;d.handles[e].attr({fill:y.backgroundColor,stroke:y.borderColor,"stroke-width":y.lineWidth}).css(b)}})};e.prototype.update=function(d){(this.series||[]).forEach(function(d){d.baseSeries&&delete d.baseSeries.navigatorSeries});this.destroy();F(!0,this.chart.options.navigator,this.options,d);this.init(this.chart)};e.prototype.render=function(d,f,e,k){var n=this.chart,y=this.scrollbarHeight,a,b=this.xAxis,t=b.pointRange||0;var c=b.navigatorAxis.fake?
n.xAxis[0]:b;var L=this.navigatorEnabled,m,l=this.rendered;var q=n.inverted;var x=n.xAxis[0].minRange,E=n.xAxis[0].options.maxRange;if(!this.hasDragged||I(e)){d=A(d-t/2);f=A(f+t/2);if(!N(d)||!N(f))if(l)e=0,k=r(b.width,c.width);else return;this.left=r(b.left,n.plotLeft+y+(q?n.plotWidth:0));this.size=m=a=r(b.len,(q?n.plotHeight:n.plotWidth)-2*y);n=q?y:a+2*y;e=r(e,b.toPixels(d,!0));k=r(k,b.toPixels(f,!0));N(e)&&Infinity!==Math.abs(e)||(e=0,k=n);d=b.toValue(e,!0);f=b.toValue(k,!0);var F=Math.abs(A(f-
d));F<x?this.grabbedLeft?e=b.toPixels(f-x-t,!0):this.grabbedRight&&(k=b.toPixels(d+x+t,!0)):I(E)&&A(F-t)>E&&(this.grabbedLeft?e=b.toPixels(f-E-t,!0):this.grabbedRight&&(k=b.toPixels(d+E+t,!0)));this.zoomedMax=Q(Math.max(e,k),0,m);this.zoomedMin=Q(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(e,k),0,m);this.range=this.zoomedMax-this.zoomedMin;m=Math.round(this.zoomedMax);e=Math.round(this.zoomedMin);L&&(this.navigatorGroup.attr({visibility:"visible"}),l=l&&!this.hasDragged?"animate":"attr",
this.drawMasks(e,m,q,l),this.drawOutline(e,m,q,l),this.navigatorOptions.handles.enabled&&(this.drawHandle(e,0,q,l),this.drawHandle(m,1,q,l)));this.scrollbar&&(q?(q=this.top-y,c=this.left-y+(L||!c.opposite?0:(c.titleOffset||0)+c.axisTitleMargin),y=a+2*y):(q=this.top+(L?this.height:-y),c=this.left-y),this.scrollbar.position(c,q,n,y),this.scrollbar.setRange(this.zoomedMin/(a||1),this.zoomedMax/(a||1)));this.rendered=!0}};e.prototype.addMouseEvents=function(){var d=this,f=d.chart,e=f.container,k=[],n,
a;d.mouseMoveHandler=n=function(f){d.onMouseMove(f)};d.mouseUpHandler=a=function(f){d.onMouseUp(f)};k=d.getPartsEvents("mousedown");k.push(z(f.renderTo,"mousemove",n),z(e.ownerDocument,"mouseup",a));B&&(k.push(z(f.renderTo,"touchmove",n),z(e.ownerDocument,"touchend",a)),k.concat(d.getPartsEvents("touchstart")));d.eventsToUnbind=k;d.series&&d.series[0]&&k.push(z(d.series[0].xAxis,"foundExtremes",function(){f.navigator.modifyNavigatorAxisExtremes()}))};e.prototype.getPartsEvents=function(d){var f=this,
e=[];["shades","handles"].forEach(function(k){f[k].forEach(function(n,y){e.push(z(n.element,d,function(d){f[k+"Mousedown"](d,y)}))})});return e};e.prototype.shadesMousedown=function(d,f){d=this.chart.pointer.normalize(d);var e=this.chart,k=this.xAxis,n=this.zoomedMin,a=this.left,b=this.size,t=this.range,c=d.chartX;e.inverted&&(c=d.chartY,a=this.top);if(1===f)this.grabbedCenter=c,this.fixedWidth=t,this.dragOffset=c-n;else{d=c-a-t/2;if(0===f)d=Math.max(0,d);else if(2===f&&d+t>=b)if(d=b-t,this.reversedExtremes){d-=
t;var r=this.getUnionExtremes().dataMin}else var m=this.getUnionExtremes().dataMax;d!==n&&(this.fixedWidth=t,f=k.navigatorAxis.toFixedRange(d,d+t,r,m),I(f.min)&&e.xAxis[0].setExtremes(Math.min(f.min,f.max),Math.max(f.min,f.max),!0,null,{trigger:"navigator"}))}};e.prototype.handlesMousedown=function(d,f){this.chart.pointer.normalize(d);d=this.chart;var e=d.xAxis[0],k=this.reversedExtremes;0===f?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=k?e.min:e.max):(this.grabbedRight=
!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=k?e.max:e.min);d.fixedRange=null};e.prototype.onMouseMove=function(d){var f=this,e=f.chart,k=f.left,n=f.navigatorSize,a=f.range,b=f.dragOffset,t=e.inverted;d.touches&&0===d.touches[0].pageX||(d=e.pointer.normalize(d),e=d.chartX,t&&(k=f.top,e=d.chartY),f.grabbedLeft?(f.hasDragged=!0,f.render(0,0,e-k,f.otherHandlePos)):f.grabbedRight?(f.hasDragged=!0,f.render(0,0,f.otherHandlePos,e-k)):f.grabbedCenter&&(f.hasDragged=!0,e<b?e=b:e>n+b-a&&(e=n+b-
a),f.render(0,0,e-b,e-b+a)),f.hasDragged&&f.scrollbar&&r(f.scrollbar.options.liveRedraw,v.svg&&!K&&!this.chart.isBoosting)&&(d.DOMType=d.type,setTimeout(function(){f.onMouseUp(d)},0)))};e.prototype.onMouseUp=function(d){var f=this.chart,e=this.xAxis,k=this.scrollbar,n=d.DOMEvent||d,a=f.inverted,b=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!k||!k.hasDragged)||"scrollbar"===d.trigger){k=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var t=this.fixedExtreme;
else if(this.zoomedMax===this.otherHandlePos)var c=this.fixedExtreme;this.zoomedMax===this.size&&(c=this.reversedExtremes?k.dataMin:k.dataMax);0===this.zoomedMin&&(t=this.reversedExtremes?k.dataMax:k.dataMin);e=e.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,t,c);I(e.min)&&f.xAxis[0].setExtremes(Math.min(e.min,e.max),Math.max(e.min,e.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:n})}"mousemove"!==d.DOMType&&"touchmove"!==d.DOMType&&(this.grabbedLeft=
this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&N(this.zoomedMin)&&N(this.zoomedMax)&&(f=Math.round(this.zoomedMin),d=Math.round(this.zoomedMax),this.shades&&this.drawMasks(f,d,a,b),this.outline&&this.drawOutline(f,d,a,b),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(f,0,a,b),this.drawHandle(d,1,a,b)))};e.prototype.removeEvents=function(){this.eventsToUnbind&&
(this.eventsToUnbind.forEach(function(d){d()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};e.prototype.removeBaseSeriesEvents=function(){var d=this.baseSeries||[];this.navigatorEnabled&&d[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&d.forEach(function(d){E(d,"updatedData",this.updatedDataHandler)},this),d[0].xAxis&&E(d[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};e.prototype.init=function(d){var f=d.options,e=f.navigator,n=e.enabled,b=f.scrollbar,t=b.enabled;f=n?e.height:
0;var m=t?b.height:0;this.handles=[];this.shades=[];this.chart=d;this.setBaseSeries();this.height=f;this.scrollbarHeight=m;this.scrollbarEnabled=t;this.navigatorEnabled=n;this.navigatorOptions=e;this.scrollbarOptions=b;this.outlineHeight=f+m;this.opposite=r(e.opposite,!(n||!d.inverted));var q=this;n=q.baseSeries;b=d.xAxis.length;t=d.yAxis.length;var l=n&&n[0]&&n[0].xAxis||d.xAxis[0]||{options:{}};d.isDirtyBox=!0;q.navigatorEnabled?(q.xAxis=new a(d,F({breaks:l.options.breaks,ordinal:l.options.ordinal},
e.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:b,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},d.inverted?{offsets:[m,0,-m,0],width:f}:{offsets:[0,-m,0,m],height:f})),q.yAxis=new a(d,F(e.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:t,isInternal:!0,reversed:r(e.yAxis&&e.yAxis.reversed,d.yAxis[0]&&d.yAxis[0].reversed,!1),zoomEnabled:!1},d.inverted?{width:f}:{height:f})),n||e.series.data?
q.updateNavigatorSeries(!1):0===d.series.length&&(q.unbindRedraw=z(d,"beforeRedraw",function(){0<d.series.length&&!q.series&&(q.setBaseSeries(),q.unbindRedraw())})),q.reversedExtremes=d.inverted&&!q.xAxis.reversed||!d.inverted&&q.xAxis.reversed,q.renderElements(),q.addMouseEvents()):(q.xAxis={chart:d,navigatorAxis:{fake:!0},translate:function(f,e){var n=d.xAxis[0],a=n.getExtremes(),b=n.len-2*m,y=k("min",n.options.min,a.dataMin);n=k("max",n.options.max,a.dataMax)-y;return e?f*n/b+y:b*(f-y)/n},toPixels:function(d){return this.translate(d)},
toValue:function(d){return this.translate(d,!0)}},q.xAxis.navigatorAxis.axis=q.xAxis,q.xAxis.navigatorAxis.toFixedRange=g.AdditionsClass.prototype.toFixedRange.bind(q.xAxis.navigatorAxis));d.options.scrollbar.enabled&&(d.scrollbar=q.scrollbar=new c(d.renderer,F(d.options.scrollbar,{margin:q.navigatorEnabled?0:10,vertical:d.inverted}),d),z(q.scrollbar,"changed",function(d){var f=q.size,e=f*this.to;f*=this.from;q.hasDragged=q.scrollbar.hasDragged;q.render(0,0,f,e);this.shouldUpdateExtremes(d.DOMType)&&
setTimeout(function(){q.onMouseUp(d)})}));q.addBaseSeriesEvents();q.addChartEvents()};e.prototype.getUnionExtremes=function(d){var f=this.chart.xAxis[0],e=this.xAxis,n=e.options,a=f.options,b;d&&null===f.dataMin||(b={dataMin:r(n&&n.min,k("min",a.min,f.dataMin,e.dataMin,e.min)),dataMax:r(n&&n.max,k("max",a.max,f.dataMax,e.dataMax,e.max))});return b};e.prototype.setBaseSeries=function(d,e){var f=this.chart,k=this.baseSeries=[];d=d||f.options&&f.options.navigator.baseSeries||(f.series.length?q(f.series,
function(d){return!d.options.isInternal}).index:0);(f.series||[]).forEach(function(e,f){e.options.isInternal||!e.options.showInNavigator&&(f!==d&&e.options.id!==d||!1===e.options.showInNavigator)||k.push(e)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,e)};e.prototype.updateNavigatorSeries=function(d,e){var f=this,k=f.chart,n=f.baseSeries,a,b,c=f.navigatorOptions.series,q,l={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",
yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},x=f.series=(f.series||[]).filter(function(d){var e=d.baseSeries;return 0>n.indexOf(e)?(e&&(E(e,"updatedData",f.updatedDataHandler),delete e.navigatorSeries),d.chart&&d.destroy(),!1):!0});n&&n.length&&n.forEach(function(d){var y=d.navigatorSeries,L=m({color:d.color,visible:d.visible},J(c)?P.navigator.series:c);y&&!1===f.navigatorOptions.adaptToUpdatedData||(l.name="Navigator "+n.length,a=d.options||
{},q=a.navigatorOptions||{},L.dataLabels=t(L.dataLabels),b=F(a,l,L,q),b.pointRange=r(L.pointRange,q.pointRange,P.plotOptions[b.type||"line"].pointRange),L=q.data||L.data,f.hasNavigatorData=f.hasNavigatorData||!!L,b.data=L||a.data&&a.data.slice(0),y&&y.options?y.update(b,e):(d.navigatorSeries=k.initSeries(b),d.navigatorSeries.baseSeries=d,x.push(d.navigatorSeries)))});if(c.data&&(!n||!n.length)||J(c))f.hasNavigatorData=!1,c=t(c),c.forEach(function(d,e){l.name="Navigator "+(x.length+1);b=F(P.navigator.series,
{color:k.series[e]&&!k.series[e].options.isInternal&&k.series[e].color||k.options.colors[e]||k.options.colors[0]},l,d);b.data=d.data;b.data&&(f.hasNavigatorData=!0,x.push(k.initSeries(b)))});d&&this.addBaseSeriesEvents()};e.prototype.addBaseSeriesEvents=function(){var d=this,e=d.baseSeries||[];e[0]&&e[0].xAxis&&e[0].eventsToUnbind.push(z(e[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes));e.forEach(function(e){e.eventsToUnbind.push(z(e,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,
!1)}));e.eventsToUnbind.push(z(e,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)}));!1!==this.navigatorOptions.adaptToUpdatedData&&e.xAxis&&e.eventsToUnbind.push(z(e,"updatedData",this.updatedDataHandler));e.eventsToUnbind.push(z(e,"remove",function(){this.navigatorSeries&&(l(d.series,this.navigatorSeries),I(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)}))},this)};e.prototype.getBaseSeriesMin=function(d){return this.baseSeries.reduce(function(d,
e){return Math.min(d,e.xData?e.xData[0]:d)},d)};e.prototype.modifyNavigatorAxisExtremes=function(){var d=this.xAxis,e;"undefined"!==typeof d.getExtremes&&(!(e=this.getUnionExtremes(!0))||e.dataMin===d.min&&e.dataMax===d.max||(d.min=e.dataMin,d.max=e.dataMax))};e.prototype.modifyBaseAxisExtremes=function(){var d=this.chart.navigator,e=this.getExtremes(),k=e.dataMin,n=e.dataMax;e=e.max-e.min;var a=d.stickToMin,b=d.stickToMax,t=r(this.options.overscroll,0),c=d.series&&d.series[0],q=!!this.setExtremes;
if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(a){var m=k;var l=m+e}b&&(l=n+t,a||(m=Math.max(k,l-e,d.getBaseSeriesMin(c&&c.xData?c.xData[0]:-Number.MAX_VALUE))));q&&(a||b)&&N(m)&&(this.min=this.userMin=m,this.max=this.userMax=l)}d.stickToMin=d.stickToMax=null};e.prototype.updatedDataHandler=function(){var d=this.chart.navigator,e=this.navigatorSeries;d.stickToMax=d.reversedExtremes?0===Math.round(d.zoomedMin):Math.round(d.zoomedMax)>=Math.round(d.size);d.stickToMin=d.shouldStickToMin(this,
d);e&&!d.hasNavigatorData&&(e.options.pointStart=this.xData[0],e.setData(this.options.data,!1,null,!1))};e.prototype.shouldStickToMin=function(d,e){e=e.getBaseSeriesMin(d.xData[0]);var f=d.xAxis;d=f.max;var k=f.min;f=f.options.range;return N(d)&&N(k)?f&&0<d-e?d-e<f&&!this.chart.fixedRange:k<=e:!1};e.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(z(this.chart,"redraw",function(){var d=this.navigator,e=d&&(d.baseSeries&&d.baseSeries[0]&&d.baseSeries[0].xAxis||
this.xAxis[0]);e&&d.render(e.min,e.max)}),z(this.chart,"getMargins",function(){var d=this.navigator,e=d.opposite?"plotTop":"marginBottom";this.inverted&&(e=d.opposite?"marginRight":"plotLeft");this[e]=(this[e]||0)+(d.navigatorEnabled||!this.inverted?d.outlineHeight:0)+d.navigatorOptions.margin}))};e.prototype.destroy=function(){this.removeEvents();this.xAxis&&(l(this.chart.xAxis,this.xAxis),l(this.chart.axes,this.xAxis));this.yAxis&&(l(this.chart.yAxis,this.yAxis),l(this.chart.axes,this.yAxis));(this.series||
[]).forEach(function(d){d.destroy&&d.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(d){this[d]&&this[d].destroy&&this[d].destroy();this[d]=null},this);[this.handles].forEach(function(d){x(d)},this)};return e}();v.Navigator||(v.Navigator=n,g.compose(a),z(p,"beforeShowResetZoom",function(){var e=this.options,d=e.navigator,f=e.rangeSelector;if((d&&d.enabled||f&&f.enabled)&&(!K&&"x"===e.chart.zoomType||
K&&"x"===e.chart.pinchType))return!1}),z(p,"beforeRender",function(){var e=this.options;if(e.navigator.enabled||e.scrollbar.enabled)this.scroller=this.navigator=new n(this)}),z(p,"afterSetChartSize",function(){var e=this.legend,d=this.navigator;if(d){var f=e&&e.options;var k=d.xAxis;var n=d.yAxis;var a=d.scrollbarHeight;this.inverted?(d.left=d.opposite?this.chartWidth-a-d.height:this.spacing[3]+a,d.top=this.plotTop+a):(d.left=r(k.left,this.plotLeft+a),d.top=d.navigatorOptions.top||this.chartHeight-
d.height-a-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(f&&"bottom"===f.verticalAlign&&"proximate"!==f.layout&&f.enabled&&!f.floating?e.legendHeight+r(f.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));k&&n&&(this.inverted?k.options.left=n.options.left=d.left:k.options.top=n.options.top=d.top,k.setAxisSize(),n.setAxisSize())}}),z(p,"update",function(e){var d=e.options.navigator||{},f=e.options.scrollbar||{};this.navigator||this.scroller||!d.enabled&&
!f.enabled||(F(!0,this.options.navigator,d),F(!0,this.options.scrollbar,f),delete e.options.navigator,delete e.options.scrollbar)}),z(p,"afterUpdate",function(e){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new n(this),r(e.redraw,!0)&&this.redraw(e.animation))}),z(p,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),z(b,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&
this.chart.navigator.setBaseSeries(null,!1)}),p.prototype.callbacks.push(function(e){var d=e.navigator;d&&e.xAxis[0]&&(e=e.xAxis[0].getExtremes(),d.render(e.min,e.max))}));v.Navigator=n;return v.Navigator});G(a,"Core/Axis/OrdinalAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,p,w,v,g){function H(a,b){var c=K.Composition.findIndexOf(a,b,!0);return a[c]===b?c:c+(b-a[c])/(a[c+1]-a[c])}var u=g.addEvent,D=g.correctFloat,
c=g.css,b=g.defined,C=g.error,h=g.pick,B=g.timeUnits,K;(function(a){var g=function(){function a(a){this.index={};this.axis=a}a.prototype.beforeSetTickPositions=function(){var a=this.axis,b=a.ordinal,c=[],l,m=!1,q=a.getExtremes(),J=q.min,g=q.max,F,r=a.isXAxis&&!!a.options.breaks;q=a.options.ordinal;var E=Number.MAX_VALUE,t=a.chart.options.chart.ignoreHiddenSeries,k;if(q||r){a.series.forEach(function(d,e){l=[];if(!(t&&!1===d.visible||!1===d.takeOrdinalPosition&&!r)&&(c=c.concat(d.processedXData),n=
c.length,c.sort(function(d,e){return d-e}),E=Math.min(E,h(d.closestPointRange,E)),n)){for(e=0;e<n-1;)c[e]!==c[e+1]&&l.push(c[e+1]),e++;l[0]!==c[0]&&l.unshift(c[0]);c=l}d.isSeriesBoosting&&(k=!0)});k&&(c.length=0);var n=c.length;if(2<n){var e=c[1]-c[0];for(F=n-1;F--&&!m;)c[F+1]-c[F]!==e&&(m=!0);!a.options.keepOrdinalPadding&&(c[0]-J>e||g-c[c.length-1]>e)&&(m=!0)}else a.options.overscroll&&(2===n?E=c[1]-c[0]:1===n?(E=a.options.overscroll,c=[c[0],c[0]+E]):E=b.overscrollPointsRange);m||a.forceOrdinal?
(a.options.overscroll&&(b.overscrollPointsRange=E,c=c.concat(b.getOverscrollPositions())),b.positions=c,e=a.ordinal2lin(Math.max(J,c[0]),!0),F=Math.max(a.ordinal2lin(Math.min(g,c[c.length-1]),!0),1),b.slope=g=(g-J)/(F-e),b.offset=J-e*g):(b.overscrollPointsRange=h(a.closestPointRange,b.overscrollPointsRange),b.positions=a.ordinal.slope=b.offset=void 0)}a.isOrdinal=q&&m;b.groupIntervalFactor=null};a.findIndexOf=function(a,b,c){for(var l=0,m=a.length-1,q;l<m;)q=Math.ceil((l+m)/2),a[q]<=b?l=q:m=q-1;return a[l]===
b?l:c?l:-1};a.prototype.getExtendedPositions=function(){var a=this,b=a.axis,c=b.constructor.prototype,l=b.chart,m=b.series[0].currentDataGrouping,q=a.index,h=m?m.count+m.unitName:"raw",g=b.options.overscroll,F=b.getExtremes(),r;q||(q=a.index={});if(!q[h]){var E={series:[],chart:l,forceOrdinal:!1,getExtremes:function(){return{min:F.dataMin,max:F.dataMax+g}},getGroupPixelWidth:c.getGroupPixelWidth,getTimeTicks:c.getTimeTicks,options:{ordinal:!0},ordinal:{getGroupIntervalFactor:this.getGroupIntervalFactor},
ordinal2lin:c.ordinal2lin,getIndexOfPoint:c.getIndexOfPoint,val2lin:c.val2lin};E.ordinal.axis=E;b.series.forEach(function(b){r={xAxis:E,xData:b.xData.slice(),chart:l,destroyGroupedData:w.noop,getProcessedData:v.prototype.getProcessedData};r.xData=r.xData.concat(a.getOverscrollPositions());r.options={dataGrouping:m?{firstAnchor:"firstPoint",anchor:"middle",lastAnchor:"lastPoint",enabled:!0,forced:!0,approximation:"open",units:[[m.unitName,[m.count]]]}:{enabled:!1}};E.series.push(r);b.processData.apply(r);
r.closestPointRange!==r.basePointRange&&r.currentDataGrouping&&(E.forceOrdinal=!0)});b.ordinal.beforeSetTickPositions.apply({axis:E});q[h]=E.ordinal.positions}return q[h]};a.prototype.getGroupIntervalFactor=function(a,b,c){c=c.processedXData;var l=c.length,m=[];var q=this.groupIntervalFactor;if(!q){for(q=0;q<l-1;q++)m[q]=c[q+1]-c[q];m.sort(function(a,b){return a-b});m=m[Math.floor(l/2)];a=Math.max(a,c[0]);b=Math.min(b,c[l-1]);this.groupIntervalFactor=q=l*m/(b-a)}return q};a.prototype.getIndexOfPoint=
function(b,c){var h=this.axis;b=(b-(this.slope?this.slope*h.transA:0))/(h.translationSlope*(this.slope||h.closestPointRange||this.overscrollPointsRange));return a.findIndexOf(c,this.positions?this.positions[0]:0)+b};a.prototype.getOverscrollPositions=function(){var a=this.axis,c=a.options.overscroll,h=this.overscrollPointsRange,l=[],m=a.dataMax;if(b(h))for(;m<=a.dataMax+c;)m+=h,l.push(m);return l};a.prototype.postProcessTickInterval=function(a){var b=this.axis,c=this.slope;return c?b.options.breaks?
b.closestPointRange||a:a/(c/b.closestPointRange):a};return a}();a.Composition=g;a.compose=function(h,g,z){h.keepProps.push("ordinal");var x=h.prototype;h.prototype.getTimeTicks=function(a,c,q,h,g,F,r){void 0===g&&(g=[]);void 0===F&&(F=0);var m=0,t,k,n={},e=[],d=-Number.MAX_VALUE,f=this.options.tickPixelInterval,y=this.chart.time,l=[];if(!this.options.ordinal&&!this.options.breaks||!g||3>g.length||"undefined"===typeof c)return y.getTimeTicks.apply(y,arguments);var x=g.length;for(t=0;t<x;t++){var M=
t&&g[t-1]>q;g[t]<c&&(m=t);if(t===x-1||g[t+1]-g[t]>5*F||M){if(g[t]>d){for(k=y.getTimeTicks(a,g[m],g[t],h);k.length&&k[0]<=d;)k.shift();k.length&&(d=k[k.length-1]);l.push(e.length);e=e.concat(k)}m=t+1}if(M)break}if(k){k=k.info;if(r&&k.unitRange<=B.hour){t=e.length-1;for(m=1;m<t;m++)if(y.dateFormat("%d",e[m])!==y.dateFormat("%d",e[m-1])){n[e[m]]="day";var R=!0}R&&(n[e[0]]="day");k.higherRanks=n}k.segmentStarts=l;e.info=k}else C(12,!1,this.chart);if(r&&b(f)){m=k=e.length;R=[];y=void 0;for(l=[];m--;)t=
this.translate(e[m]),y&&(l[m]=y-t),R[m]=y=t;l.sort();l=l[Math.floor(l.length/2)];l<.6*f&&(l=null);m=e[k-1]>q?k-1:k;for(y=void 0;m--;)t=R[m],k=Math.abs(y-t),y&&k<.8*f&&(null===l||k<.8*l)?(n[e[m]]&&!n[e[m+1]]?(k=m+1,y=t):k=m,e.splice(k,1)):y=t}return e};x.index2val=function(a){var b=this.ordinal.positions;if(!b)return a;var c=b.length-1;if(0>a)a=b[0];else if(a>c)a=b[c];else{c=Math.floor(a);var l=a-c}return"undefined"!==typeof l&&"undefined"!==typeof b[c]?b[c]+(l?l*(b[c+1]-b[c]):0):a};x.lin2val=function(a){var b=
this.ordinal,c=b.positions;if(!c)return a;var l=(a-(this.old?this.old.min:this.min))*(this.old?this.old.transA:this.transA);a>this.left&&a<this.left+this.len||(b.extendedOrdinalPositions||(b.extendedOrdinalPositions=b.getExtendedPositions()),c=b.extendedOrdinalPositions);if(c&&c.length){a=b.getIndexOfPoint(l,c);b=D(a%1);if(0<=a&&a<c.length)return c[Math.floor(a)]+b*(c[Math.ceil(a)]-c[Math.floor(a)]);b=c.length;l=c[0];c=c[b-1];var h=(c-l)/(b-1);return 0>a?l+h*a:c+h*(a-b)}return a};x.val2lin=function(a,
b){var c=this.ordinal,m=c.slope,l=c.positions,h=c.extendedOrdinalPositions;if(!l)return a;var r=l.length;if(l[0]<=a&&l[r-1]>=a)a=H(l,a);else{h||(h=c.getExtendedPositions&&c.getExtendedPositions(),c.extendedOrdinalPositions=h);if(!h||!h.length)return a;r=h.length;m||(m=(h[r-1]-h[0])/r);l=H(h,l[0]);a>=h[0]&&a<=h[r-1]?a=H(h,a)-l:a<h[0]?(a=h[0]-a,a=-l-a/m):(a-=h[r-1],a=a/m+r-l)}return b?a:m*(a||0)+c.offset};x.ordinal2lin=x.val2lin;u(h,"afterInit",function(){this.ordinal||(this.ordinal=new a.Composition(this))});
u(h,"foundExtremes",function(){this.isXAxis&&b(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&b(this.userMin)&&(this.min+=this.options.overscroll))});u(h,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});u(h,"initialAxisTranslation",
function(){this.ordinal&&(this.ordinal.beforeSetTickPositions(),this.tickInterval=this.ordinal.postProcessTickInterval(this.tickInterval))});u(g,"pan",function(a){var b=this.xAxis[0],q=b.options.overscroll,l=a.originalEvent.chartX,h=this.options.chart.panning,g=!1;if(h&&"y"!==h.type&&b.options.ordinal&&b.series.length){var r=this.mouseDownX,E=b.getExtremes(),t=E.dataMax,k=E.min,n=E.max,e=void 0;e=this.hoverPoints;var d=b.closestPointRange||b.ordinal&&b.ordinal.overscrollPointsRange;r=(r-l)/(b.translationSlope*
(b.ordinal.slope||d));d={ordinal:{positions:b.ordinal.getExtendedPositions()}};var f=void 0,y=void 0,L=b.index2val,x=b.val2lin,M=void 0;d.ordinal.positions?1<Math.abs(r)&&(e&&e.forEach(function(d){d.setState()}),0>r?(y=d,M=b.ordinal.positions?b:d):(y=b.ordinal.positions?b:d,M=d),f=M.ordinal.positions,t>f[f.length-1]&&f.push(t),this.fixedRange=n-k,e=b.navigatorAxis.toFixedRange(null,null,L.apply(y,[x.apply(y,[k,!0])+r]),L.apply(M,[x.apply(M,[n,!0])+r])),e.min>=Math.min(E.dataMin,k)&&e.max<=Math.max(t,
n)+q&&b.setExtremes(e.min,e.max,!0,!1,{trigger:"pan"}),this.mouseDownX=l,c(this.container,{cursor:"move"})):g=!0}else g=!0;g||h&&/y/.test(h.type)?q&&(b.max=b.dataMax+q):a.preventDefault()});u(z,"updatedData",function(){var a=this.xAxis;a&&a.options.ordinal&&delete a.ordinal.index})}})(K||(K={}));K.compose(a,p,v);return K});G(a,"Core/Axis/BrokenAxis.js",[a["Core/Axis/Axis.js"],a["Core/Series/Series.js"],a["Extensions/Stacking.js"],a["Core/Utilities.js"]],function(a,p,w,v){var g=v.addEvent,H=v.find,
u=v.fireEvent,D=v.isArray,c=v.isNumber,b=v.pick,C;(function(h){function B(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)}function C(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)}function v(){var a=this.brokenAxis;if(a&&a.hasBreaks){for(var b=this.tickPositions,c=this.tickPositions.info,l=[],h=0;h<b.length;h++)a.isInAnyBreak(b[h])||l.push(b[h]);this.tickPositions=l;this.tickPositions.info=c}}function z(){this.brokenAxis||(this.brokenAxis=
new l(this))}function O(){var a=this.options.connectNulls,b=this.points,c=this.xAxis,l=this.yAxis;if(this.isDirty)for(var h=b.length;h--;){var r=b[h],g=!(null===r.y&&!1===a)&&(c&&c.brokenAxis&&c.brokenAxis.isInAnyBreak(r.x,!0)||l&&l.brokenAxis&&l.brokenAxis.isInAnyBreak(r.y,!0));r.visible=g?!1:!1!==r.options.visible}}function A(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,b(this.pointArrayMap,["y"]))}function I(a,l){var h=this,q=h.points,m,r,g,t;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var k=
a.brokenAxis;l.forEach(function(n){m=k&&k.breakArray||[];r=a.isXAxis?a.min:b(h.options.threshold,a.min);q.forEach(function(e){t=b(e["stack"+n.toUpperCase()],e[n]);m.forEach(function(d){if(c(r)&&c(t)){g=!1;if(r<d.from&&t>d.to||r>d.from&&t<d.from)g="pointBreak";else if(r<d.from&&t>d.from&&t<d.to||r>d.from&&t>d.to&&t<d.from)g="pointInBreak";g&&u(a,g,{point:e,brk:d})}})})})}}function x(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.points.slice();var c=this.yAxis,l=this.options.gapSize,h=a.length-
1,r;if(l&&0<h)for("value"!==this.options.gapUnit&&(l*=this.basePointRange),b&&b>l&&b>=this.basePointRange&&(l=b),r=void 0;h--;)r&&!1!==r.visible||(r=a[h+1]),b=a[h],!1!==r.visible&&!1!==b.visible&&(r.x-b.x>l&&(r=(b.x+r.x)/2,a.splice(h+1,0,{isNull:!0,x:r}),c.stacking&&this.options.stacking&&(r=c.stacking.stacks[this.stackKey][r]=new w(c,c.options.stackLabels,!1,r,this.stack),r.total=0)),r=b);return this.getGraphPath(a)}h.compose=function(a,b){if(-1===a.keepProps.indexOf("brokenAxis")){a.keepProps.push("brokenAxis");
var c=p.prototype;c.drawBreaks=I;c.gappedPath=x;g(a,"init",z);g(a,"afterInit",B);g(a,"afterSetTickPositions",v);g(a,"afterSetOptions",C);g(b,"afterGeneratePoints",O);g(b,"afterRender",A)}return a};var l=function(){function l(a){this.hasBreaks=!1;this.axis=a}l.isInBreak=function(a,b){var c=a.repeat||Infinity,l=a.from,r=a.to-a.from;b=b>=l?(b-l)%c:c-(l-b)%c;return a.inclusive?b<=r:b<r&&0!==b};l.lin2Val=function(a){var b=this.brokenAxis;b=b&&b.breakArray;if(!b||!c(a))return a;var h;for(h=0;h<b.length;h++){var q=
b[h];if(q.from>=a)break;else q.to<a?a+=q.len:l.isInBreak(q,a)&&(a+=q.len)}return a};l.val2Lin=function(a){var b=this.brokenAxis;b=b&&b.breakArray;if(!b||!c(a))return a;var h=a,q;for(q=0;q<b.length;q++){var r=b[q];if(r.to<=a)h-=r.len;else if(r.from>=a)break;else if(l.isInBreak(r,a)){h-=a-r.from;break}}return h};l.prototype.findBreakAt=function(a,b){return H(b,function(b){return b.from<a&&a<b.to})};l.prototype.isInAnyBreak=function(a,h){var q=this.axis,g=q.options.breaks||[],r=g.length,m;if(r&&c(a)){for(;r--;)if(l.isInBreak(g[r],
a)){var t=!0;m||(m=b(g[r].showPoints,!q.isXAxis))}var k=t&&h?t&&!m:t}return k};l.prototype.setBreaks=function(h,g){var q=this,m=q.axis,r=D(h)&&!!h.length;m.isDirty=q.hasBreaks!==r;q.hasBreaks=r;m.options.breaks=m.userOptions.breaks=h;m.forceRedraw=!0;m.series.forEach(function(a){a.isDirty=!0});r||m.val2lin!==l.val2Lin||(delete m.val2lin,delete m.lin2val);r&&(m.userOptions.ordinal=!1,m.lin2val=l.lin2Val,m.val2lin=l.val2Lin,m.setExtremes=function(b,c,k,n,e){if(q.hasBreaks){for(var d=this.options.breaks||
[],f;f=q.findBreakAt(b,d);)b=f.to;for(;f=q.findBreakAt(c,d);)c=f.from;c<b&&(c=b)}a.prototype.setExtremes.call(this,b,c,k,n,e)},m.setAxisTranslation=function(){a.prototype.setAxisTranslation.call(this);q.unitLength=void 0;if(q.hasBreaks){var r=m.options.breaks||[],t=[],k=[],n=b(m.pointRangePadding,0),e=0,d,f=m.userMin||m.min,y=m.userMax||m.max,h;r.forEach(function(a){d=a.repeat||Infinity;c(f)&&c(y)&&(l.isInBreak(a,f)&&(f+=a.to%d-f%d),l.isInBreak(a,y)&&(y-=y%d-a.from%d))});r.forEach(function(a){M=a.from;
d=a.repeat||Infinity;if(c(f)&&c(y)){for(;M-d>f;)M-=d;for(;M<f;)M+=d;for(h=M;h<y;h+=d)t.push({value:h,move:"in"}),t.push({value:h+a.to-a.from,move:"out",size:a.breakSize})}});t.sort(function(d,a){return d.value===a.value?("in"===d.move?0:1)-("in"===a.move?0:1):d.value-a.value});var g=0;var M=f;t.forEach(function(d){g+="in"===d.move?1:-1;1===g&&"in"===d.move&&(M=d.value);0===g&&c(M)&&(k.push({from:M,to:d.value,len:d.value-M-(d.size||0)}),e+=d.value-M-(d.size||0))});q.breakArray=k;c(f)&&c(y)&&c(m.min)&&
(q.unitLength=y-f-e+n,u(m,"afterBreaks"),m.staticScale?m.transA=m.staticScale:q.unitLength&&(m.transA*=(y-m.min+n)/q.unitLength),n&&(m.minPixelPadding=m.transA*(m.minPointOffset||0)),m.min=f,m.max=y)}});b(g,!0)&&m.chart.redraw()};return l}();h.Additions=l})(C||(C={}));return C});G(a,"masters/modules/broken-axis.src.js",[a["Core/Globals.js"],a["Core/Axis/BrokenAxis.js"]],function(a,p){p.compose(a.Axis,a.Series)});G(a,"Extensions/DataGrouping.js",[a["Core/Axis/Axis.js"],a["Core/Axis/DateTimeAxis.js"],
a["Core/FormatUtilities.js"],a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Series/Series.js"],a["Core/Tooltip.js"],a["Core/DefaultOptions.js"],a["Core/Utilities.js"]],function(a,p,w,v,g,H,u,D,c){var b=w.format,C=H.prototype;w=c.addEvent;var h=c.arrayMax,B=c.arrayMin,K=c.correctFloat,P=c.defined,z=c.error,O=c.extend,A=c.isNumber,I=c.merge,x=c.pick;"";var l=v.approximations={sum:function(a){var b=a.length;if(!b&&a.hasNulls)var c=null;else if(b)for(c=0;b--;)c+=a[b];return c},average:function(a){var b=
a.length;a=l.sum(a);A(a)&&b&&(a=K(a/b));return a},averages:function(){var a=[];[].forEach.call(arguments,function(b){a.push(l.average(b))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?h(a):a.hasNulls?null:void 0},low:function(a){return a.length?B(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,b,c,k){a=l.open(a);b=l.high(b);c=l.low(c);k=l.close(k);
if(A(a)||A(b)||A(c)||A(k))return[a,b,c,k]},range:function(a,b){a=l.low(a);b=l.high(b);if(A(a)||A(b))return[a,b];if(null===a&&null===b)return null}};c=function(a,b,c,k){var n=this,e=n.data,d=n.options&&n.options.data,f=[],t=[],h=[],m=a.length,r=!!b,q=[],g=n.pointArrayMap,x=g&&g.length,u=["x"].concat(g||["y"]),E=this.options.dataGrouping&&this.options.dataGrouping.groupAll,z=0,C=0,B;k="function"===typeof k?k:l[k]?l[k]:l[n.getDGApproximation&&n.getDGApproximation()||"average"];x?g.forEach(function(){q.push([])}):
q.push([]);var D=x||1;for(B=0;B<=m&&!(a[B]>=c[0]);B++);for(B;B<=m;B++){for(;"undefined"!==typeof c[z+1]&&a[B]>=c[z+1]||B===m;){var p=c[z];n.dataGroupInfo={start:E?C:n.cropStart+C,length:q[0].length};var v=k.apply(n,q);n.pointClass&&!P(n.dataGroupInfo.options)&&(n.dataGroupInfo.options=I(n.pointClass.prototype.optionsToObject.call({series:n},n.options.data[n.cropStart+C])),u.forEach(function(a){delete n.dataGroupInfo.options[a]}));"undefined"!==typeof v&&(f.push(p),t.push(v),h.push(n.dataGroupInfo));
C=B;for(p=0;p<D;p++)q[p].length=0,q[p].hasNulls=!1;z+=1;if(B===m)break}if(B===m)break;if(g){p=n.options.dataGrouping&&n.options.dataGrouping.groupAll?B:n.cropStart+B;v=e&&e[p]||n.pointClass.prototype.applyOptions.apply({series:n},[d[p]]);var K=void 0;for(p=0;p<x;p++)K=v[g[p]],A(K)?q[p].push(K):null===K&&(q[p].hasNulls=!0)}else p=r?b[B]:null,A(p)?q[0].push(p):null===p&&(q[0].hasNulls=!0)}return{groupedXData:f,groupedYData:t,groupMap:h}};var m={approximations:l,groupData:c},q=C.generatePoints,J={groupPixelWidth:2,
dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},N={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},
columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},F=v.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];C.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};C.groupData=c;C.applyGrouping=function(){var a=this.chart,b=this.options.dataGrouping,
c=!1!==this.allowDG&&b&&x(b.enabled,a.options.isStock),k=this.visible||!a.options.chart.ignoreHiddenSeries,n,e=this.currentDataGrouping,d=!1;c&&!this.requireSorting&&(this.requireSorting=d=!0);var f=!this.isCartesian||this.isDirty||this.xAxis.isDirty||this.yAxis.isDirty?void 0:!1;d&&(this.requireSorting=!1);if(!f&&c){this.destroyGroupedData();f=b.groupAll?this.xData:this.processedXData;var y=b.groupAll?this.yData:this.processedYData;d=a.plotSizeX;c=this.xAxis;var h=c.options.ordinal,l=this.groupPixelWidth;
if(l&&f&&f.length){this.isDirty=n=!0;this.points=null;var m=c.getExtremes();var q=m.min;m=m.max;h=h&&c.ordinal&&c.ordinal.getGroupIntervalFactor(q,m,this)||1;d=c.getTimeTicks(p.Additions.prototype.normalizeTimeTickInterval(l*(m-q)/d*h,b.units||F),Math.min(q,f[0]),Math.max(m,f[f.length-1]),c.options.startOfWeek,f,this.closestPointRange);l=C.groupData.apply(this,[f,y,d,b.approximation]);f=l.groupedXData;y=l.groupedYData;h=0;b&&b.smoothed&&f.length&&(b.firstAnchor="firstPoint",b.anchor="middle",b.lastAnchor=
"lastPoint",z(32,!1,a,{"dataGrouping.smoothed":"use dataGrouping.anchor"}));a=f;var g=this.options.dataGrouping;q=this.currentDataGrouping&&this.currentDataGrouping.gapSize;if(g&&this.xData&&q&&this.groupMap){var B=a.length-1;var u=g.anchor;var v=x(g.firstAnchor,u);g=x(g.lastAnchor,u);if(u&&"start"!==u){var K=q*{middle:.5,end:1}[u];for(u=a.length-1;u--&&0<u;)a[u]+=K}if(v&&"start"!==v&&this.xData[0]>=a[0]){u=this.groupMap[0].start;K=this.groupMap[0].length;var D=void 0;A(u)&&A(K)&&(D=u+(K-1));a[0]=
{middle:a[0]+.5*q,end:a[0]+q,firstPoint:this.xData[0],lastPoint:D&&this.xData[D]}[v]}g&&"start"!==g&&q&&a[B]>=m-q&&(m=this.groupMap[this.groupMap.length-1].start,a[B]={middle:a[B]+.5*q,end:a[B]+q,firstPoint:m&&this.xData[m],lastPoint:this.xData[this.xData.length-1]}[g])}for(m=1;m<d.length;m++)d.info.segmentStarts&&-1!==d.info.segmentStarts.indexOf(m)||(h=Math.max(d[m]-d[m-1],h));m=d.info;m.gapSize=h;this.closestPointRange=d.info.totalRange;this.groupMap=l.groupMap;if(k){k=f;if(P(k[0])&&A(c.min)&&
A(c.dataMin)&&k[0]<c.min){if(!P(c.options.min)&&c.min<=c.dataMin||c.min===c.dataMin)c.min=Math.min(k[0],c.min);c.dataMin=Math.min(k[0],c.dataMin)}if(P(k[k.length-1])&&A(c.max)&&A(c.dataMax)&&k[k.length-1]>c.max){if(!P(c.options.max)&&A(c.dataMax)&&c.max>=c.dataMax||c.max===c.dataMax)c.max=Math.max(k[k.length-1],c.max);c.dataMax=Math.max(k[k.length-1],c.dataMax)}}b.groupAll&&(b=this.cropData(f,y,c.min,c.max,1),f=b.xData,y=b.yData,this.cropStart=b.start);this.processedXData=f;this.processedYData=y}else this.groupMap=
null;this.hasGroupedData=n;this.currentDataGrouping=m;this.preventGraphAnimation=(e&&e.totalRange)!==(m&&m.totalRange)}};C.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(a,b){a&&(this.groupedData[b]=a.destroy?a.destroy():null)},this),this.groupedData.length=0)};C.generatePoints=function(){q.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};w(a,"postProcessData",function(){var a=this;a.series.forEach(function(b){b.groupPixelWidth=
void 0;b.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();b.groupPixelWidth&&(b.hasProcessed=!0,b.applyGrouping())})});w(g,"update",function(){if(this.dataGroup)return z(24,!1,this.series.chart),!1});w(u,"headerFormatter",function(a){var c=this.chart,h=c.time,k=a.labelConfig,n=k.series,e=n.tooltipOptions,d=n.options.dataGrouping,f=e.xDateFormat,y=n.xAxis,l=e[a.isFooter?"footerFormat":"headerFormat"];if(y&&"datetime"===y.options.type&&d&&A(k.key)){var m=n.currentDataGrouping;d=d.dateTimeLabelFormats||
J.dateTimeLabelFormats;if(m)if(e=d[m.unitName],1===m.count)f=e[0];else{f=e[1];var q=e[2]}else!f&&d&&y.dateTime&&(f=y.dateTime.getXDateFormat(k.x,e.dateTimeLabelFormats));f=h.dateFormat(f,k.key);q&&(f+=h.dateFormat(q,k.key+m.totalRange-1));n.chart.styledMode&&(l=this.styledModeFormat(l));a.text=b(l,{point:O(k.point,{key:f}),series:n},c);a.preventDefault()}});w(H,"destroy",C.destroyGroupedData);w(H,"afterSetOptions",function(a){a=a.options;var b=this.type,c=this.chart.options.plotOptions,k=D.defaultOptions.plotOptions[b].dataGrouping,
n=this.useCommonDataGrouping&&J;if(N[b]||n){k||(k=I(J,N[b]));var e=this.chart.rangeSelector;a.dataGrouping=I(n,k,c.series&&c.series.dataGrouping,c[b].dataGrouping,this.userOptions.dataGrouping,!a.isInternal&&e&&A(e.selected)&&e.buttonOptions[e.selected].dataGrouping)}});w(a,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=!1})});a.prototype.getGroupPixelWidth=function(){var a=this.series,b=a.length,c,k=0,n=!1,e;for(c=b;c--;)(e=a[c].options.dataGrouping)&&(k=Math.max(k,x(e.groupPixelWidth,
J.groupPixelWidth)));for(c=b;c--;)if(e=a[c].options.dataGrouping)if(b=(a[c].processedXData||a[c].data).length,a[c].groupPixelWidth||b>this.chart.plotSizeX/k||b&&e.forced)n=!0;return n?k:0};a.prototype.setDataGrouping=function(b,c){var h;c=x(c,!0);b||(b={forced:!1,units:null});if(this instanceof a)for(h=this.series.length;h--;)this.series[h].update({dataGrouping:b},!1);else this.chart.options.series.forEach(function(a){a.dataGrouping=b},!1);this.ordinal&&(this.ordinal.slope=void 0);c&&this.chart.redraw()};
v.dataGrouping=m;"";return m});G(a,"Series/OHLC/OHLCPoint.js",[a["Core/Series/SeriesRegistry.js"]],function(a){var p=this&&this.__extends||function(){var a=function(p,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var u in g)g.hasOwnProperty(u)&&(a[u]=g[u])};return a(p,g)};return function(p,g){function v(){this.constructor=p}a(p,g);p.prototype=null===g?Object.create(g):(v.prototype=g.prototype,new v)}}();return function(a){function v(){var g=
null!==a&&a.apply(this,arguments)||this;g.close=void 0;g.high=void 0;g.low=void 0;g.open=void 0;g.options=void 0;g.plotClose=void 0;g.plotOpen=void 0;g.series=void 0;return g}p(v,a);v.prototype.getClassName=function(){return a.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")};v.prototype.resolveUpColor=function(){this.open<this.close&&!this.options.color&&this.series.options.upColor&&(this.color=this.series.options.upColor)};v.prototype.resolveColor=
function(){a.prototype.resolveColor.call(this);this.resolveUpColor()};v.prototype.getZone=function(){var g=a.prototype.getZone.call(this);this.resolveUpColor();return g};return v}(a.seriesTypes.column.prototype.pointClass)});G(a,"Series/OHLC/OHLCSeries.js",[a["Series/OHLC/OHLCPoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,w){var v=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=
b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(c,b)};return function(c,b){function g(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(g.prototype=b.prototype,new g)}}(),g=p.seriesTypes.column,H=w.extend,u=w.merge;w=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;b.yData=void 0;return b}v(c,a);c.prototype.drawPoints=function(){var a=this,c=a.chart,h=function(a,b,c){var h=a[0];a=a[1];
"number"===typeof h[2]&&(h[2]=Math.max(c+b,h[2]));"number"===typeof a[2]&&(a[2]=Math.min(c-b,a[2]))};a.points.forEach(function(b){var g=b.graphic,u=!g;if("undefined"!==typeof b.plotY){g||(b.graphic=g=c.renderer.path().add(a.group));c.styledMode||g.attr(a.pointAttribs(b,b.selected&&"select"));var p=g.strokeWidth();var v=p%2/2;var A=Math.round(b.plotX)-v;var C=Math.round(b.shapeArgs.width/2);var x=[["M",A,Math.round(b.yBottom)],["L",A,Math.round(b.plotHigh)]];if(null!==b.open){var l=Math.round(b.plotOpen)+
v;x.push(["M",A,l],["L",A-C,l]);h(x,p/2,l)}null!==b.close&&(l=Math.round(b.plotClose)+v,x.push(["M",A,l],["L",A+C,l]),h(x,p/2,l));g[u?"attr":"animate"]({d:x}).addClass(b.getClassName(),!0)}})};c.prototype.init=function(){a.prototype.init.apply(this,arguments);this.options.stacking=void 0};c.prototype.pointAttribs=function(b,c){c=a.prototype.pointAttribs.call(this,b,c);var h=this.options;delete c.fill;!b.options.color&&h.upColor&&b.open<b.close&&(c.stroke=h.upColor);return c};c.prototype.toYData=function(a){return[a.open,
a.high,a.low,a.close]};c.prototype.translate=function(){var b=this,c=b.yAxis,h=!!b.modifyValue,g=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];a.prototype.translate.apply(b);b.points.forEach(function(a){[a.open,a.high,a.low,a.close,a.low].forEach(function(u,p){null!==u&&(h&&(u=b.modifyValue(u)),a[g[p]]=c.toPixels(u,!0))});a.tooltipPos[1]=a.plotHigh+c.pos-b.chart.plotTop})};c.defaultOptions=u(g.defaultOptions,{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0});return c}(g);H(w.prototype,{animate:null,directTouch:!1,pointArrayMap:["open","high","low","close"],pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointValKey:"close"});w.prototype.pointClass=a;p.registerSeriesType("ohlc",w);"";return w});G(a,"Series/Candlestick/CandlestickSeries.js",[a["Core/DefaultOptions.js"],a["Core/Color/Palette.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,w,v){var g=
this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function h(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(h.prototype=c.prototype,new h)}}(),H=a.defaultOptions;a=w.seriesTypes;var u=a.column,D=a.ohlc,c=v.merge;v=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=
void 0;b.options=void 0;b.points=void 0;return b}g(b,a);b.prototype.pointAttribs=function(a,b){var c=u.prototype.pointAttribs.call(this,a,b),h=this.options,g=a.open<a.close,p=h.lineColor||this.color,v=a.color||this.color;c["stroke-width"]=h.lineWidth;c.fill=a.options.color||(g?h.upColor||v:v);c.stroke=a.options.lineColor||(g?h.upLineColor||p:p);b&&(a=h.states[b],c.fill=a.color||c.fill,c.stroke=a.lineColor||c.stroke,c["stroke-width"]=a.lineWidth||c["stroke-width"]);return c};b.prototype.drawPoints=
function(){var a=this,b=a.chart,c=a.yAxis.reversed;a.points.forEach(function(h){var g=h.graphic,u=!g;if("undefined"!==typeof h.plotY){g||(h.graphic=g=b.renderer.path().add(a.group));a.chart.styledMode||g.attr(a.pointAttribs(h,h.selected&&"select")).shadow(a.options.shadow);var p=g.strokeWidth()%2/2;var v=Math.round(h.plotX)-p;var x=h.plotOpen;var l=h.plotClose;var m=Math.min(x,l);x=Math.max(x,l);var q=Math.round(h.shapeArgs.width/2);l=c?x!==h.yBottom:Math.round(m)!==Math.round(h.plotHigh);var D=c?
Math.round(m)!==Math.round(h.plotHigh):x!==h.yBottom;m=Math.round(m)+p;x=Math.round(x)+p;p=[];p.push(["M",v-q,x],["L",v-q,m],["L",v+q,m],["L",v+q,x],["Z"],["M",v,m],["L",v,l?Math.round(c?h.yBottom:h.plotHigh):m],["M",v,x],["L",v,D?Math.round(c?h.plotHigh:h.yBottom):x]);g[u?"attr":"animate"]({d:p}).addClass(h.getClassName(),!0)}})};b.defaultOptions=c(D.defaultOptions,H.plotOptions,{states:{hover:{lineWidth:2}},tooltip:H.plotOptions.ohlc.tooltip,threshold:null,lineColor:p.neutralColor100,lineWidth:1,
upColor:p.backgroundColor,stickyTracking:!0});return b}(D);w.registerSeriesType("candlestick",v);"";return v});G(a,"Series/Flags/FlagsPoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p){var w=this&&this.__extends||function(){var a=function(g,p){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(g,p)};return function(g,p){function u(){this.constructor=g}a(g,p);
g.prototype=null===p?Object.create(p):(u.prototype=p.prototype,new u)}}(),v=p.isNumber;return function(a){function g(){var g=null!==a&&a.apply(this,arguments)||this;g.options=void 0;g.series=void 0;return g}w(g,a);g.prototype.isValid=function(){return v(this.y)||"undefined"===typeof this.y};g.prototype.hasNewShapeType=function(){var a=this.options.shape||this.series.options.shape;return this.graphic&&a&&a!==this.graphic.symbolKey};return g}(a.seriesTypes.column.prototype.pointClass)});G(a,"Mixins/OnSeries.js",
[a["Series/Column/ColumnSeries.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,p,w){var v=a.prototype,g=p.prototype,H=w.defined,u=w.stableSort;return{getPlotBox:function(){return g.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){v.translate.apply(this);var a=this,c=a.options,b=a.chart,g=a.points,h=g.length-1,p,w=c.onSeries;w=w&&b.get(w);c=c.onKey||"y";var O=w&&w.options.step,z=w&&w.points,G=z&&z.length,A=b.inverted,I=a.xAxis,
x=a.yAxis,l=0,m;if(w&&w.visible&&G){l=(w.pointXOffset||0)+(w.barW||0)/2;b=w.currentDataGrouping;var q=z[G-1].x+(b?b.totalRange:0);u(g,function(a,b){return a.x-b.x});for(c="plot"+c[0].toUpperCase()+c.substr(1);G--&&g[h];){var J=z[G];b=g[h];b.y=J.y;if(J.x<=b.x&&"undefined"!==typeof J[c]){if(b.x<=q&&(b.plotY=J[c],J.x<b.x&&!O&&(m=z[G+1])&&"undefined"!==typeof m[c])){var N=(b.x-J.x)/(m.x-J.x);b.plotY+=N*(m[c]-J[c]);b.y+=N*(m.y-J.y)}h--;G++;if(0>h)break}}}g.forEach(function(b,c){b.plotX+=l;if("undefined"===
typeof b.plotY||A)0<=b.plotX&&b.plotX<=I.len?A?(b.plotY=I.translate(b.x,0,1,0,1),b.plotX=H(b.y)?x.translate(b.y,0,0,0,1):0):b.plotY=(I.opposite?0:a.yAxis.len)+I.offset:b.shapeArgs={};if((p=g[c-1])&&p.plotX===b.plotX){"undefined"===typeof p.stackIndex&&(p.stackIndex=0);var h=p.stackIndex+1}b.stackIndex=h});this.onSeries=w}}});G(a,"Series/Flags/FlagsSymbols.js",[a["Core/Renderer/RendererRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"]],function(a,p){function w(a){v[a+"pin"]=function(g,p,w,c,b){var u=
b&&b.anchorX;b=b&&b.anchorY;"circle"===a&&c>w&&(g-=Math.round((c-w)/2),w=c);var h=v[a](g,p,w,c);if(u&&b){var B=u;"circle"===a?B=g+w/2:(g=h[0],w=h[1],"M"===g[0]&&"L"===w[0]&&(B=(g[1]+w[1])/2));h.push(["M",B,p>b?p:p+c],["L",u,b]);h=h.concat(v.circle(u-1,b-1,2,2))}return h}}var v=p.prototype.symbols;v.flag=function(a,p,u,w,c){var b=c&&c.anchorX||a;c=c&&c.anchorY||p;var g=v.circle(b-1,c-1,2,2);g.push(["M",b,c],["L",a,p+w],["L",a,p],["L",a+u,p],["L",a+u,p+w],["L",a,p+w],["Z"]);return g};w("circle");w("square");
a=a.getRendererType();a!==p&&(a.prototype.symbols.circlepin=v.circlepin,a.prototype.symbols.flag=v.flag,a.prototype.symbols.squarepin=v.squarepin);return v});G(a,"Series/Flags/FlagsSeries.js",[a["Series/Flags/FlagsPoint.js"],a["Core/Globals.js"],a["Mixins/OnSeries.js"],a["Core/Color/Palette.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Utilities.js"]],function(a,p,w,v,g,H,u){var D=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function h(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(h.prototype=c.prototype,new h)}}(),c=p.noop,b=g.series,C=g.seriesTypes.column,h=u.addEvent,B=u.defined,K=u.extend,G=u.merge,z=u.objectEach,O=u.wrap;u=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;
return b}D(c,a);c.prototype.animate=function(a){a&&this.setClip()};c.prototype.drawPoints=function(){var a=this.points,b=this.chart,c=b.renderer,h=b.inverted,g=this.options,u=g.y,v,r=this.yAxis,w={},t=[];for(v=a.length;v--;){var k=a[v];var n=(h?k.plotY:k.plotX)>this.xAxis.len;var e=k.plotX;var d=k.stackIndex;var f=k.options.shape||g.shape;var y=k.plotY;"undefined"!==typeof y&&(y=k.plotY+u-("undefined"!==typeof d&&d*g.stackDistance));k.anchorX=d?void 0:k.plotX;var L=d?void 0:k.plotY;var S="flag"!==
f;d=k.graphic;"undefined"!==typeof y&&0<=e&&!n?(d&&k.hasNewShapeType()&&(d=d.destroy()),d||(d=k.graphic=c.label("",null,null,f,null,null,g.useHTML).addClass("highcharts-point").add(this.markerGroup),k.graphic.div&&(k.graphic.div.point=k),d.isNew=!0),d.attr({align:S?"center":"left",width:g.width,height:g.height,"text-align":g.textAlign}),b.styledMode||d.attr(this.pointAttribs(k)).css(G(g.style,k.style)).shadow(g.shadow),0<e&&(e-=d.strokeWidth()%2),f={y:y,anchorY:L},g.allowOverlapX&&(f.x=e,f.anchorX=
k.anchorX),d.attr({text:k.options.title||g.title||"A"})[d.isNew?"attr":"animate"](f),g.allowOverlapX||(w[k.plotX]?w[k.plotX].size=Math.max(w[k.plotX].size,d.width):w[k.plotX]={align:S?.5:0,size:d.width,target:e,anchorX:e}),k.tooltipPos=[e,y+r.pos-b.plotTop]):d&&(k.graphic=d.destroy())}g.allowOverlapX||(z(w,function(a){a.plotX=a.anchorX;t.push(a)}),p.distribute(t,h?r.len:this.xAxis.len,100),a.forEach(function(a){var b=a.graphic&&w[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos+b.align*
b.size,anchorX:a.anchorX}),B(b.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));g.useHTML&&O(this.markerGroup,"on",function(a){return H.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})};c.prototype.drawTracker=function(){var b=this.points;a.prototype.drawTracker.call(this);b.forEach(function(a){var c=a.graphic;c&&(a.unbindMouseOver&&a.unbindMouseOver(),a.unbindMouseOver=h(c.element,"mouseover",function(){0<a.stackIndex&&
!a.raised&&(a._y=c.y,c.attr({y:a._y-8}),a.raised=!0);b.forEach(function(b){b!==a&&b.raised&&b.graphic&&(b.graphic.attr({y:b._y}),b.raised=!1)})}))})};c.prototype.pointAttribs=function(a,b){var c=this.options,h=a&&a.color||this.color,g=c.lineColor,l=a&&a.lineWidth;a=a&&a.fillColor||c.fillColor;b&&(a=c.states[b].fillColor,g=c.states[b].lineColor,l=c.states[b].lineWidth);return{fill:a||h,stroke:g||h,"stroke-width":l||c.lineWidth||0}};c.prototype.setClip=function(){b.prototype.setClip.apply(this,arguments);
!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup&&this.markerGroup.clip(this.chart.sharedClips[this.sharedClipKey])};c.defaultOptions=G(C.defaultOptions,{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}"},threshold:null,y:-30,fillColor:v.backgroundColor,lineWidth:1,states:{hover:{lineColor:v.neutralColor100,fillColor:v.highlightColor20}},style:{fontSize:"11px",fontWeight:"bold"}});return c}(C);K(u.prototype,{allowDG:!1,buildKDTree:c,
forceCrop:!0,getPlotBox:w.getPlotBox,init:b.prototype.init,invertGroups:c,invertible:!1,noSharedTooltip:!0,pointClass:a,sorted:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],translate:w.translate});g.registerSeriesType("flags",u);"";"";return u});G(a,"Extensions/RangeSelector.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/DefaultOptions.js"],a["Core/Color/Palette.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Utilities.js"]],function(a,p,w,v,g,H,u){function D(a){if(-1!==
a.indexOf("%L"))return"text";var b="aAdewbBmoyY".split("").some(function(b){return-1!==a.indexOf("%"+b)}),c="HkIlMS".split("").some(function(b){return-1!==a.indexOf("%"+b)});return b&&c?"datetime-local":b?"date":c?"time":"text"}var c=v.defaultOptions,b=u.addEvent,C=u.createElement,h=u.css,B=u.defined,K=u.destroyObjectProperties,G=u.discardElement,z=u.extend,O=u.find,A=u.fireEvent,I=u.isNumber,x=u.merge,l=u.objectEach,m=u.pad,q=u.pick,J=u.pInt,N=u.splat;z(c,{rangeSelector:{allButtonsEnabled:!1,buttons:void 0,
buttonSpacing:5,dropdown:"responsive",enabled:void 0,verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputBoxBorderColor:"none",inputBoxHeight:17,inputBoxWidth:void 0,inputDateFormat:"%b %e, %Y",inputDateParser:void 0,inputEditDateFormat:"%Y-%m-%d",inputEnabled:!0,inputPosition:{align:"right",x:0,y:0},inputSpacing:5,selected:void 0,buttonPosition:{align:"left",x:0,y:0},inputStyle:{color:g.highlightColor80,cursor:"pointer"},labelStyle:{color:g.neutralColor60}}});
z(c.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"",rangeSelectorTo:"\u2192"});var F=function(){function t(a){this.buttons=void 0;this.buttonOptions=t.prototype.defaultButtons;this.initialButtonGroupWidth=0;this.options=void 0;this.chart=a;this.init(a)}t.prototype.clickButton=function(c,n){var e=this.chart,d=this.buttonOptions[c],f=e.xAxis[0],k=e.scroller&&e.scroller.getUnionExtremes()||f||{},h=k.dataMin,g=k.dataMax,l=f&&Math.round(Math.min(f.max,q(g,f.max))),m=d.type;k=d._range;var t,p=d.dataGrouping;
if(null!==h&&null!==g){e.fixedRange=k;this.setSelected(c);p&&(this.forcedDataGrouping=!0,a.prototype.setDataGrouping.call(f||{chart:this.chart},p,!1),this.frozenStates=d.preserveDataGrouping);if("month"===m||"year"===m)if(f){m={range:d,max:l,chart:e,dataMin:h,dataMax:g};var r=f.minFromRange.call(m);I(m.newMax)&&(l=m.newMax)}else k=d;else if(k)r=Math.max(l-k,h),l=Math.min(r+k,g);else if("ytd"===m)if(f)"undefined"===typeof g&&(h=Number.MAX_VALUE,g=Number.MIN_VALUE,e.series.forEach(function(a){a=a.xData;
h=Math.min(a[0],h);g=Math.max(a[a.length-1],g)}),n=!1),l=this.getYTDExtremes(g,h,e.time.useUTC),r=t=l.min,l=l.max;else{this.deferredYTDClick=c;return}else"all"===m&&f&&(e.navigator&&e.navigator.baseSeries[0]&&(e.navigator.baseSeries[0].xAxis.options.range=void 0),r=h,l=g);B(r)&&(r+=d._offsetMin);B(l)&&(l+=d._offsetMax);this.dropdown&&(this.dropdown.selectedIndex=c+1);if(f)f.setExtremes(r,l,q(n,!0),void 0,{trigger:"rangeSelectorButton",rangeSelectorButton:d});else{var u=N(e.options.xAxis)[0];var v=
u.range;u.range=k;var w=u.min;u.min=t;b(e,"load",function(){u.range=v;u.min=w})}A(this,"afterBtnClick")}};t.prototype.setSelected=function(a){this.selected=this.options.selected=a};t.prototype.init=function(a){var c=this,e=a.options.rangeSelector,d=e.buttons||c.defaultButtons.slice(),f=e.selected,k=function(){var a=c.minInput,b=c.maxInput;a&&a.blur&&A(a,"blur");b&&b.blur&&A(b,"blur")};c.chart=a;c.options=e;c.buttons=[];c.buttonOptions=d;this.eventsToUnbind=[];this.eventsToUnbind.push(b(a.container,
"mousedown",k));this.eventsToUnbind.push(b(a,"resize",k));d.forEach(c.computeButtonRange);"undefined"!==typeof f&&d[f]&&this.clickButton(f,!1);this.eventsToUnbind.push(b(a,"load",function(){a.xAxis&&a.xAxis[0]&&b(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&c.forcedDataGrouping&&!c.frozenStates&&this.setDataGrouping(!1,!1)})}))};t.prototype.updateButtonStates=function(){var a=this,b=this.chart,c=this.dropdown,
d=b.xAxis[0],f=Math.round(d.max-d.min),h=!d.hasVisibleSeries,g=b.scroller&&b.scroller.getUnionExtremes()||d,l=g.dataMin,m=g.dataMax;b=a.getYTDExtremes(m,l,b.time.useUTC);var t=b.min,q=b.max,p=a.selected,r=I(p),u=a.options.allButtonsEnabled,v=a.buttons;a.buttonOptions.forEach(function(b,e){var k=b._range,n=b.type,g=b.count||1,y=v[e],L=0,w=b._offsetMax-b._offsetMin;b=e===p;var x=k>m-l,M=k<d.minRange,z=!1,T=!1;k=k===f;("month"===n||"year"===n)&&f+36E5>=864E5*{month:28,year:365}[n]*g-w&&f-36E5<=864E5*
{month:31,year:366}[n]*g+w?k=!0:"ytd"===n?(k=q-t+w===f,z=!b):"all"===n&&(k=d.max-d.min>=m-l,T=!b&&r&&k);n=!u&&(x||M||T||h);g=b&&k||k&&!r&&!z||b&&a.frozenStates;n?L=3:g&&(r=!0,L=2);y.state!==L&&(y.setState(L),c&&(c.options[e+1].disabled=n,2===L&&(c.selectedIndex=e+1)),0===L&&p===e&&a.setSelected())})};t.prototype.computeButtonRange=function(a){var b=a.type,c=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[b])a._range=d[b]*c;else if("month"===b||"year"===b)a._range=
864E5*{month:30,year:365}[b]*c;a._offsetMin=q(a.offsetMin,0);a._offsetMax=q(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin};t.prototype.getInputValue=function(a){a="min"===a?this.minInput:this.maxInput;var b=this.chart.options.rangeSelector,c=this.chart.time;return a?("text"===a.type&&b.inputDateParser||this.defaultInputDateParser)(a.value,c.useUTC,c):0};t.prototype.setInputValue=function(a,b){var c=this.options,d=this.chart.time,f="min"===a?this.minInput:this.maxInput;a="min"===a?this.minDateBox:
this.maxDateBox;if(f){var n=f.getAttribute("data-hc-time");n=B(n)?Number(n):void 0;B(b)&&(B(n)&&f.setAttribute("data-hc-time-previous",n),f.setAttribute("data-hc-time",b),n=b);f.value=d.dateFormat(this.inputTypeFormats[f.type]||c.inputEditDateFormat,n);a&&a.attr({text:d.dateFormat(c.inputDateFormat,n)})}};t.prototype.setInputExtremes=function(a,b,c){if(a="min"===a?this.minInput:this.maxInput){var d=this.inputTypeFormats[a.type],e=this.chart.time;d&&(b=e.dateFormat(d,b),a.min!==b&&(a.min=b),c=e.dateFormat(d,
c),a.max!==c&&(a.max=c))}};t.prototype.showInput=function(a){var b="min"===a?this.minDateBox:this.maxDateBox;if((a="min"===a?this.minInput:this.maxInput)&&b&&this.inputGroup){var c="text"===a.type,d=this.inputGroup,f=d.translateX;d=d.translateY;var k=this.options.inputBoxWidth;h(a,{width:c?b.width+(k?-2:20)+"px":"auto",height:c?b.height-2+"px":"auto",border:"2px solid silver"});c&&k?h(a,{left:f+b.x+"px",top:d+"px"}):h(a,{left:Math.min(Math.round(b.x+f-(a.offsetWidth-b.width)/2),this.chart.chartWidth-
a.offsetWidth)+"px",top:d-(a.offsetHeight-b.height)/2+"px"})}};t.prototype.hideInput=function(a){(a="min"===a?this.minInput:this.maxInput)&&h(a,{top:"-9999em",border:0,width:"1px",height:"1px"})};t.prototype.defaultInputDateParser=function(a,b,c){var d=a.split("/").join("-").split(" ").join("T");-1===d.indexOf("T")&&(d+="T00:00");if(b)d+="Z";else{var e;if(e=w.isSafari)e=d,e=!(6<e.length&&(e.lastIndexOf("-")===e.length-6||e.lastIndexOf("+")===e.length-6));e&&(e=(new Date(d)).getTimezoneOffset()/60,
d+=0>=e?"+"+m(-e)+":00":"-"+m(e)+":00")}d=Date.parse(d);I(d)||(a=a.split("-"),d=Date.UTC(J(a[0]),J(a[1])-1,J(a[2])));c&&b&&I(d)&&(d+=c.getTimezoneOffset(d));return d};t.prototype.drawInput=function(a){function b(){var b=k.getInputValue(a),d=e.xAxis[0],c=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:d,f=c.dataMin;c=c.dataMax;var n=k.maxInput,g=k.minInput;b!==Number(r.getAttribute("data-hc-time-previous"))&&I(b)&&(r.setAttribute("data-hc-time-previous",b),q&&n&&I(f)?b>Number(n.getAttribute("data-hc-time"))?
b=void 0:b<f&&(b=f):g&&I(c)&&(b<Number(g.getAttribute("data-hc-time"))?b=void 0:b>c&&(b=c)),"undefined"!==typeof b&&d.setExtremes(q?b:d.min,q?d.max:b,void 0,void 0,{trigger:"rangeSelectorInput"}))}var e=this.chart,d=this.div,f=this.inputGroup,k=this,l=e.renderer.style||{},m=e.renderer,t=e.options.rangeSelector,q="min"===a,p=c.lang[q?"rangeSelectorFrom":"rangeSelectorTo"]||"";p=m.label(p,0).addClass("highcharts-range-label").attr({padding:p?2:0,height:p?t.inputBoxHeight:0}).add(f);m=m.label("",0).addClass("highcharts-range-input").attr({padding:2,
width:t.inputBoxWidth,height:t.inputBoxHeight,"text-align":"center"}).on("click",function(){k.showInput(a);k[a+"Input"].focus()});e.styledMode||m.attr({stroke:t.inputBoxBorderColor,"stroke-width":1});m.add(f);var r=C("input",{name:a,className:"highcharts-range-selector"},void 0,d);r.setAttribute("type",D(t.inputDateFormat||"%b %e, %Y"));e.styledMode||(p.css(x(l,t.labelStyle)),m.css(x({color:g.neutralColor80},l,t.inputStyle)),h(r,z({position:"absolute",border:0,boxShadow:"0 0 15px rgba(0,0,0,0.3)",
width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:l.fontSize,fontFamily:l.fontFamily,top:"-9999em"},t.inputStyle)));r.onfocus=function(){k.showInput(a)};r.onblur=function(){r===w.doc.activeElement&&b();k.hideInput(a);k.setInputValue(a);r.blur()};var u=!1;r.onchange=function(){u||(b(),k.hideInput(a),r.blur())};r.onkeypress=function(a){13===a.keyCode&&b()};r.onkeydown=function(a){u=!0;38!==a.keyCode&&40!==a.keyCode||b()};r.onkeyup=function(){u=!1};return{dateBox:m,input:r,label:p}};t.prototype.getPosition=
function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};t.prototype.getYTDExtremes=function(a,b,c){var d=this.chart.time,e=new d.Date(a),n=d.get("FullYear",e);c=c?d.Date.UTC(n,0,1):+new d.Date(n,0,1);b=Math.max(b,c);e=e.getTime();return{max:Math.min(a||e,e),min:b}};t.prototype.render=function(a,b){var c=this.chart,d=c.renderer,f=c.container,n=c.options,k=n.rangeSelector,g=q(n.chart.style&&
n.chart.style.zIndex,0)+1;n=k.inputEnabled;if(!1!==k.enabled){this.rendered||(this.group=d.g("range-selector-group").attr({zIndex:7}).add(),this.div=C("div",void 0,{position:"relative",height:0,zIndex:g}),this.buttonOptions.length&&this.renderButtons(),f.parentNode&&f.parentNode.insertBefore(this.div,f),n&&(this.inputGroup=d.g("input-group").add(this.group),d=this.drawInput("min"),this.minDateBox=d.dateBox,this.minLabel=d.label,this.minInput=d.input,d=this.drawInput("max"),this.maxDateBox=d.dateBox,
this.maxLabel=d.label,this.maxInput=d.input));if(n&&(this.setInputValue("min",a),this.setInputValue("max",b),a=c.scroller&&c.scroller.getUnionExtremes()||c.xAxis[0]||{},B(a.dataMin)&&B(a.dataMax)&&(c=c.xAxis[0].minRange||0,this.setInputExtremes("min",a.dataMin,Math.min(a.dataMax,this.getInputValue("max"))-c),this.setInputExtremes("max",Math.max(a.dataMin,this.getInputValue("min"))+c,a.dataMax)),this.inputGroup)){var h=0;[this.minLabel,this.minDateBox,this.maxLabel,this.maxDateBox].forEach(function(a){if(a){var b=
a.getBBox().width;b&&(a.attr({x:h}),h+=b+k.inputSpacing)}})}this.alignElements();this.rendered=!0}};t.prototype.renderButtons=function(){var a=this,n=this.buttons,e=this.options,d=c.lang,f=this.chart.renderer,g=x(e.buttonTheme),h=g&&g.states,l=g.width||28;delete g.width;delete g.states;this.buttonGroup=f.g("range-selector-buttons").add(this.group);var m=this.dropdown=C("select",void 0,{position:"absolute",width:"1px",height:"1px",padding:0,border:0,top:"-9999em",cursor:"pointer",opacity:.0001},this.div);
b(m,"touchstart",function(){m.style.fontSize="16px"});[[w.isMS?"mouseover":"mouseenter"],[w.isMS?"mouseout":"mouseleave"],["change","click"]].forEach(function(d){var c=d[0],e=d[1];b(m,c,function(){var b=n[a.currentButtonIndex()];b&&A(b.element,e||c)})});this.zoomText=f.label(d&&d.rangeSelectorZoom||"",0).attr({padding:e.buttonTheme.padding,height:e.buttonTheme.height,paddingLeft:0,paddingRight:0}).add(this.buttonGroup);this.chart.styledMode||(this.zoomText.css(e.labelStyle),g["stroke-width"]=q(g["stroke-width"],
0));C("option",{textContent:this.zoomText.textStr,disabled:!0},void 0,m);this.buttonOptions.forEach(function(b,d){C("option",{textContent:b.title||b.text},void 0,m);n[d]=f.button(b.text,0,0,function(c){var e=b.events&&b.events.click,f;e&&(f=e.call(b,c));!1!==f&&a.clickButton(d);a.isActive=!0},g,h&&h.hover,h&&h.select,h&&h.disabled).attr({"text-align":"center",width:l}).add(a.buttonGroup);b.title&&n[d].attr("title",b.title)})};t.prototype.alignElements=function(){var a=this,b=this.buttonGroup,c=this.buttons,
d=this.chart,f=this.group,g=this.inputGroup,h=this.options,l=this.zoomText,m=d.options,t=m.exporting&&!1!==m.exporting.enabled&&m.navigation&&m.navigation.buttonOptions;m=h.buttonPosition;var p=h.inputPosition,r=h.verticalAlign,u=function(b,c){return t&&a.titleCollision(d)&&"top"===r&&"right"===c.align&&c.y-b.getBBox().height-12<(t.y||0)+(t.height||0)+d.spacing[0]?-40:0},v=d.plotLeft;if(f&&m&&p){var w=m.x-d.spacing[3];if(b){this.positionButtons();if(!this.initialButtonGroupWidth){var x=0;l&&(x+=l.getBBox().width+
5);c.forEach(function(a,b){x+=a.width;b!==c.length-1&&(x+=h.buttonSpacing)});this.initialButtonGroupWidth=x}v-=d.spacing[3];this.updateButtonStates();l=u(b,m);this.alignButtonGroup(l);f.placed=b.placed=d.hasLoaded}b=0;g&&(b=u(g,p),"left"===p.align?w=v:"right"===p.align&&(w=-Math.max(d.axisOffset[1],-b)),g.align({y:p.y,width:g.getBBox().width,align:p.align,x:p.x+w-2},!0,d.spacingBox),g.placed=d.hasLoaded);this.handleCollision(b);f.align({verticalAlign:r},!0,d.spacingBox);g=f.alignAttr.translateY;b=
f.getBBox().height+20;u=0;"bottom"===r&&(u=(u=d.legend&&d.legend.options)&&"bottom"===u.verticalAlign&&u.enabled&&!u.floating?d.legend.legendHeight+q(u.margin,10):0,b=b+u-20,u=g-b-(h.floating?0:h.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===r)h.floating&&(u=0),d.titleOffset&&d.titleOffset[0]&&(u=d.titleOffset[0]),u+=d.margin[0]-d.spacing[0]||0;else if("middle"===r)if(p.y===m.y)u=g;else if(p.y||m.y)u=0>p.y||0>m.y?u-Math.min(p.y,m.y):g-b;f.translate(h.x,h.y+Math.floor(u));m=this.minInput;p=
this.maxInput;g=this.dropdown;h.inputEnabled&&m&&p&&(m.style.marginTop=f.translateY+"px",p.style.marginTop=f.translateY+"px");g&&(g.style.marginTop=f.translateY+"px")}};t.prototype.alignButtonGroup=function(a,b){var c=this.chart,d=this.buttonGroup,f=this.options.buttonPosition,n=c.plotLeft-c.spacing[3],k=f.x-c.spacing[3];"right"===f.align?k+=a-n:"center"===f.align&&(k-=n/2);d&&d.align({y:f.y,width:q(b,this.initialButtonGroupWidth),align:f.align,x:k},!0,c.spacingBox)};t.prototype.positionButtons=function(){var a=
this.buttons,b=this.chart,c=this.options,d=this.zoomText,f=b.hasLoaded?"animate":"attr",g=c.buttonPosition,h=b.plotLeft,m=h;d&&"hidden"!==d.visibility&&(d[f]({x:q(h+g.x,h)}),m+=g.x+d.getBBox().width+5);this.buttonOptions.forEach(function(b,d){if("hidden"!==a[d].visibility)a[d][f]({x:m}),m+=a[d].width+c.buttonSpacing;else a[d][f]({x:h})})};t.prototype.handleCollision=function(a){var b=this,c=this.chart,d=this.buttonGroup,f=this.inputGroup,k=this.options,g=k.buttonPosition,h=k.dropdown,m=k.inputPosition;
k=function(){var a=0;b.buttons.forEach(function(b){b=b.getBBox();b.width>a&&(a=b.width)});return a};var l=function(b){if(f&&d){var c=f.alignAttr.translateX+f.alignOptions.x-a+f.getBBox().x+2,e=f.alignOptions.width,n=d.alignAttr.translateX+d.getBBox().x;return n+b>c&&c+e>n&&g.y<m.y+f.getBBox().height}return!1},t=function(){f&&d&&f.attr({translateX:f.alignAttr.translateX+(c.axisOffset[1]>=-a?0:-a),translateY:f.alignAttr.translateY+d.getBBox().height+10})};if(d){if("always"===h){this.collapseButtons(a);
l(k())&&t();return}"never"===h&&this.expandButtons()}f&&d?m.align===g.align||l(this.initialButtonGroupWidth+20)?"responsive"===h?(this.collapseButtons(a),l(k())&&t()):t():"responsive"===h&&this.expandButtons():d&&"responsive"===h&&(this.initialButtonGroupWidth>c.plotWidth?this.collapseButtons(a):this.expandButtons())};t.prototype.collapseButtons=function(a){var b=this.buttons,c=this.buttonOptions,d=this.chart,f=this.dropdown,k=this.options,g=this.zoomText,h=d.userOptions.rangeSelector&&d.userOptions.rangeSelector.buttonTheme||
{},m=function(a){return{text:a?a+" \u25be":"\u25be",width:"auto",paddingLeft:q(k.buttonTheme.paddingLeft,h.padding,8),paddingRight:q(k.buttonTheme.paddingRight,h.padding,8)}};g&&g.hide();var l=!1;c.forEach(function(a,c){c=b[c];2!==c.state?c.hide():(c.show(),c.attr(m(a.text)),l=!0)});l||(f&&(f.selectedIndex=0),b[0].show(),b[0].attr(m(this.zoomText&&this.zoomText.textStr)));c=k.buttonPosition.align;this.positionButtons();"right"!==c&&"center"!==c||this.alignButtonGroup(a,b[this.currentButtonIndex()].getBBox().width);
this.showDropdown()};t.prototype.expandButtons=function(){var a=this.buttons,b=this.buttonOptions,c=this.options,d=this.zoomText;this.hideDropdown();d&&d.show();b.forEach(function(b,d){d=a[d];d.show();d.attr({text:b.text,width:c.buttonTheme.width||28,paddingLeft:q(c.buttonTheme.paddingLeft,"unset"),paddingRight:q(c.buttonTheme.paddingRight,"unset")});2>d.state&&d.setState(0)});this.positionButtons()};t.prototype.currentButtonIndex=function(){var a=this.dropdown;return a&&0<a.selectedIndex?a.selectedIndex-
1:0};t.prototype.showDropdown=function(){var a=this.buttonGroup,b=this.buttons,c=this.chart,d=this.dropdown;if(a&&d){var f=a.translateX;a=a.translateY;b=b[this.currentButtonIndex()].getBBox();h(d,{left:c.plotLeft+f+"px",top:a+.5+"px",width:b.width+"px",height:b.height+"px"});this.hasVisibleDropdown=!0}};t.prototype.hideDropdown=function(){var a=this.dropdown;a&&(h(a,{top:"-9999em",width:"1px",height:"1px"}),this.hasVisibleDropdown=!1)};t.prototype.getHeight=function(){var a=this.options,b=this.group,
c=a.y,d=a.buttonPosition.y,f=a.inputPosition.y;if(a.height)return a.height;this.alignElements();a=b?b.getBBox(!0).height+13+c:0;b=Math.min(f,d);if(0>f&&0>d||0<f&&0<d)a+=Math.abs(b);return a};t.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};t.prototype.update=function(a){var b=this.chart;x(!0,b.options.rangeSelector,a);this.destroy();this.init(b);this.render()};t.prototype.destroy=function(){var a=this,b=a.minInput,c=a.maxInput;a.eventsToUnbind&&(a.eventsToUnbind.forEach(function(a){return a()}),
a.eventsToUnbind=void 0);K(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);l(a,function(b,c){b&&"chart"!==c&&(b instanceof H?b.destroy():b instanceof window.HTMLElement&&G(b));b!==t.prototype[c]&&(a[c]=null)},this)};return t}();F.prototype.defaultButtons=[{type:"month",count:1,text:"1m",title:"View 1 month"},{type:"month",count:3,text:"3m",title:"View 3 months"},{type:"month",count:6,text:"6m",title:"View 6 months"},{type:"ytd",text:"YTD",title:"View year to date"},
{type:"year",count:1,text:"1y",title:"View 1 year"},{type:"all",text:"All",title:"View all"}];F.prototype.inputTypeFormats={"datetime-local":"%Y-%m-%dT%H:%M:%S",date:"%Y-%m-%d",time:"%H:%M:%S"};a.prototype.minFromRange=function(){var a=this.range,b=a.type,c=this.max,e=this.chart.time,d=function(a,c){var d="year"===b?"FullYear":"Month",f=new e.Date(a),n=e.get(d,f);e.set(d,f,n+c);n===e.get(d,f)&&e.set("Date",f,0);return f.getTime()-a};if(I(a)){var f=c-a;var g=a}else f=c+d(c,-a.count),this.chart&&(this.chart.fixedRange=
c-f);var h=q(this.dataMin,Number.MIN_VALUE);I(f)||(f=h);f<=h&&(f=h,"undefined"===typeof g&&(g=d(f,a.count)),this.newMax=Math.min(f+g,this.dataMax));I(c)||(f=void 0);return f};if(!w.RangeSelector){var r=[],E=function(a){function c(){e&&(n=a.xAxis[0].getExtremes(),d=a.legend,g=e&&e.options.verticalAlign,I(n.min)&&e.render(n.min,n.max),d.display&&"top"===g&&g===d.options.verticalAlign&&(f=x(a.spacingBox),f.y="vertical"===d.options.layout?a.plotTop:f.y+e.getHeight(),d.group.placed=!1,d.align(f)))}var n,
e=a.rangeSelector,d,f,g;e&&(O(r,function(b){return b[0]===a})||r.push([a,[b(a.xAxis[0],"afterSetExtremes",function(a){e&&e.render(a.min,a.max)}),b(a,"redraw",c)]]),c())};b(p,"afterGetContainer",function(){this.options.rangeSelector&&this.options.rangeSelector.enabled&&(this.rangeSelector=new F(this))});b(p,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(I(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),
this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))});b(p,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!B(a)&&this.options.rangeSelector&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=a=new F(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(E(this),b=b&&b.verticalAlign||a.options&&
a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==e)&&(this.isDirtyBox=!0)});b(p,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))});b(p,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=
a),this.extraBottomMargin&&(this.marginBottom+=a))});p.prototype.callbacks.push(E);b(p,"destroy",function(){for(var a=0;a<r.length;a++){var b=r[a];if(b[0]===this){b[1].forEach(function(a){return a()});r.splice(a,1);break}}});w.RangeSelector=F}return F});G(a,"Core/Chart/StockChart.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/FormatUtilities.js"],a["Core/DefaultOptions.js"],a["Core/Color/Palette.js"],a["Core/Series/Point.js"],a["Core/Series/Series.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,p,w,v,g,H,u,D,c,b){function C(a,b){return"xAxis"===a?{minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0}:"yAxis"===a?{labels:{y:-2},opposite:t(b.opposite,!0),showLastLabel:!(!b.categories&&"category"!==b.type),title:{text:null}}:{}}function h(a,b){if("xAxis"===a){a=z();var c={type:"datetime",categories:void 0};t(b.navigator&&b.navigator.enabled,a.navigator.enabled,
!0)&&(c.startOnTick=!1,c.endOnTick=!1);return c}return{}}var B=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),G=a.animObject,O=v.format,z=g.getOptions,Q=u.prototype.tooltipFormatter;a=D.prototype;
var A=a.init,I=a.processData;a=b.addEvent;var x=b.arrayMax,l=b.arrayMin,m=b.clamp,q=b.defined,J=b.extend,N=b.find,F=b.isNumber,r=b.isString,E=b.merge,t=b.pick,k=b.splat;b=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}B(b,a);b.prototype.init=function(b,c){var d=z(),e=b.xAxis,f=b.yAxis,g=t(b.navigator&&b.navigator.enabled,d.navigator.enabled,!0);b.xAxis=b.yAxis=void 0;g=E({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:g},scrollbar:{enabled:t(d.scrollbar&&
d.scrollbar.enabled,!0)},rangeSelector:{enabled:t(d.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:t(d.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},b,{isStock:!0});b.xAxis=e;b.yAxis=f;g.xAxis=k(b.xAxis||{}).map(function(a,c){return E(C("xAxis",a),d.xAxis,d.xAxis&&d.xAxis[c],a,h("xAxis",b))});g.yAxis=k(b.yAxis||{}).map(function(a,b){return E(C("yAxis",a),d.yAxis,d.yAxis&&d.yAxis[b],a)});a.prototype.init.call(this,g,c)};b.prototype.createAxis=function(b,c){c.axis=E(C(b,c.axis),
c.axis,h(b,this.userOptions));return a.prototype.createAxis.call(this,b,c)};return b}(w);(function(a){a.stockChart=function(b,c,f){return new a(b,c,f)}})(b||(b={}));a(D,"setOptions",function(a){var b;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?b={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(b={marker:{enabled:!1,radius:2}}),b&&(a.plotOptions[this.type]=E(a.plotOptions[this.type],b)))});a(p,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=
b._labelPanes||{};var f=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&f.enabled&&(15===f.x&&(f.x=0),"undefined"===typeof f.align&&(f.align="right"),b[c]=this,a.align="right",a.preventDefault()))});a(p,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});a(p,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=
c.options[b];return F(a)?[g[b][a]]:r(a)?[g.get(a)]:f.map(function(a){return a[b]})}var c=this,f=this.isLinked&&!this.series?this.linkedParent.series:this.series,g=c.chart,h=g.renderer,n=c.left,k=c.top,l,p,u,v,w=[],x=[],z=a.translatedValue,A=a.value,B=a.force;if(g.options.isStock&&!1!==a.acrossPanes&&"xAxis"===c.coll||"yAxis"===c.coll){a.preventDefault();x=b(c.coll);var D=c.isXAxis?g.yAxis:g.xAxis;D.forEach(function(a){if(q(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":
"xAxis";b=q(a.options[b])?g[b][a.options[b]]:g[b][0];c===b&&x.push(a)}});var C=x.length?[]:[c.isXAxis?g.yAxis[0]:g.xAxis[0]];x.forEach(function(a){-1!==C.indexOf(a)||N(C,function(b){return b.pos===a.pos&&b.len===a.len})||C.push(a)});var E=t(z,c.translate(A,null,null,a.old));F(E)&&(c.horiz?C.forEach(function(a){var b;p=a.pos;v=p+a.len;l=u=Math.round(E+c.transB);"pass"!==B&&(l<n||l>n+c.width)&&(B?l=u=m(l,n,n+c.width):b=!0);b||w.push(["M",l,p],["L",u,v])}):C.forEach(function(a){var b;l=a.pos;u=l+a.len;
p=v=Math.round(k+c.height-E);"pass"!==B&&(p<k||p>k+c.height)&&(B?p=v=m(p,k,k+c.height):b=!0);b||w.push(["M",l,p],["L",u,v])}));a.path=0<w.length?h.crispPolyLine(w,a.lineWidth||1):null}});c.prototype.crispPolyLine=function(a,b){for(var c=0;c<a.length;c+=2){var e=a[c],g=a[c+1];e[1]===g[1]&&(e[1]=g[1]=Math.round(e[1])-b%2/2);e[2]===g[2]&&(e[2]=g[2]=Math.round(e[2])+b%2/2)}return a};a(p,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});a(p,"afterDrawCrosshair",
function(a){var b,c;if(this.crosshair&&this.crosshair.label&&this.crosshair.label.enabled&&this.cross&&F(this.min)&&F(this.max)){var f=this.chart,g=this.logarithmic,h=this.crosshair.label,k=this.horiz,n=this.opposite,l=this.left,m=this.top,p=this.crossLabel,q=h.format,r="",u="inside"===this.options.tickPosition,v=!1!==this.crosshair.snap,w=0,x=a.e||this.cross&&this.cross.e;a=a.point;var z=this.min,A=this.max;g&&(z=g.lin2log(z),A=g.lin2log(A));g=k?"center":n?"right"===this.labelAlign?"right":"left":
"left"===this.labelAlign?"left":"center";p||(p=this.crossLabel=f.renderer.label("",0,void 0,h.shape||"callout").addClass("highcharts-crosshair-label highcharts-color-"+(a?a.series.colorIndex:this.series[0]&&this.series[0].colorIndex)).attr({align:h.align||g,padding:t(h.padding,8),r:t(h.borderRadius,3),zIndex:2}).add(this.labelGroup),f.styledMode||p.attr({fill:h.backgroundColor||a&&a.series&&a.series.color||H.neutralColor60,stroke:h.borderColor||"","stroke-width":h.borderWidth||0}).css(J({color:H.backgroundColor,
fontWeight:"normal",fontSize:"11px",textAlign:"center"},h.style||{})));k?(g=v?(a.plotX||0)+l:x.chartX,m+=n?0:this.height):(g=n?this.width+l:0,m=v?(a.plotY||0)+m:x.chartY);q||h.formatter||(this.dateTime&&(r="%b %d, %Y"),q="{value"+(r?":"+r:"")+"}");r=v?this.isXAxis?a.x:a.y:this.toValue(k?x.chartX:x.chartY);v=a?a.series.isPointInside(a):F(r)&&r>z&&r<A;x="";q?x=O(q,{value:r},f):h.formatter&&F(r)&&(x=h.formatter.call(this,r));p.attr({text:x,x:g,y:m,visibility:v?"visible":"hidden"});h=p.getBBox();if(F(p.y))if(k){if(u&&
!n||!u&&n)m=p.y-h.height}else m=p.y-h.height/2;k?(b=l-h.x,c=l+this.width-h.x):(b="left"===this.labelAlign?l:0,c="right"===this.labelAlign?l+this.width:f.chartWidth);p.translateX<b&&(w=b-p.translateX);p.translateX+h.width>=c&&(w=-(p.translateX+h.width-c));p.attr({x:g+w,y:m,anchorX:k?g:this.opposite?0:f.chartWidth,anchorY:k?this.opposite?f.chartHeight:0:m+h.height/2})}});D.prototype.init=function(){A.apply(this,arguments);this.initCompare(this.options.compare)};D.prototype.setCompare=function(a){this.initCompare(a);
this.userOptions.compare=a};D.prototype.initCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.chart.hasRendered&&(this.isDirty=!0)};D.prototype.forceCropping=function(){var a=this.chart,b=this.options.dataGrouping;return!1!==this.allowDG&&b&&t(b.enabled,a.options.isStock)};D.prototype.processData=
function(a){var b,c=-1,f=!0===this.options.compareStart?0:1;I.apply(this,arguments);if(this.xAxis&&this.processedYData){var g=this.processedXData;var h=this.processedYData;var k=h.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<k-f;b++){var n=h[b]&&-1<c?h[b][c]:h[b];if(F(n)&&g[b+f]>=this.xAxis.min&&0!==n){this.compareValue=n;break}}}};a(D,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&a){var b=[this.modifyValue(a.dataMin),
this.modifyValue(a.dataMax)];a.dataMin=l(b);a.dataMax=x(b)}});p.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),t(b,!0)&&this.chart.redraw())};u.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,t(this.series.tooltipOptions.changeDecimals,2)));return Q.apply(this,[a])};a(D,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&
!this.xAxis.isRadial&&!1!==this.options.clip){var b=this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,f=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(f-c,0))}if(!a.hasLoaded||!this.clipBox&&this.isDirty&&!this.isDirtyData)this.clipBox=this.clipBox||E(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b;a.hasRendered&&(c=G(this.options.animation),c=this.getSharedClipKey(c),f=a.sharedClips[c])&&(f.animate({width:this.xAxis.len,
height:b}),(a=a.sharedClips[c+"m"])&&a.animate({width:this.xAxis.len}))}});a(w,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(E(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});"";return b});G(a,"masters/modules/stock.src.js",[a["Core/Globals.js"],a["Core/Scrollbar.js"],a["Core/Chart/StockChart.js"]],function(a,p,w){a.Scrollbar=p;a.StockChart=a.stockChart=w.stockChart;p.compose(a.Axis)})});
//# sourceMappingURL=stock.js.map