/*
 Highcharts JS v9.1.2 (2021-07-09)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(z){e(z);e.Highcharts=z;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function z(e,d,b,k){e.hasOwnProperty(d)||(e[d]=k.apply(null,b))}e=e?e._modules:{};z(e,"Extensions/Pane.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Pointer.js"],
e["Core/Utilities.js"],e["Mixins/CenteredSeries.js"]],function(e,d,b,k,a,r){function q(c,n,a){return Math.sqrt(Math.pow(c-a[0],2)+Math.pow(n-a[1],2))<=a[2]/2}var l=a.addEvent,w=a.extend,y=a.merge,c=a.pick,m=a.splat;e.prototype.collectionsWithUpdate.push("pane");a=function(){function c(c,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,
borderColor:b.neutralColor20,backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,b.backgroundColor],[1,b.neutralColor10]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(c,a)}c.prototype.init=function(c,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(c)};c.prototype.setOptions=function(c){this.options=y(this.defaultOptions,this.chart.angular?{background:{}}:void 0,c)};c.prototype.render=function(){var c=this.options,a=this.options.background,
h=this.chart.renderer;this.group||(this.group=h.g("pane-group").attr({zIndex:c.zIndex||0}).add());this.updateCenter();if(a)for(a=m(a),c=Math.max(a.length,this.background.length||0),h=0;h<c;h++)a[h]&&this.axis?this.renderBackground(y(this.defaultBackgroundOptions,a[h]),h):this.background[h]&&(this.background[h]=this.background[h].destroy(),this.background.splice(h,1))};c.prototype.renderBackground=function(c,a){var h="animate",n={"class":"highcharts-pane "+(c.className||"")};this.chart.styledMode||
w(n,{fill:c.backgroundColor,stroke:c.borderColor,"stroke-width":c.borderWidth});this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),h="attr");this.background[a][h]({d:this.axis.getPlotBandPath(c.from,c.to,c)}).attr(n)};c.prototype.updateCenter=function(c){this.center=(c||this.axis||{}).center=r.getCenter.call(this)};c.prototype.update=function(c,a){y(!0,this.options,c);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(c){c.pane===this&&(c.pane=
null,c.update({},a))},this)};return c}();e.prototype.getHoverPane=function(c){var a=this,h;c&&a.pane.forEach(function(m){var n=c.chartX-a.plotLeft,x=c.chartY-a.plotTop;q(a.inverted?x:n,a.inverted?n:x,m.center)&&(h=m)});return h};l(e,"afterIsInsidePlot",function(c){this.polar&&(c.isInsidePlot=this.pane.some(function(a){return q(c.x,c.y,a.center)}))});l(k,"beforeGetHoverData",function(a){var m=this.chart;m.polar?(m.hoverPane=m.getHoverPane(a),a.filter=function(h){return h.visible&&!(!a.shared&&h.directTouch)&&
c(h.options.enableMouseTracking,!0)&&(!m.hoverPane||h.xAxis.pane===m.hoverPane)}):m.hoverPane=void 0});l(k,"afterGetHoverData",function(c){var a=this.chart;c.hoverPoint&&c.hoverPoint.plotX&&c.hoverPoint.plotY&&a.hoverPane&&!q(c.hoverPoint.plotX,c.hoverPoint.plotY,a.hoverPane.center)&&(c.hoverPoint=void 0)});d.Pane=a;return d.Pane});z(e,"Core/Axis/RadialAxis.js",[e["Core/Axis/AxisDefaults.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,b){var k=d.noop,a=b.addEvent,r=b.correctFloat,q=
b.defined,l=b.extend,w=b.fireEvent,y=b.merge,c=b.pick,m=b.relativeLength,h=b.wrap,n;(function(n){function x(){this.autoConnect=this.isCircular&&"undefined"===typeof c(this.userMax,this.options.max)&&r(this.endAngleRad-this.startAngleRad)===r(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)}function b(){var f=this;return function(){if(f.isRadial&&f.tickPositions&&f.options.labels&&!0!==f.options.labels.allowOverlap)return f.tickPositions.map(function(c){return f.ticks[c]&&
f.ticks[c].label}).filter(function(f){return!!f})}}function d(){return k}function t(f,c,g){var p=this.pane.center,u=f.value;if(this.isCircular){if(q(u))f.point&&(a=f.point.shapeArgs||{},a.start&&(u=this.chart.inverted?this.translate(f.point.rectPlotY,!0):f.point.x));else{var a=f.chartX||0;var v=f.chartY||0;u=this.translate(Math.atan2(v-g,a-c)-this.startAngleRad,!0)}f=this.getPosition(u);a=f.x;v=f.y}else q(u)||(a=f.chartX,v=f.chartY),q(a)&&q(v)&&(g=p[1]+this.chart.plotTop,u=this.translate(Math.min(Math.sqrt(Math.pow(a-
c,2)+Math.pow(v-g,2)),p[2]/2)-p[3]/2,!0));return[u,a||0,v||0]}function A(f,g,p){f=this.pane.center;var u=this.chart,a=this.left||0,v=this.top||0,m=c(g,f[2]/2-this.offset);"undefined"===typeof p&&(p=this.horiz?0:this.center&&-this.center[3]/2);p&&(m+=p);this.isCircular||"undefined"!==typeof g?(g=this.chart.renderer.symbols.arc(a+f[0],v+f[1],m,m,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),g.xBounds=[a+f[0]],g.yBounds=[v+f[1]-m]):(g=this.postTranslate(this.angleRad,m),g=[["M",this.center[0]+
u.plotLeft,this.center[1]+u.plotTop],["L",g.x,g.y]]);return g}function g(){this.constructor.prototype.getOffset.call(this);this.chart.axisOffset[this.side]=0}function f(f,g,p){var u=this.chart,a=function(f){if("string"===typeof f){var g=parseInt(f,10);x.test(f)&&(g=g*E/100);return g}return f},v=this.center,m=this.startAngleRad,E=v[2]/2,h=Math.min(this.offset,0),n=this.left||0,A=this.top||0,x=/%$/,t=this.isCircular,C=c(a(p.outerRadius),E),b=a(p.innerRadius);a=c(a(p.thickness),10);if("polygon"===this.options.gridLineInterpolation)h=
this.getPlotLinePath({value:f}).concat(this.getPlotLinePath({value:g,reverse:!0}));else{f=Math.max(f,this.min);g=Math.min(g,this.max);f=this.translate(f);g=this.translate(g);t||(C=f||0,b=g||0);if("circle"!==p.shape&&t)p=m+(f||0),m+=g||0;else{p=-Math.PI/2;m=1.5*Math.PI;var d=!0}C-=h;h=u.renderer.symbols.arc(n+v[0],A+v[1],C,C,{start:Math.min(p,m),end:Math.max(p,m),innerR:c(b,C-(a-h)),open:d});t&&(t=(m+p)/2,n=n+v[0]+v[2]/2*Math.cos(t),h.xBounds=t>-Math.PI/2&&t<Math.PI/2?[n,u.plotWidth]:[0,n],h.yBounds=
[A+v[1]+v[2]/2*Math.sin(t)],h.yBounds[0]+=t>-Math.PI&&0>t||t>Math.PI?-10:10)}return h}function u(f){var g=this,c=this.pane.center,p=this.chart,u=p.inverted,a=f.reverse,v=this.pane.options.background?this.pane.options.background[0]||this.pane.options.background:{},h=v.innerRadius||"0%",E=v.outerRadius||"100%",n=c[0]+p.plotLeft,A=c[1]+p.plotTop,x=this.height,t=f.isCrosshair;v=c[3]/2;var C=f.value,b;var d=this.getPosition(C);var l=d.x;d=d.y;t&&(d=this.getCrosshairPosition(f,n,A),C=d[0],l=d[1],d=d[2]);
if(this.isCircular)C=Math.sqrt(Math.pow(l-n,2)+Math.pow(d-A,2)),a="string"===typeof h?m(h,1):h/C,p="string"===typeof E?m(E,1):E/C,c&&v&&(v/=C,a<v&&(a=v),p<v&&(p=v)),c=[["M",n+a*(l-n),A-a*(A-d)],["L",l-(1-p)*(l-n),d+(1-p)*(A-d)]];else if((C=this.translate(C))&&(0>C||C>x)&&(C=0),"circle"===this.options.gridLineInterpolation)c=this.getLinePath(0,C,v);else if(c=[],p[u?"yAxis":"xAxis"].forEach(function(f){f.pane===g.pane&&(b=f)}),b)for(n=b.tickPositions,b.autoConnect&&(n=n.concat([n[0]])),a&&(n=n.slice().reverse()),
C&&(C+=v),A=0;A<n.length;A++)v=b.getPosition(n[A],C),c.push(A?["L",v.x,v.y]:["M",v.x,v.y]);return c}function p(f,g){f=this.translate(f);return this.postTranslate(this.isCircular?f:this.angleRad,c(this.isCircular?g:0>f?0:f,this.center[2]/2)-this.offset)}function E(){var f=this.center,g=this.chart,c=this.options.title;return{x:g.plotLeft+f[0]+(c.x||0),y:g.plotTop+f[1]-{high:.5,middle:.25,low:0}[c.align]*f[2]+(c.y||0)}}function v(c){c.beforeSetTickPositions=x;c.createLabelCollector=b;c.getCrosshairPosition=
t;c.getLinePath=A;c.getOffset=g;c.getPlotBandPath=f;c.getPlotLinePath=u;c.getPosition=p;c.getTitlePosition=E;c.postTranslate=D;c.setAxisSize=F;c.setAxisTranslation=O;c.setOptions=G}function C(){var f=this.chart,g=this.options,p=this.pane,u=p&&p.options;f.angular&&this.isXAxis||!p||!f.angular&&!f.polar||(this.angleRad=(g.angle||0)*Math.PI/180,this.startAngleRad=(u.startAngle-90)*Math.PI/180,this.endAngleRad=(c(u.endAngle,u.startAngle+360)-90)*Math.PI/180,this.offset=g.offset||0)}function K(f){this.isRadial&&
(f.align=void 0,f.preventDefault())}function P(){if(this.chart&&this.chart.labelCollectors){var f=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=f&&this.chart.labelCollectors.splice(f,1)}}function Q(f){var c=this.chart,g=c.inverted,p=c.angular,u=c.polar,a=this.isXAxis,m=this.coll,h=p&&a,n=c.options;f=f.userOptions.pane||0;f=this.pane=c.pane&&c.pane[f];var E;if("colorAxis"===m)this.isRadial=!1;else{if(p){if(h?(this.isHidden=!0,this.createLabelCollector=d,this.getOffset=
k,this.render=this.redraw=R,this.setTitle=this.setCategories=this.setScale=k):v(this),E=!a)this.defaultPolarOptions=S}else u&&(v(this),this.defaultPolarOptions=(E=this.horiz)?T:y("xAxis"===m?e.defaultXAxisOptions:e.defaultYAxisOptions,U),g&&"yAxis"===m&&(this.defaultPolarOptions.stackLabels=e.defaultYAxisOptions.stackLabels,this.defaultPolarOptions.reversedStacks=!0));p||u?(this.isRadial=!0,n.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&
c.labelCollectors.push(this.labelCollector)):this.isRadial=!1;f&&E&&(f.axis=this);this.isCircular=E}}function V(){this.isRadial&&this.beforeSetTickPositions()}function L(f){var g=this.label;if(g){var p=this.axis,u=g.getBBox(),a=p.options.labels,v=(p.translate(this.pos)+p.startAngleRad+Math.PI/2)/Math.PI*180%360,h=Math.round(v),n=q(a.y)?0:.3*-u.height,E=a.y,A=20,C=a.align,x="end",t=0>h?h+360:h,d=t,b=0,l=0;if(p.isRadial){var k=p.getPosition(this.pos,p.center[2]/2+m(c(a.distance,-25),p.center[2]/2,-p.center[2]/
2));"auto"===a.rotation?g.attr({rotation:v}):q(E)||(E=p.chart.renderer.fontMetrics(g.styles&&g.styles.fontSize).b-u.height/2);q(C)||(p.isCircular?(u.width>p.len*p.tickInterval/(p.max-p.min)&&(A=0),C=v>A&&v<180-A?"left":v>180+A&&v<360-A?"right":"center"):C="center",g.attr({align:C}));if("auto"===C&&2===p.tickPositions.length&&p.isCircular){90<t&&180>t?t=180-t:270<t&&360>=t&&(t=540-t);180<d&&360>=d&&(d=360-d);if(p.pane.options.startAngle===h||p.pane.options.startAngle===h+360||p.pane.options.startAngle===
h-360)x="start";C=-90<=h&&90>=h||-360<=h&&-270>=h||270<=h&&360>=h?"start"===x?"right":"left":"start"===x?"left":"right";70<d&&110>d&&(C="center");15>t||180<=t&&195>t?b=.3*u.height:15<=t&&35>=t?b="start"===x?0:.75*u.height:195<=t&&215>=t?b="start"===x?.75*u.height:0:35<t&&90>=t?b="start"===x?.25*-u.height:u.height:215<t&&270>=t&&(b="start"===x?u.height:.25*-u.height);15>d?l="start"===x?.15*-u.height:.15*u.height:165<d&&180>=d&&(l="start"===x?.15*u.height:.15*-u.height);g.attr({align:C});g.translate(l,
b+n)}f.pos.x=k.x+(a.x||0);f.pos.y=k.y+(E||0)}}}function J(f){this.axis.getPosition&&l(f.pos,this.axis.getPosition(this.pos))}function D(f,g){var c=this.chart,p=this.center;f=this.startAngleRad+f;return{x:c.plotLeft+p[0]+Math.cos(f)*g,y:c.plotTop+p[1]+Math.sin(f)*g}}function R(){this.isDirty=!1}function F(){this.constructor.prototype.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var f=this.center=this.pane.center.slice();if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;
else{var g=this.postTranslate(this.angleRad,f[3]/2);f[0]=g.x-this.chart.plotLeft;f[1]=g.y-this.chart.plotTop}this.len=this.width=this.height=(f[2]-f[3])*c(this.sector,1)/2}}function O(){this.constructor.prototype.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)}function G(f){f=this.options=
y(this.constructor.defaultOptions,this.defaultPolarOptions,f);f.plotBands||(f.plotBands=[]);w(this,"afterSetOptions")}function z(f,g,c,p,u,a,v){var h=this.axis;h.isRadial?(f=h.getPosition(this.pos,h.center[2]/2+p),g=["M",g,c,"L",f.x,f.y]):g=f.call(this,g,c,p,u,a,v);return g}var N=[],T={gridLineWidth:1,labels:{align:void 0,distance:15,x:0,y:void 0,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},S={labels:{align:"center",x:0,y:void 0},minorGridLineWidth:0,minorTickInterval:"auto",
minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},U={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};n.compose=function(f,g){-1===N.indexOf(f)&&(N.push(f),a(f,"afterInit",C),a(f,"autoLabelAlign",K),a(f,"destroy",P),a(f,"init",Q),a(f,"initialAxisTranslation",V));-1===N.indexOf(g)&&(N.push(g),a(g,"afterGetLabelPosition",L),a(g,
"afterGetPosition",J),h(g.prototype,"getMarkPath",z));return f}})(n||(n={}));return n});z(e,"Series/AreaRange/AreaRangePoint.js",[e["Series/Area/AreaSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,d,b){var k=this&&this.__extends||function(){var a=function(d,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var h in a)a.hasOwnProperty(h)&&(c[h]=a[h])};return a(d,b)};return function(d,b){function c(){this.constructor=
d}a(d,b);d.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}}(),a=d.prototype,r=b.defined,q=b.isNumber;return function(d){function b(){var a=null!==d&&d.apply(this,arguments)||this;a.high=void 0;a.low=void 0;a.options=void 0;a.plotHigh=void 0;a.plotLow=void 0;a.plotHighX=void 0;a.plotLowX=void 0;a.plotX=void 0;a.series=void 0;return a}k(b,d);b.prototype.setState=function(){var d=this.state,c=this.series,m=c.chart.polar;r(this.plotHigh)||(this.plotHigh=c.yAxis.toPixels(this.high,
!0));r(this.plotLow)||(this.plotLow=this.plotY=c.yAxis.toPixels(this.low,!0));c.stateMarkerGraphic&&(c.lowerStateMarkerGraphic=c.stateMarkerGraphic,c.stateMarkerGraphic=c.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;m&&(this.plotX=this.plotHighX);a.setState.apply(this,arguments);this.state=d;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;m&&(this.plotX=this.plotLowX);c.stateMarkerGraphic&&(c.upperStateMarkerGraphic=c.stateMarkerGraphic,c.stateMarkerGraphic=
c.lowerStateMarkerGraphic,c.lowerStateMarkerGraphic=void 0);a.setState.apply(this,arguments)};b.prototype.haloPath=function(){var d=this.series.chart.polar,c=[];this.plotY=this.plotLow;d&&(this.plotX=this.plotLowX);this.isInside&&(c=a.haloPath.apply(this,arguments));this.plotY=this.plotHigh;d&&(this.plotX=this.plotHighX);this.isTopInside&&(c=c.concat(a.haloPath.apply(this,arguments)));return c};b.prototype.isValid=function(){return q(this.low)&&q(this.high)};return b}(e.prototype.pointClass)});z(e,
"Series/AreaRange/AreaRangeSeries.js",[e["Series/AreaRange/AreaRangePoint.js"],e["Series/Area/AreaSeries.js"],e["Series/Column/ColumnSeries.js"],e["Core/Globals.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k,a,r,q){var l=this&&this.__extends||function(){var c=function(a,h){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,g){c.__proto__=g}||function(c,g){for(var f in g)g.hasOwnProperty(f)&&(c[f]=g[f])};return c(a,h)};return function(a,
h){function m(){this.constructor=a}c(a,h);a.prototype=null===h?Object.create(h):(m.prototype=h.prototype,new m)}}(),w=d.prototype,y=b.prototype;b=k.noop;var c=a.prototype,m=q.defined,h=q.extend,n=q.isArray,x=q.pick,B=q.merge;a=function(a){function b(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;c.lowerStateMarkerGraphic=void 0;c.xAxis=void 0;return c}l(b,a);b.prototype.toYData=function(c){return[c.low,c.high]};b.prototype.highToXY=function(c){var a=
this.chart,g=this.xAxis.postTranslate(c.rectPlotX||0,this.yAxis.len-c.plotHigh);c.plotHighX=g.x-a.plotLeft;c.plotHigh=g.y-a.plotTop;c.plotLowX=c.plotX};b.prototype.translate=function(){var c=this,a=c.yAxis,g=!!c.modifyValue;w.translate.apply(c);c.points.forEach(function(f){var u=f.high,p=f.plotY;f.isNull?f.plotY=null:(f.plotLow=p,f.plotHigh=a.translate(g?c.modifyValue(u,f):u,0,1,0,1),g&&(f.yBottom=f.plotHigh))});this.chart.polar&&this.points.forEach(function(f){c.highToXY(f);f.tooltipPos=[(f.plotHighX+
f.plotLowX)/2,(f.plotHigh+f.plotLow)/2]})};b.prototype.getGraphPath=function(c){var a=[],g=[],f,u=w.getGraphPath;var p=this.options;var h=this.chart.polar,v=h&&!1!==p.connectEnds,m=p.connectNulls,n=p.step;c=c||this.points;for(f=c.length;f--;){var b=c[f];var d=h?{plotX:b.rectPlotX,plotY:b.yBottom,doCurve:!1}:{plotX:b.plotX,plotY:b.plotY,doCurve:!1};b.isNull||v||m||c[f+1]&&!c[f+1].isNull||g.push(d);var l={polarPlotY:b.polarPlotY,rectPlotX:b.rectPlotX,yBottom:b.yBottom,plotX:x(b.plotHighX,b.plotX),plotY:b.plotHigh,
isNull:b.isNull};g.push(l);a.push(l);b.isNull||v||m||c[f-1]&&!c[f-1].isNull||g.push(d)}c=u.call(this,c);n&&(!0===n&&(n="left"),p.step={left:"right",center:"center",right:"left"}[n]);a=u.call(this,a);g=u.call(this,g);p.step=n;p=[].concat(c,a);!this.chart.polar&&g[0]&&"M"===g[0][0]&&(g[0]=["L",g[0][1],g[0][2]]);this.graphPath=p;this.areaPath=c.concat(g);p.isArea=!0;p.xMap=c.xMap;this.areaPath.xMap=c.xMap;return p};b.prototype.drawDataLabels=function(){var a=this.points,m=a.length,g,f=[],u=this.options.dataLabels,
p,E=this.chart.inverted;if(u){if(n(u)){var v=u[0]||{enabled:!1};var b=u[1]||{enabled:!1}}else v=h({},u),v.x=u.xHigh,v.y=u.yHigh,b=h({},u),b.x=u.xLow,b.y=u.yLow;if(v.enabled||this._hasPointLabels){for(g=m;g--;)if(p=a[g]){var d=v.inside?p.plotHigh<p.plotLow:p.plotHigh>p.plotLow;p.y=p.high;p._plotY=p.plotY;p.plotY=p.plotHigh;f[g]=p.dataLabel;p.dataLabel=p.dataLabelUpper;p.below=d;E?v.align||(v.align=d?"right":"left"):v.verticalAlign||(v.verticalAlign=d?"top":"bottom")}this.options.dataLabels=v;c.drawDataLabels&&
c.drawDataLabels.apply(this,arguments);for(g=m;g--;)if(p=a[g])p.dataLabelUpper=p.dataLabel,p.dataLabel=f[g],delete p.dataLabels,p.y=p.low,p.plotY=p._plotY}if(b.enabled||this._hasPointLabels){for(g=m;g--;)if(p=a[g])d=b.inside?p.plotHigh<p.plotLow:p.plotHigh>p.plotLow,p.below=!d,E?b.align||(b.align=d?"left":"right"):b.verticalAlign||(b.verticalAlign=d?"bottom":"top");this.options.dataLabels=b;c.drawDataLabels&&c.drawDataLabels.apply(this,arguments)}if(v.enabled)for(g=m;g--;)if(p=a[g])p.dataLabels=[p.dataLabelUpper,
p.dataLabel].filter(function(f){return!!f});this.options.dataLabels=u}};b.prototype.alignDataLabel=function(){y.alignDataLabel.apply(this,arguments)};b.prototype.drawPoints=function(){var a=this.points.length,b;c.drawPoints.apply(this,arguments);for(b=0;b<a;){var g=this.points[b];g.origProps={plotY:g.plotY,plotX:g.plotX,isInside:g.isInside,negative:g.negative,zone:g.zone,y:g.y};g.lowerGraphic=g.graphic;g.graphic=g.upperGraphic;g.plotY=g.plotHigh;m(g.plotHighX)&&(g.plotX=g.plotHighX);g.y=x(g.high,
g.origProps.y);g.negative=g.y<(this.options.threshold||0);this.zones.length&&(g.zone=g.getZone());this.chart.polar||(g.isInside=g.isTopInside="undefined"!==typeof g.plotY&&0<=g.plotY&&g.plotY<=this.yAxis.len&&0<=g.plotX&&g.plotX<=this.xAxis.len);b++}c.drawPoints.apply(this,arguments);for(b=0;b<a;)g=this.points[b],g.upperGraphic=g.graphic,g.graphic=g.lowerGraphic,g.origProps&&(h(g,g.origProps),delete g.origProps),b++};b.defaultOptions=B(d.defaultOptions,{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}});return b}(d);h(a.prototype,{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,pointClass:e,setStackedPoints:b});r.registerSeriesType("arearange",a);"";return a});z(e,"Series/AreaSplineRange/AreaSplineRangeSeries.js",[e["Series/AreaRange/AreaRangeSeries.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b){var k=this&&this.__extends||function(){var a=function(b,
d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var h in a)a.hasOwnProperty(h)&&(c[h]=a[h])};return a(b,d)};return function(b,d){function c(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}(),a=d.seriesTypes.spline,r=b.merge;b=b.extend;var q=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.options=void 0;b.data=void 0;b.points=void 0;return b}k(b,a);b.defaultOptions=
r(e.defaultOptions);return b}(e);b(q.prototype,{getPointSpline:a.prototype.getPointSpline});d.registerSeriesType("areasplinerange",q);"";return q});z(e,"Series/BoxPlot/BoxPlotSeries.js",[e["Series/Column/ColumnSeries.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k,a){var r=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,
a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return a(c,b)};return function(c,b){function h(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(h.prototype=b.prototype,new h)}}();d=d.noop;var q=a.extend,l=a.merge,w=a.pick;a=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}r(c,a);c.prototype.pointAttribs=function(){return{}};c.prototype.translate=function(){var c=this.yAxis,b=this.pointArrayMap;a.prototype.translate.apply(this);
this.points.forEach(function(a){b.forEach(function(b){null!==a[b]&&(a[b+"Plot"]=c.translate(a[b],0,1,0,1))});a.plotHigh=a.highPlot})};c.prototype.drawPoints=function(){var c=this,a=c.options,b=c.chart,d=b.renderer,k,l,e,q,A,g,f=0,u,p,E,v,C=!1!==c.doQuartiles,K,r=c.options.whiskerLength;c.points.forEach(function(h){var n=h.graphic,m=n?"animate":"attr",x=h.shapeArgs,t={},I={},y={},B={},H=h.color||c.color;"undefined"!==typeof h.plotY&&(u=Math.round(x.width),p=Math.floor(x.x),E=p+u,v=Math.round(u/2),
k=Math.floor(C?h.q1Plot:h.lowPlot),l=Math.floor(C?h.q3Plot:h.lowPlot),e=Math.floor(h.highPlot),q=Math.floor(h.lowPlot),n||(h.graphic=n=d.g("point").add(c.group),h.stem=d.path().addClass("highcharts-boxplot-stem").add(n),r&&(h.whiskers=d.path().addClass("highcharts-boxplot-whisker").add(n)),C&&(h.box=d.path(void 0).addClass("highcharts-boxplot-box").add(n)),h.medianShape=d.path(void 0).addClass("highcharts-boxplot-median").add(n)),b.styledMode||(I.stroke=h.stemColor||a.stemColor||H,I["stroke-width"]=
w(h.stemWidth,a.stemWidth,a.lineWidth),I.dashstyle=h.stemDashStyle||a.stemDashStyle||a.dashStyle,h.stem.attr(I),r&&(y.stroke=h.whiskerColor||a.whiskerColor||H,y["stroke-width"]=w(h.whiskerWidth,a.whiskerWidth,a.lineWidth),y.dashstyle=h.whiskerDashStyle||a.whiskerDashStyle||a.dashStyle,h.whiskers.attr(y)),C&&(t.fill=h.fillColor||a.fillColor||H,t.stroke=a.lineColor||H,t["stroke-width"]=a.lineWidth||0,t.dashstyle=h.boxDashStyle||a.boxDashStyle||a.dashStyle,h.box.attr(t)),B.stroke=h.medianColor||a.medianColor||
H,B["stroke-width"]=w(h.medianWidth,a.medianWidth,a.lineWidth),B.dashstyle=h.medianDashStyle||a.medianDashStyle||a.dashStyle,h.medianShape.attr(B)),g=h.stem.strokeWidth()%2/2,f=p+v+g,n=[["M",f,l],["L",f,e],["M",f,k],["L",f,q]],h.stem[m]({d:n}),C&&(g=h.box.strokeWidth()%2/2,k=Math.floor(k)+g,l=Math.floor(l)+g,p+=g,E+=g,n=[["M",p,l],["L",p,k],["L",E,k],["L",E,l],["L",p,l],["Z"]],h.box[m]({d:n})),r&&(g=h.whiskers.strokeWidth()%2/2,e+=g,q+=g,K=/%$/.test(r)?v*parseFloat(r)/100:r/2,n=[["M",f-K,e],["L",
f+K,e],["M",f-K,q],["L",f+K,q]],h.whiskers[m]({d:n})),A=Math.round(h.medianPlot),g=h.medianShape.strokeWidth()%2/2,A+=g,n=[["M",p,A],["L",E,A]],h.medianShape[m]({d:n}))})};c.prototype.toYData=function(c){return[c.low,c.q1,c.median,c.q3,c.high]};c.defaultOptions=l(e.defaultOptions,{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:b.backgroundColor,lineWidth:1,medianWidth:2,whiskerWidth:2});return c}(e);q(a.prototype,{pointArrayMap:["low","q1","median","q3","high"],pointValKey:"high",drawDataLabels:d,setStackedPoints:d});k.registerSeriesType("boxplot",a);"";return a});z(e,"Series/Bubble/BubbleLegendDefaults.js",[e["Core/Color/Palette.js"]],function(e){return{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,
enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"10px",color:e.neutralColor100},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});z(e,"Series/Bubble/BubbleLegendItem.js",[e["Core/Color/Color.js"],e["Core/FormatUtilities.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,b,k){var a=e.parse,r=b.noop,
q=k.arrayMax,l=k.arrayMin,w=k.isNumber,y=k.merge,c=k.pick,m=k.stableSort;"";return function(){function b(c,a){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=r;this.init(c,a)}b.prototype.init=function(c,a){this.options=c;this.visible=!0;this.chart=a.chart;this.legend=a};b.prototype.addToLegend=function(c){c.splice(this.options.legendIndex,
0,this)};b.prototype.drawLegendSymbol=function(a){var b=this.chart,h=this.options,d=c(a.options.itemDistance,20),n=h.ranges,e=h.connectorDistance;this.fontMetrics=b.renderer.fontMetrics(h.labels.style.fontSize);n&&n.length&&w(n[0].value)?(m(n,function(c,a){return a.value-c.value}),this.ranges=n,this.setOptions(),this.render(),a=this.getMaxLabelSize(),n=this.ranges[0].radius,b=2*n,e=e-n+a.width,e=0<e?e:0,this.maxLabel=a,this.movementX="left"===h.labels.align?e:0,this.legendItemWidth=b+e+d,this.legendItemHeight=
b+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};b.prototype.setOptions=function(){var b=this.ranges,h=this.options,d=this.chart.series[h.seriesIndex],m=this.legend.baseline,e={zIndex:h.zIndex,"stroke-width":h.borderWidth},l={zIndex:h.zIndex,"stroke-width":h.connectorWidth},A={align:this.legend.options.rtl||"left"===h.labels.align?"right":"left",zIndex:h.zIndex},g=d.options.marker.fillOpacity,f=this.chart.styledMode;b.forEach(function(u,p){f||(e.stroke=c(u.borderColor,h.borderColor,d.color),
e.fill=c(u.color,h.color,1!==g?a(d.color).setOpacity(g).get("rgba"):d.color),l.stroke=c(u.connectorColor,h.connectorColor,d.color));b[p].radius=this.getRangeRadius(u.value);b[p]=y(b[p],{center:b[0].radius-b[p].radius+m});f||y(!0,b[p],{bubbleAttribs:y(e),connectorAttribs:y(l),labelAttribs:A})},this)};b.prototype.getRangeRadius=function(c){var a=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,
c)};b.prototype.render=function(){var c=this.chart.renderer,a=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=c.g("bubble-legend");this.legendItem=c.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(c){c.value>=a&&this.renderRange(c)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};b.prototype.renderRange=
function(c){var a=this.options,b=a.labels,h=this.chart,d=h.series[a.seriesIndex],m=h.renderer,n=this.symbols;h=n.labels;var g=c.center,f=Math.abs(c.radius),u=a.connectorDistance||0,p=b.align,E=a.connectorWidth,v=this.ranges[0].radius||0,C=g-f-a.borderWidth/2+E/2,e=this.fontMetrics;e=e.f/2-(e.h-e.f)/2;var l=m.styledMode;u=this.legend.options.rtl||"left"===p?-u:u;"center"===p&&(u=0,a.connectorDistance=0,c.labelAttribs.align="center");p=C+a.labels.y;var k=v+u+a.labels.x;n.bubbleItems.push(m.circle(v,
g+((C%1?1:.5)-(E%2?0:.5)),f).attr(l?{}:c.bubbleAttribs).addClass((l?"highcharts-color-"+d.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(a.className||"")).add(this.legendSymbol));n.connectors.push(m.path(m.crispLine([["M",v,C],["L",v+u,C]],a.connectorWidth)).attr(l?{}:c.connectorAttribs).addClass((l?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(a.connectorClassName||"")).add(this.legendSymbol));c=m.text(this.formatLabel(c),k,p+e).attr(l?{}:c.labelAttribs).css(l?
{}:b.style).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);h.push(c);c.placed=!0;c.alignAttr={x:k,y:p+e}};b.prototype.getMaxLabelSize=function(){var c,a;this.symbols.labels.forEach(function(b){a=b.getBBox(!0);c=c?a.width>c.width?a:c:a});return c||{}};b.prototype.formatLabel=function(c){var a=this.options,b=a.labels.formatter;a=a.labels.format;var h=this.chart.numberFormatter;return a?d.format(a,c):b?b.call(c):h(c.value,1)};b.prototype.hideOverlappingLabels=
function(){var c=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(c.hideOverlappingLabels(a.labels),a.labels.forEach(function(c,b){c.newOpacity?c.newOpacity!==c.oldOpacity&&a.connectors[b].show():a.connectors[b].hide()}))};b.prototype.getRanges=function(){var a=this.legend.bubbleLegend,b=a.options.ranges,h,d=Number.MAX_VALUE,m=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(h=a.zData.filter(w),h.length&&(d=c(a.options.zMin,Math.min(d,Math.max(l(h),
!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),m=c(a.options.zMax,Math.max(m,q(h)))))});var e=d===m?[{value:m}]:[{value:d},{value:(d+m)/2},{value:m,autoRanges:!0}];b.length&&b[0].radius&&e.reverse();e.forEach(function(c,a){b&&b[a]&&(e[a]=y(b[a],c))});return e};b.prototype.predictBubbleSizes=function(){var c=this.chart,a=this.fontMetrics,b=c.legend.options,h="horizontal"===b.layout,d=h?c.legend.lastLineHeight:0,m=c.plotSizeX,e=c.plotSizeY,g=c.series[this.options.seriesIndex];
c=Math.ceil(g.minPxSize);var f=Math.ceil(g.maxPxSize),u=Math.min(e,m);g=g.options.maxSize;if(b.floating||!/%$/.test(g))a=f;else if(g=parseFloat(g),a=(u+d-a.h/2)*g/100/(g/100+1),h&&e-a>=m||!h&&m-a>=e)a=f;return[c,Math.ceil(a)]};b.prototype.updateRanges=function(c,a){var b=this.legend.options.bubbleLegend;b.minSize=c;b.maxSize=a;b.ranges=this.getRanges()};b.prototype.correctSizes=function(){var c=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&
(this.updateRanges(this.options.minSize,a.maxPxSize),c.render())};return b}()});z(e,"Series/Bubble/BubbleLegendComposition.js",[e["Series/Bubble/BubbleLegendDefaults.js"],e["Series/Bubble/BubbleLegendItem.js"],e["Core/DefaultOptions.js"],e["Core/Utilities.js"]],function(e,d,b,k){var a=b.setOptions,r=k.addEvent,q=k.objectEach,l=k.wrap,w;(function(b){function c(c,a,b){var d=this.legend,g=0<=m(this);if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&g){var f=d.bubbleLegend.options;
g=d.bubbleLegend.predictBubbleSizes();d.bubbleLegend.updateRanges(g[0],g[1]);f.placed||(d.group.placed=!1,d.allItems.forEach(function(f){f.legendGroup.translateY=null}));d.render();this.getMargins();this.axes.forEach(function(c){c.visible&&c.render();f.placed||(c.setScale(),c.updateNames(),q(c.ticks,function(f){f.isNew=!0;f.isNewLabel=!0}))});f.placed=!0;this.getMargins();c.call(this,a,b);d.bubbleLegend.correctSizes();w(d,h(d))}else c.call(this,a,b),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),
w(d,h(d)))}function m(c){c=c.series;for(var a=0;a<c.length;){if(c[a]&&c[a].isBubble&&c[a].visible&&c[a].zData.length)return a;a++}return-1}function h(c){c=c.allItems;var a=[],b=c.length,h,g=0;for(h=0;h<b;h++)if(c[h].legendItemHeight&&(c[h].itemHeight=c[h].legendItemHeight),c[h]===c[b-1]||c[h+1]&&c[h]._legendItemPos[1]!==c[h+1]._legendItemPos[1]){a.push({height:0});var f=a[a.length-1];for(g;g<=h;g++)c[g].itemHeight>f.height&&(f.height=c[g].itemHeight);f.step=h}return a}function n(c){var a=this.bubbleLegend,
b=this.options,h=b.bubbleLegend,g=m(this.chart);a&&a.ranges&&a.ranges.length&&(h.ranges.length&&(h.autoRanges=!!h.ranges[0].autoRanges),this.destroyItem(a));0<=g&&b.enabled&&h.enabled&&(h.seriesIndex=g,this.bubbleLegend=new d(h,this),this.bubbleLegend.addToLegend(c.allItems))}function k(){var c=this.chart,a=this.visible,b=this.chart.legend;b&&b.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,c=0<=m(c),b.bubbleLegend.visible!==c&&(b.update({bubbleLegend:{enabled:c}}),b.bubbleLegend.visible=c),this.visible=
a)}function w(c,a){var b=c.options.rtl,h,g,f,u=0;c.allItems.forEach(function(c,d){h=c.legendGroup.translateX;g=c._legendItemPos[1];if((f=c.movementX)||b&&c.ranges)f=b?h-c.options.maxSize/2:h+f,c.legendGroup.attr({translateX:f});d>a[u].step&&u++;c.legendGroup.attr({translateY:Math.round(g+a[u].height/2)});c._legendItemPos[1]=g+a[u].height/2})}b.compose=function(b,h,d){a({legend:{bubbleLegend:e}});r(h,"afterGetAllItems",n);r(d,"legendItemClick",k);l(b.prototype,"drawChartBox",c)}})(w||(w={}));return w});
z(e,"Series/Bubble/BubblePoint.js",[e["Core/Series/Point.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b){var k=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(b,d)};return function(b,d){function e(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}();b=b.extend;
d=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.options=void 0;b.series=void 0;return b}k(b,a);b.prototype.haloPath=function(a){return e.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)};return b}(d.seriesTypes.scatter.prototype.pointClass);b(d.prototype,{ttBelow:!1});return d});z(e,"Series/Bubble/BubbleSeries.js",[e["Core/Axis/Axis.js"],e["Series/Bubble/BubbleLegendComposition.js"],e["Series/Bubble/BubblePoint.js"],e["Core/Color/Color.js"],
e["Core/Globals.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k,a,r,q,l){var w=this&&this.__extends||function(){var c=function(f,a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,f){c.__proto__=f}||function(c,f){for(var a in f)f.hasOwnProperty(a)&&(c[a]=f[a])};return c(f,a)};return function(f,a){function g(){this.constructor=f}c(f,a);f.prototype=null===a?Object.create(a):(g.prototype=a.prototype,new g)}}(),y=k.parse;
k=a.noop;var c=q.seriesTypes;a=c.column;var m=c.scatter,h=l.arrayMax,n=l.arrayMin,x=l.clamp,B=l.extend,I=l.isNumber,H=l.merge,t=l.pick,A=l.pInt;l=function(c){function f(){var f=null!==c&&c.apply(this,arguments)||this;f.data=void 0;f.maxPxSize=void 0;f.minPxSize=void 0;f.options=void 0;f.points=void 0;f.radii=void 0;f.yData=void 0;f.zData=void 0;return f}w(f,c);f.prototype.animate=function(c){!c&&this.points.length<this.options.animationLimit&&this.points.forEach(function(c){var f=c.graphic;f&&f.width&&
(this.hasRendered||f.attr({x:c.plotX,y:c.plotY,width:1,height:1}),f.animate(this.markerAttribs(c),this.options.animation))},this)};f.prototype.getRadii=function(c,f,a){var g=this.zData,b=this.yData,p=a.minPxSize,h=a.maxPxSize,d=[];var u=0;for(a=g.length;u<a;u++){var m=g[u];d.push(this.getRadius(c,f,p,h,m,b[u]))}this.radii=d};f.prototype.getRadius=function(c,f,a,g,b,h){var p=this.options,d="width"!==p.sizeBy,u=p.zThreshold,v=f-c,m=.5;if(null===h||null===b)return null;if(I(b)){p.sizeByAbsoluteValue&&
(b=Math.abs(b-u),v=Math.max(f-u,Math.abs(c-u)),c=0);if(b<c)return a/2-1;0<v&&(m=(b-c)/v)}d&&0<=m&&(m=Math.sqrt(m));return Math.ceil(a+m*(g-a))/2};f.prototype.hasData=function(){return!!this.processedXData.length};f.prototype.pointAttribs=function(c,f){var a=this.options.marker.fillOpacity;c=r.prototype.pointAttribs.call(this,c,f);1!==a&&(c.fill=y(c.fill).setOpacity(a).get("rgba"));return c};f.prototype.translate=function(){var f,a=this.data,g=this.radii;c.prototype.translate.call(this);for(f=a.length;f--;){var b=
a[f];var h=g?g[f]:0;I(h)&&h>=this.minPxSize/2?(b.marker=B(b.marker,{radius:h,width:2*h,height:2*h}),b.dlBox={x:b.plotX-h,y:b.plotY-h,width:2*h,height:2*h}):b.shapeArgs=b.plotY=b.dlBox=void 0}};f.compose=d.compose;f.defaultOptions=H(m.defaultOptions,{dataLabels:{formatter:function(){var c=this.series.chart.numberFormatter,f=this.point.z;return I(f)?c(f,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},
symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});return f}(m);B(l.prototype,{alignDataLabel:a.prototype.alignDataLabel,applyZones:k,bubblePadding:!0,buildKDTree:k,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:b,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});e.prototype.beforePadding=
function(){var c=this,f=this.len,a=this.chart,b=0,d=f,v=this.isXAxis,m=v?"xData":"yData",e=this.min,k={},l=Math.min(a.plotWidth,a.plotHeight),q=Number.MAX_VALUE,r=-Number.MAX_VALUE,w=this.max-e,y=f/w,B=[];this.series.forEach(function(f){var b=f.options;!f.bubblePadding||!f.visible&&a.options.chart.ignoreHiddenSeries||(c.allowZoomOutside=!0,B.push(f),v&&(["minSize","maxSize"].forEach(function(c){var f=b[c],a=/%$/.test(f);f=A(f);k[c]=a?l*f/100:f}),f.minPxSize=k.minSize,f.maxPxSize=Math.max(k.maxSize,
k.minSize),f=f.zData.filter(I),f.length&&(q=t(b.zMin,x(n(f),!1===b.displayNegative?b.zThreshold:-Number.MAX_VALUE,q)),r=t(b.zMax,Math.max(r,h(f))))))});B.forEach(function(f){var a=f[m],g=a.length;v&&f.getRadii(q,r,f);if(0<w)for(;g--;)if(I(a[g])&&c.dataMin<=a[g]&&a[g]<=c.max){var h=f.radii?f.radii[g]:0;b=Math.min((a[g]-e)*y-h,b);d=Math.max((a[g]-e)*y+h,d)}});B.length&&0<w&&!this.logarithmic&&(d-=f,y*=(f+Math.max(0,b)-Math.min(d,f))/f,[["min","userMin",b],["max","userMax",d]].forEach(function(f){"undefined"===
typeof t(c.options[f[0]],c[f[1]])&&(c[f[0]]+=f[2]/y)}))};q.registerSeriesType("bubble",l);"";"";return l});z(e,"Series/ColumnRange/ColumnRangePoint.js",[e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d){var b=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(b,d)};return function(b,d){function e(){this.constructor=
b}a(b,d);b.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),k=e.seriesTypes;e=k.column.prototype.pointClass;var a=d.extend,r=d.isNumber;d=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.series=void 0;b.options=void 0;b.barX=void 0;b.pointWidth=void 0;b.shapeType=void 0;return b}b(d,a);d.prototype.isValid=function(){return r(this.low)};return d}(k.arearange.prototype.pointClass);a(d.prototype,{setState:e.prototype.setState});return d});z(e,"Series/ColumnRange/ColumnRangeSeries.js",
[e["Series/ColumnRange/ColumnRangePoint.js"],e["Core/Globals.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k){var a=this&&this.__extends||function(){var c=function(a,b){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return c(a,b)};return function(a,b){function h(){this.constructor=a}c(a,b);a.prototype=null===b?Object.create(b):(h.prototype=b.prototype,new h)}}();
d=d.noop;var r=b.seriesTypes,q=r.arearange,l=r.column,w=l.prototype,y=q.prototype,c=k.clamp,m=k.merge,h=k.pick;k=k.extend;var n={pointRange:null,marker:null,states:{hover:{halo:!1}}};r=function(b){function d(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.points=void 0;c.options=void 0;return c}a(d,b);d.prototype.setOptions=function(){m(!0,arguments[0],{stacking:void 0});return y.setOptions.apply(this,arguments)};d.prototype.translate=function(){var a=this,b=a.yAxis,d=a.xAxis,m=d.startAngleRad,
g,f=a.chart,u=a.xAxis.isRadial,p=Math.max(f.chartWidth,f.chartHeight)+999,e;w.translate.apply(a);a.points.forEach(function(v){var E=v.shapeArgs||{},n=a.options.minPointLength;v.plotHigh=e=c(b.translate(v.high,0,1,0,1),-p,p);v.plotLow=c(v.plotY,-p,p);var k=e;var l=h(v.rectPlotY,v.plotY)-e;Math.abs(l)<n?(n-=l,l+=n,k-=n/2):0>l&&(l*=-1,k-=l);u?(g=v.barX+m,v.shapeType="arc",v.shapeArgs=a.polarArc(k+l,k,g,g+v.pointWidth)):(E.height=l,E.y=k,n=E.x,n=void 0===n?0:n,E=E.width,E=void 0===E?0:E,v.tooltipPos=
f.inverted?[b.len+b.pos-f.plotLeft-k-l/2,d.len+d.pos-f.plotTop-n-E/2,l]:[d.left-f.plotLeft+n+E/2,b.pos-f.plotTop+k+l/2,l])})};d.prototype.crispCol=function(){return w.crispCol.apply(this,arguments)};d.prototype.drawPoints=function(){return w.drawPoints.apply(this,arguments)};d.prototype.drawTracker=function(){return w.drawTracker.apply(this,arguments)};d.prototype.getColumnMetrics=function(){return w.getColumnMetrics.apply(this,arguments)};d.prototype.pointAttribs=function(){return w.pointAttribs.apply(this,
arguments)};d.prototype.adjustForMissingColumns=function(){return w.adjustForMissingColumns.apply(this,arguments)};d.prototype.animate=function(){return w.animate.apply(this,arguments)};d.prototype.translate3dPoints=function(){return w.translate3dPoints.apply(this,arguments)};d.prototype.translate3dShapes=function(){return w.translate3dShapes.apply(this,arguments)};d.defaultOptions=m(l.defaultOptions,q.defaultOptions,n);return d}(q);k(r.prototype,{directTouch:!0,trackerGroups:["group","dataLabelsGroup"],
drawGraph:d,getSymbol:d,polarArc:function(){return w.polarArc.apply(this,arguments)},pointClass:e});b.registerSeriesType("columnrange",r);"";return r});z(e,"Series/ColumnPyramid/ColumnPyramidSeries.js",[e["Series/Column/ColumnSeries.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b){var k=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&
(c[b]=a[b])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),a=e.prototype,r=b.clamp,q=b.merge,l=b.pick;b=function(b){function d(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}k(d,b);d.prototype.translate=function(){var c=this,b=c.chart,d=c.options,e=c.dense=2>c.closestPointRange*c.xAxis.transA;e=c.borderWidth=l(d.borderWidth,e?0:1);var k=c.yAxis,
q=d.threshold,y=c.translatedThreshold=k.getThreshold(q),w=l(d.minPointLength,5),t=c.getColumnMetrics(),A=t.width,g=c.barW=Math.max(A,1+2*e),f=c.pointXOffset=t.offset;b.inverted&&(y-=.5);d.pointPadding&&(g=Math.ceil(g));a.translate.apply(c);c.points.forEach(function(a){var h=l(a.yBottom,y),u=999+Math.abs(h),v=r(a.plotY,-u,k.len+u);u=a.plotX+f;var e=g/2,m=Math.min(v,h);h=Math.max(v,h)-m;var n;a.barX=u;a.pointWidth=A;a.tooltipPos=b.inverted?[k.len+k.pos-b.plotLeft-v,c.xAxis.len-u-e,h]:[u+e,v+k.pos-b.plotTop,
h];v=q+(a.total||a.y);"percent"===d.stacking&&(v=q+(0>a.y)?-100:100);v=k.toPixels(v,!0);var t=(n=b.plotHeight-v-(b.plotHeight-y))?e*(m-v)/n:0;var x=n?e*(m+h-v)/n:0;n=u-t+e;t=u+t+e;var L=u+x+e;x=u-x+e;var M=m-w;var D=m+h;0>a.y&&(M=m,D=m+h+w);b.inverted&&(L=b.plotWidth-m,n=v-(b.plotWidth-y),t=e*(v-L)/n,x=e*(v-(L-h))/n,n=u+e+t,t=n-2*t,L=u-x+e,x=u+x+e,M=m,D=m+h-w,0>a.y&&(D=m+h+w));a.shapeType="path";a.shapeArgs={x:n,y:M,width:t-n,height:h,d:[["M",n,M],["L",t,M],["L",L,D],["L",x,D],["Z"]]}})};d.defaultOptions=
q(e.defaultOptions,{});return d}(e);d.registerSeriesType("columnpyramid",b);"";return b});z(e,"Series/ErrorBar/ErrorBarSeries.js",[e["Series/BoxPlot/BoxPlotSeries.js"],e["Series/Column/ColumnSeries.js"],e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k,a){var r=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&
(c[b]=a[b])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}(),q=k.seriesTypes.arearange,l=a.merge;a=a.extend;var w=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}r(c,a);c.prototype.getColumnMetrics=function(){return this.linkedParent&&this.linkedParent.columnMetrics||d.prototype.getColumnMetrics.call(this)};c.prototype.drawDataLabels=
function(){var c=this.pointValKey;q&&(q.prototype.drawDataLabels.call(this),this.data.forEach(function(a){a.y=a[c]}))};c.prototype.toYData=function(c){return[c.low,c.high]};c.defaultOptions=l(e.defaultOptions,{color:b.neutralColor100,grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null});return c}(e);a(w.prototype,{pointArrayMap:["low","high"],pointValKey:"high",doQuartiles:!1});
k.registerSeriesType("errorbar",w);"";return w});z(e,"Series/Gauge/GaugePoint.js",[e["Core/Series/SeriesRegistry.js"]],function(e){var d=this&&this.__extends||function(){var b=function(d,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return b(d,a)};return function(d,a){function e(){this.constructor=d}b(d,a);d.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)}}();return function(b){function e(){var a=
null!==b&&b.apply(this,arguments)||this;a.options=void 0;a.series=void 0;a.shapeArgs=void 0;return a}d(e,b);e.prototype.setState=function(a){this.state=a};return e}(e.series.prototype.pointClass)});z(e,"Series/Gauge/GaugeSeries.js",[e["Series/Gauge/GaugePoint.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k,a){var r=this&&this.__extends||function(){var c=function(a,b){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return c(a,b)};return function(a,b){function d(){this.constructor=a}c(a,b);a.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}();d=d.noop;var q=k.series,l=k.seriesTypes.column,w=a.clamp,y=a.isNumber,c=a.extend,m=a.merge,h=a.pick,n=a.pInt;a=function(c){function a(){var a=null!==c&&c.apply(this,arguments)||this;a.data=void 0;a.points=void 0;a.options=void 0;a.yAxis=void 0;return a}r(a,c);
a.prototype.translate=function(){var c=this.yAxis,a=this.options,b=c.center;this.generatePoints();this.points.forEach(function(d){var g=m(a.dial,d.dial),f=n(h(g.radius,"80%"))*b[2]/200,u=n(h(g.baseLength,"70%"))*f/100,p=n(h(g.rearLength,"10%"))*f/100,e=g.baseWidth||3,v=g.topWidth||1,k=a.overshoot,l=c.startAngleRad+c.translate(d.y,null,null,null,!0);if(y(k)||!1===a.wrap)k=y(k)?k/180*Math.PI:0,l=w(l,c.startAngleRad-k,c.endAngleRad+k);l=180*l/Math.PI;d.shapeType="path";d.shapeArgs={d:g.path||[["M",-p,
-e/2],["L",u,-e/2],["L",f,-v/2],["L",f,v/2],["L",u,e/2],["L",-p,e/2],["Z"]],translateX:b[0],translateY:b[1],rotation:l};d.plotX=b[0];d.plotY=b[1]})};a.prototype.drawPoints=function(){var c=this,a=c.chart,d=c.yAxis.center,e=c.pivot,g=c.options,f=g.pivot,u=a.renderer;c.points.forEach(function(f){var d=f.graphic,h=f.shapeArgs,p=h.d,e=m(g.dial,f.dial);d?(d.animate(h),h.d=p):f.graphic=u[f.shapeType](h).attr({rotation:h.rotation,zIndex:1}).addClass("highcharts-dial").add(c.group);if(!a.styledMode)f.graphic[d?
"animate":"attr"]({stroke:e.borderColor||"none","stroke-width":e.borderWidth||0,fill:e.backgroundColor||b.neutralColor100})});e?e.animate({translateX:d[0],translateY:d[1]}):(c.pivot=u.circle(0,0,h(f.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(d[0],d[1]).add(c.group),a.styledMode||c.pivot.attr({"stroke-width":f.borderWidth||0,stroke:f.borderColor||b.neutralColor20,fill:f.backgroundColor||b.neutralColor100}))};a.prototype.animate=function(c){var a=this;c||a.points.forEach(function(c){var b=
c.graphic;b&&(b.attr({rotation:180*a.yAxis.startAngleRad/Math.PI}),b.animate({rotation:c.shapeArgs.rotation},a.options.animation))})};a.prototype.render=function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);q.prototype.render.call(this);this.group.clip(this.chart.clipRect)};a.prototype.setData=function(c,a){q.prototype.setData.call(this,c,!1);this.processData();this.generatePoints();h(a,!0)&&this.chart.redraw()};a.prototype.hasData=
function(){return!!this.points.length};a.defaultOptions=m(q.defaultOptions,{dataLabels:{borderColor:b.neutralColor20,borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1});return a}(q);c(a.prototype,{angular:!0,directTouch:!0,drawGraph:d,drawTracker:l.prototype.drawTracker,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,pointClass:e,trackerGroups:["group","dataLabelsGroup"]});k.registerSeriesType("gauge",a);
"";return a});z(e,"Series/PackedBubble/PackedBubblePoint.js",[e["Core/Chart/Chart.js"],e["Core/Series/Point.js"],e["Core/Series/SeriesRegistry.js"]],function(e,d,b){var k=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};return a(b,d)};return function(b,d){function e(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(e.prototype=d.prototype,
new e)}}();return function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.degree=NaN;b.mass=NaN;b.radius=NaN;b.options=void 0;b.series=void 0;b.value=null;return b}k(b,a);b.prototype.destroy=function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return d.prototype.destroy.apply(this,arguments)};b.prototype.firePointEvent=function(){var a=this.series.options;if(this.isParentNode&&a.parentNode){var b=a.allowPointSelect;a.allowPointSelect=
a.parentNode.allowPointSelect;d.prototype.firePointEvent.apply(this,arguments);a.allowPointSelect=b}else d.prototype.firePointEvent.apply(this,arguments)};b.prototype.select=function(){var a=this.series.chart;this.isParentNode?(a.getSelectedPoints=a.getSelectedParentNodes,d.prototype.select.apply(this,arguments),a.getSelectedPoints=e.prototype.getSelectedPoints):d.prototype.select.apply(this,arguments)};return b}(b.seriesTypes.bubble.prototype.pointClass)});z(e,"Series/Networkgraph/DraggableNodes.js",
[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,b){var k=b.addEvent;d.dragNodesMixin={onMouseDown:function(a,b){b=this.chart.pointer.normalize(b);a.fixedPosition={chartX:b.chartX,chartY:b.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,b){if(a.fixedPosition&&a.inDragMode){var d=this.chart,e=d.pointer.normalize(b);b=a.fixedPosition.chartX-e.chartX;e=a.fixedPosition.chartY-e.chartY;var k=void 0,r=void 0,c=d.graphLayoutsLookup;if(5<Math.abs(b)||
5<Math.abs(e))k=a.fixedPosition.plotX-b,r=a.fixedPosition.plotY-e,d.isInsidePlot(k,r)&&(a.plotX=k,a.plotY=r,a.hasDragged=!0,this.redrawHalo(a),c.forEach(function(a){a.restartSimulation()}))}},onMouseUp:function(a,b){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};
k(e,"load",function(){var a=this,b,d,e;a.container&&(b=k(a.container,"mousedown",function(b){var l=a.hoverPoint;l&&l.series&&l.series.hasDraggableNodes&&l.series.options.draggable&&(l.series.onMouseDown(l,b),d=k(a.container,"mousemove",function(a){return l&&l.series&&l.series.onMouseMove(l,a)}),e=k(a.container.ownerDocument,"mouseup",function(a){d();e();return l&&l.series&&l.series.onMouseUp(l,a)}))}));k(a,"destroy",function(){b()})})});z(e,"Series/Networkgraph/Integrations.js",[e["Core/Globals.js"]],
function(e){e.networkgraphIntegrations={verlet:{attractiveForceFunction:function(d,b){return(b-d)/d},repulsiveForceFunction:function(d,b){return(b-d)/d*(b>d?1:0)},barycenter:function(){var d=this.options.gravitationalConstant,b=this.barycenter.xFactor,e=this.barycenter.yFactor;b=(b-(this.box.left+this.box.width)/2)*d;e=(e-(this.box.top+this.box.height)/2)*d;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=b/a.mass/a.degree,a.plotY-=e/a.mass/a.degree)})},repulsive:function(d,b,e){b=b*this.diffTemperature/
d.mass/d.degree;d.fixedPosition||(d.plotX+=e.x*b,d.plotY+=e.y*b)},attractive:function(d,b,e){var a=d.getMass(),k=-e.x*b*this.diffTemperature;b=-e.y*b*this.diffTemperature;d.fromNode.fixedPosition||(d.fromNode.plotX-=k*a.fromNode/d.fromNode.degree,d.fromNode.plotY-=b*a.fromNode/d.fromNode.degree);d.toNode.fixedPosition||(d.toNode.plotX+=k*a.toNode/d.toNode.degree,d.toNode.plotY+=b*a.toNode/d.toNode.degree)},integrate:function(d,b){var e=-d.options.friction,a=d.options.maxSpeed,r=(b.plotX+b.dispX-b.prevX)*
e;e*=b.plotY+b.dispY-b.prevY;var q=Math.abs,l=q(r)/(r||1);q=q(e)/(e||1);r=l*Math.min(a,Math.abs(r));e=q*Math.min(a,Math.abs(e));b.prevX=b.plotX+b.dispX;b.prevY=b.plotY+b.dispY;b.plotX+=r;b.plotY+=e;b.temperature=d.vectorLength({x:r,y:e})},getK:function(d){return Math.pow(d.box.width*d.box.height/d.nodes.length,.5)}},euler:{attractiveForceFunction:function(d,b){return d*d/b},repulsiveForceFunction:function(d,b){return b*b/d},barycenter:function(){var d=this.options.gravitationalConstant,b=this.barycenter.xFactor,
e=this.barycenter.yFactor;this.nodes.forEach(function(a){if(!a.fixedPosition){var k=a.getDegree();k*=1+k/2;a.dispX+=(b-a.plotX)*d*k/a.degree;a.dispY+=(e-a.plotY)*d*k/a.degree}})},repulsive:function(d,b,e,a){d.dispX+=e.x/a*b/d.degree;d.dispY+=e.y/a*b/d.degree},attractive:function(d,b,e,a){var k=d.getMass(),q=e.x/a*b;b*=e.y/a;d.fromNode.fixedPosition||(d.fromNode.dispX-=q*k.fromNode/d.fromNode.degree,d.fromNode.dispY-=b*k.fromNode/d.fromNode.degree);d.toNode.fixedPosition||(d.toNode.dispX+=q*k.toNode/
d.toNode.degree,d.toNode.dispY+=b*k.toNode/d.toNode.degree)},integrate:function(d,b){b.dispX+=b.dispX*d.options.friction;b.dispY+=b.dispY*d.options.friction;var e=b.temperature=d.vectorLength({x:b.dispX,y:b.dispY});0!==e&&(b.plotX+=b.dispX/e*Math.min(Math.abs(b.dispX),d.temperature),b.plotY+=b.dispY/e*Math.min(Math.abs(b.dispY),d.temperature))},getK:function(d){return Math.pow(d.box.width*d.box.height/d.nodes.length,.3)}}}});z(e,"Series/Networkgraph/QuadTree.js",[e["Core/Globals.js"],e["Core/Utilities.js"]],
function(e,d){d=d.extend;var b=e.QuadTreeNode=function(b){this.box=b;this.boxSize=Math.min(b.width,b.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};d(b.prototype,{insert:function(d,a){this.isInternal?this.nodes[this.getBoxPosition(d)].insert(d,a-1):(this.isEmpty=!1,this.body?a?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,a-1),this.body=!0),this.nodes[this.getBoxPosition(d)].insert(d,a-1)):(a=new b({top:d.plotX,
left:d.plotY,width:.1,height:.1}),a.body=d,a.isInternal=!1,this.nodes.push(a)):(this.isInternal=!1,this.body=d))},updateMassAndCenter:function(){var b=0,a=0,d=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||(b+=e.mass,a+=e.plotX*e.mass,d+=e.plotY*e.mass)}),a/=b,d/=b):this.body&&(b=this.body.mass,a=this.body.plotX,d=this.body.plotY);this.mass=b;this.plotX=a;this.plotY=d},divideBox:function(){var d=this.box.width/2,a=this.box.height/2;this.nodes[0]=new b({left:this.box.left,top:this.box.top,
width:d,height:a});this.nodes[1]=new b({left:this.box.left+d,top:this.box.top,width:d,height:a});this.nodes[2]=new b({left:this.box.left+d,top:this.box.top+a,width:d,height:a});this.nodes[3]=new b({left:this.box.left,top:this.box.top+a,width:d,height:a})},getBoxPosition:function(b){var a=b.plotY<this.box.top+this.box.height/2;return b.plotX<this.box.left+this.box.width/2?a?0:3:a?1:2}});e=e.QuadTree=function(d,a,e,q){this.box={left:d,top:a,width:e,height:q};this.maxDepth=25;this.root=new b(this.box,
"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};d(e.prototype,{insertNodes:function(b){b.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(b,a,d){var e;b||(b=this.root);b===this.root&&a&&(e=a(b));!1!==e&&(b.nodes.forEach(function(b){if(b.isInternal){a&&(e=a(b));if(!1===e)return;this.visitNodeRecursive(b,a,d)}else b.body&&a&&a(b.body);d&&d(b)},this),b===this.root&&d&&d(b))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,
null,function(b){b.updateMassAndCenter()})}})});z(e,"Series/Networkgraph/Layouts.js",[e["Core/Chart/Chart.js"],e["Core/Animation/AnimationUtilities.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,b,k){var a=d.setAnimation;d=k.addEvent;var r=k.clamp,q=k.defined,l=k.extend,w=k.isFunction,y=k.pick;b.layouts={"reingold-fruchterman":function(){}};l(b.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,
height:0};this.setInitialRendering(!0);this.integration=b.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=y(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=y(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=y(a,this.options.enableSimulation)},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=
a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(b);this.enableSimulation&&this.step()},step:function(){var a=this,d=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(c){a[c+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,
a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(d.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&b.win.cancelAnimationFrame(a.simulation),a.simulation=b.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&b.win.cancelAnimationFrame(this.simulation)},setArea:function(a,b,d,e){this.box={left:a,
top:b,width:d,height:e}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},
restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(a){this.maxIterations=y(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},
setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new b.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;w(a)?(a.call(this),this.nodes.forEach(function(a){q(a.prevX)||(a.prevX=a.plotX);q(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(c){c.linksFrom.forEach(function(c){q[c.toNode.id]||
(q[c.toNode.id]=!0,k.push(c.toNode),a(c.toNode))})}var b=this.box,d=this.nodes,e=2*Math.PI/(d.length+1),l=d.filter(function(a){return 0===a.linksTo.length}),k=[],q={},w=this.options.initialPositionRadius;l.forEach(function(c){k.push(c);a(c)});k.length?d.forEach(function(a){-1===k.indexOf(a)&&k.push(a)}):k=d;k.forEach(function(a,c){a.plotX=a.prevX=y(a.plotX,b.width/2+w*Math.cos(c*e));a.plotY=a.prevY=y(a.plotY,b.height/2+w*Math.sin(c*e));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=
a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,d=this.nodes,e=d.length+1;d.forEach(function(c,d){c.plotX=c.prevX=y(c.plotX,b.width*a(d));c.plotY=c.prevY=y(c.plotY,b.height*a(e+d));c.dispX=0;c.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=0,b=0,d=0;this.nodes.forEach(function(c){b+=c.plotX*c.mass;d+=c.plotY*c.mass;a+=c.mass});return this.barycenter=
{x:b,y:d,xFactor:b/a,yFactor:d/a}},barnesHutApproximation:function(a,b){var c=this.getDistXY(a,b),d=this.vectorLength(c);if(a!==b&&0!==d)if(b.isInternal)if(b.boxSize/d<this.options.theta&&0!==d){var e=this.repulsiveForce(d,this.k);this.force("repulsive",a,e*b.mass,c,d);var m=!1}else m=!0;else e=this.repulsiveForce(d,this.k),this.force("repulsive",a,e*b.mass,c,d);return m},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(c){a.quadTree.visitNodeRecursive(null,
function(b){return a.barnesHutApproximation(c,b)})}):a.nodes.forEach(function(c){a.nodes.forEach(function(b){if(c!==b&&!c.fixedPosition){var d=a.getDistXY(c,b);var e=a.vectorLength(d);if(0!==e){var h=a.repulsiveForce(e,a.k);a.force("repulsive",c,h*b.mass,d,e)}}})})},attractiveForces:function(){var a=this,b,d,e;a.links.forEach(function(c){c.fromNode&&c.toNode&&(b=a.getDistXY(c.fromNode,c.toNode),d=a.vectorLength(b),0!==d&&(e=a.attractiveForce(d,a.k),a.force("attractive",c,e,b,d)))})},applyLimits:function(){var a=
this;a.nodes.forEach(function(c){c.fixedPosition||(a.integration.integrate(a,c),a.applyLimitBox(c,a.box),c.dispX=0,c.dispY=0)})},applyLimitBox:function(a,b){var c=a.radius;a.plotX=r(a.plotX,b.left+c,b.width-c);a.plotY=r(a.plotY,b.top+c,b.height-c)},coolDown:function(a,b,d){return a-b*d},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},
vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});d(e,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});d(e,"render",function(){function b(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),
a.step(),e=!1,d=!0)}var d=!1;if(this.graphLayoutsLookup){a(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!e;){var e=!0;this.graphLayoutsLookup.forEach(b)}d&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});d(e,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),this.redraw())});d(e,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});
this.redraw()})});z(e,"Series/PackedBubble/PackedBubbleComposition.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,d,b){var k=d.layouts["reingold-fruchterman"],a=b.addEvent,r=b.extendClass,q=b.pick;e.prototype.getSelectedParentNodes=function(){var a=[];this.series.forEach(function(b){b.parentNode&&b.parentNode.selected&&a.push(b.parentNode)});return a};d.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,b,d,c){return Math.min(a,(d.marker.radius+
c.marker.radius)/2)},barycenter:function(){var a=this,b=a.options.gravitationalConstant,d=a.box,c=a.nodes,e,h;c.forEach(function(l){a.options.splitSeries&&!l.isParentNode?(e=l.series.parentNode.plotX,h=l.series.parentNode.plotY):(e=d.width/2,h=d.height/2);l.fixedPosition||(l.plotX-=(l.plotX-e)*b/(l.mass*Math.sqrt(c.length)),l.plotY-=(l.plotY-h)*b/(l.mass*Math.sqrt(c.length)))})},repulsive:function(a,b,d,c){var e=b*this.diffTemperature/a.mass/a.degree;b=d.x*e;d=d.y*e;a.fixedPosition||(a.plotX+=b,a.plotY+=
d);c.fixedPosition||(c.plotX-=b,c.plotY-=d)},integrate:d.networkgraphIntegrations.verlet.integrate,getK:d.noop};d.layouts.packedbubble=r(k,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},isStable:function(){var a=Math.abs(this.prevSystemTemperature-this.systemTemperature);return 1>Math.abs(10*this.systemTemperature/Math.sqrt(this.nodes.length))&&.00001>a||0>=this.temperature},setCircularPositions:function(){var a=this,b=a.box,d=a.nodes,c=
2*Math.PI/(d.length+1),e,h,k=a.options.initialPositionRadius;d.forEach(function(d,l){a.options.splitSeries&&!d.isParentNode?(e=d.series.parentNode.plotX,h=d.series.parentNode.plotY):(e=b.width/2,h=b.height/2);d.plotX=d.prevX=q(d.plotX,e+k*Math.cos(d.index||l*c));d.plotY=d.prevY=q(d.plotY,h+k*Math.sin(d.index||l*c));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,b,d,c,e=a.options.bubblePadding;a.nodes.forEach(function(h){h.degree=h.mass;h.neighbours=0;a.nodes.forEach(function(l){b=0;
h===l||h.fixedPosition||!a.options.seriesInteraction&&h.series!==l.series||(c=a.getDistXY(h,l),d=a.vectorLength(c)-(h.marker.radius+l.marker.radius+e),0>d&&(h.degree+=.01,h.neighbours++,b=a.repulsiveForce(-d/Math.sqrt(h.neighbours),a.k,h,l)),a.force("repulsive",h,b*l.mass,c,l,d))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var b=this.getDistXY(a,a.series.parentNode);var d=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(b);
0>d&&d>-2*a.marker.radius&&(a.plotX-=.01*b.x,a.plotY-=.01*b.y)}k.prototype.applyLimitBox.apply(this,arguments)}});a(e,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints})});z(e,"Series/PackedBubble/PackedBubbleSeries.js",[e["Core/Color/Color.js"],e["Core/Globals.js"],e["Series/PackedBubble/PackedBubblePoint.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k,a){var r=this&&this.__extends||function(){var a=function(b,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,b){a.__proto__=b}||function(a,b){for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f])};return a(b,f)};return function(b,f){function c(){this.constructor=b}a(b,f);b.prototype=null===f?Object.create(f):(c.prototype=f.prototype,new c)}}(),q=e.parse,l=k.series,w=k.seriesTypes.bubble,y=a.addEvent,c=a.clamp,m=a.defined,h=a.extend,n=a.fireEvent,x=a.isArray,B=a.isNumber,z=a.merge,H=a.pick,t=d.dragNodesMixin;e=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;
b.data=void 0;b.layout=void 0;b.options=void 0;b.points=void 0;b.xData=void 0;return b}r(b,a);b.prototype.accumulateAllPoints=function(a){var b=a.chart,f=[],c,d;for(c=0;c<b.series.length;c++)if(a=b.series[c],a.is("packedbubble")&&a.visible||!b.options.chart.ignoreHiddenSeries)for(d=0;d<a.yData.length;d++)f.push([null,null,a.yData[d],a.index,d,{id:d,marker:{radius:0}}]);return f};b.prototype.addLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,
e=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=c=[]);var g=b[a.type];g||(a.enableSimulation=m(e.forExport)?!e.forExport:a.enableSimulation,b[a.type]=g=new d.layouts[a.type],g.init(a),c.splice(g.index,0,g));this.layout=g;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});g.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);g.addElementsToCollection([this],g.series);g.addElementsToCollection(this.points,g.nodes)};b.prototype.addSeriesLayout=
function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,e=z(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var g=b[a.type+"-series"];g||(b[a.type+"-series"]=g=new d.layouts[a.type],g.init(e),c.splice(g.index,0,g));this.parentNodeLayout=g;this.createParentNodes()};b.prototype.calculateParentRadius=function(){var a=this.seriesBox();this.parentNodeRadius=c(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,
2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)};b.prototype.calculateZExtremes=function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,d=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){m(a)&&(a>d&&(d=a),a<c&&(c=a))})});a=H(a,c);b=H(b,d);return[a,b]};b.prototype.checkOverlap=function(a,b){var c=a[0]-b[0],f=a[1]-b[1];
return-.001>Math.sqrt(c*c+f*f)-Math.abs(a[2]+b[2])};b.prototype.createParentNodes=function(){var a=this,b=a.chart,c=a.parentNodeLayout,d,e=a.parentNode,g=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===a.index&&(d=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);d||(e||(e=(new g).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},
dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,c.addElementsToCollection([a],c.series),c.addElementsToCollection([e],c.nodes))};b.prototype.deferLayout=function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())};b.prototype.destroy=function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,
a.series)},this);this.parentNode&&this.parentNodeLayout&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));l.prototype.destroy.apply(this,arguments)};b.prototype.drawDataLabels=function(){var a=this.options.dataLabels.textPath,b=this.points;l.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],
this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,l.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)};b.prototype.drawGraph=function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart;var b=this.layout.options.parentNodeOptions.marker;var c={fill:b.fillColor||q(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};this.parentNodesGroup||(this.parentNodesGroup=
this.plotGroup("parentNodesGroup","parentNode",this.visible?"inherit":"hidden",.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();b=z({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},c);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(c.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(b)}};b.prototype.drawTracker=function(){var b=
this.parentNode;a.prototype.drawTracker.call(this);if(b){var c=x(b.dataLabels)?b.dataLabels:b.dataLabel?[b.dataLabel]:[];b.graphic&&(b.graphic.element.point=b);c.forEach(function(a){a.div?a.div.point=b:a.element.point=b})}};b.prototype.getPointRadius=function(){var a=this,b=a.chart,d=a.options,e=d.useSimulation,g=Math.min(b.plotWidth,b.plotHeight),h={},l=[],k=b.allDataPoints,m,n,q,A;["minSize","maxSize"].forEach(function(a){var b=parseInt(d[a],10),c=/%$/.test(d[a]);h[a]=c?g*b/100:b*Math.sqrt(k.length)});
b.minRadius=m=h.minSize/Math.sqrt(k.length);b.maxRadius=n=h.maxSize/Math.sqrt(k.length);var t=e?a.calculateZExtremes():[m,n];(k||[]).forEach(function(b,f){q=e?c(b[2],t[0],t[1]):b[2];A=a.getRadius(t[0],t[1],m,n,q);0===A&&(A=null);k[f][2]=A;l.push(A)});a.radii=l};b.prototype.init=function(){l.prototype.init.apply(this,arguments);this.eventsToUnbind.push(y(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)}));return this};b.prototype.onMouseUp=
function(a){if(a.fixedPosition&&!a.removed){var b,c,f=this.layout,d=this.parentNodeLayout;d&&f.options.dragBetweenSeries&&d.nodes.forEach(function(d){a&&a.marker&&d!==a.series.parentNode&&(b=f.getDistXY(a,d),c=f.vectorLength(b)-d.marker.radius-a.marker.radius,0>c&&(d.series.addPoint(z(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),f.removeElementFromCollection(a,f.nodes),a.remove()))});t.onMouseUp.apply(this,arguments)}};b.prototype.placeBubbles=function(a){var b=this.checkOverlap,c=this.positionBubble,
f=[],d=1,e=0,g=0;var h=[];var k;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){f.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(f.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),k=2;k<a.length;k++)a[k][2]=a[k][2]||1,h=c(f[d][e],f[d-1][g],a[k]),b(h,f[d][0])?(f.push([]),g=0,f[d+1].push(c(f[d][e],f[d][0],a[k])),d++,e=0):1<d&&f[d-1][g+1]&&b(h,f[d-1][g+1])?(g++,f[d].push(c(f[d][e],f[d-1][g],a[k])),e++):(e++,f[d].push(h));this.chart.stages=f;this.chart.rawPositions=[].concat.apply([],
f);this.resizeRadius();h=this.chart.rawPositions}return h};b.prototype.positionBubble=function(a,b,c){var f=Math.sqrt,d=Math.asin,e=Math.acos,g=Math.pow,h=Math.abs;f=f(g(a[0]-b[0],2)+g(a[1]-b[1],2));e=e((g(f,2)+g(c[2]+b[2],2)-g(c[2]+a[2],2))/(2*(c[2]+b[2])*f));d=d(h(a[0]-b[0])/f);a=(0>a[1]-b[1]?0:Math.PI)+e+d*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]};b.prototype.render=function(){var a=[];l.prototype.render.apply(this,arguments);
this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){x(b.dataLabels)&&b.dataLabels.forEach(function(b){a.push(b)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))};b.prototype.resizeRadius=function(){var a=this.chart,b=a.rawPositions,c=Math.min,d=Math.max,e=a.plotLeft,g=a.plotTop,h=a.plotHeight,k=a.plotWidth,l,m,n;var q=l=Number.POSITIVE_INFINITY;var A=m=Number.NEGATIVE_INFINITY;for(n=0;n<b.length;n++){var t=b[n][2];q=c(q,b[n][0]-t);A=d(A,b[n][0]+t);l=c(l,b[n][1]-
t);m=d(m,b[n][1]+t)}n=[A-q,m-l];c=c.apply([],[(k-e)/n[0],(h-g)/n[1]]);if(1e-10<Math.abs(c-1)){for(n=0;n<b.length;n++)b[n][2]*=c;this.placeBubbles(b)}else a.diffY=h/2+g-l-(m-l)/2,a.diffX=k/2+e-q-(A-q)/2};b.prototype.seriesBox=function(){var a=this.chart,b=Math.max,c=Math.min,d,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){m(a.plotX)&&m(a.plotY)&&a.marker.radius&&(d=a.marker.radius,e[0]=c(e[0],a.plotX-d),e[1]=b(e[1],a.plotX+d),e[2]=c(e[2],a.plotY-
d),e[3]=b(e[3],a.plotY+d))});return B(e.width/e.height)?e:null};b.prototype.setVisible=function(){var a=this;l.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,
a.layout.nodes)}))};b.prototype.translate=function(){var a=this.chart,b=this.data,c=this.index,d,e=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();m(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(e)var g=a.allDataPoints;else g=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(d=0;d<g.length;d++)if(g[d][3]===c){var k=b[g[d][4]];var l=H(g[d][2],void 0);e||(k.plotX=g[d][0]-a.plotLeft+a.diffX,k.plotY=g[d][1]-a.plotTop+
a.diffY);B(l)&&(k.marker=h(k.marker,{radius:l,width:2*l,height:2*l}),k.radius=l)}e&&this.deferLayout();n(this,"afterTranslate")};b.defaultOptions=z(w.defaultOptions,{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return B(b)?a(b,-1):""},parentNodeFormatter:function(){return this.name},
parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,
splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}});return b}(w);h(e.prototype,{alignDataLabel:l.prototype.alignDataLabel,axisTypes:[],directTouch:!0,forces:["barycenter","repulsive"],hasDraggableNodes:!0,isCartesian:!1,noSharedTooltip:!0,onMouseDown:t.onMouseDown,onMouseMove:t.onMouseMove,pointArrayMap:["value"],pointClass:b,pointValKey:"value",redrawHalo:t.redrawHalo,requireSorting:!1,searchPoint:d.noop,trackerGroups:["group","dataLabelsGroup","parentNodesGroup"]});k.registerSeriesType("packedbubble",
e);"";"";return e});z(e,"Series/Polygon/PolygonSeries.js",[e["Core/Globals.js"],e["Mixins/LegendSymbol.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,d,b,k){var a=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):
(d.prototype=c.prototype,new d)}}();e=e.noop;var r=b.series,q=b.seriesTypes,l=q.area,w=q.line,y=q.scatter;q=k.extend;var c=k.merge;k=function(b){function d(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}a(d,b);d.prototype.getGraphPath=function(){for(var a=w.prototype.getGraphPath.call(this),b=a.length+1;b--;)(b===a.length||"M"===a[b][0])&&0<b&&a.splice(b,0,["Z"]);return this.areaPath=a};d.prototype.drawGraph=function(){this.options.fillColor=
this.color;l.prototype.drawGraph.call(this)};d.defaultOptions=c(y.defaultOptions,{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0});return d}(y);q(k.prototype,{type:"polygon",drawLegendSymbol:d.drawRectangle,drawTracker:r.prototype.drawTracker,setStackedPoints:e});b.registerSeriesType("polygon",k);"";return k});z(e,"Core/Axis/WaterfallAxis.js",[e["Extensions/Stacking.js"],e["Core/Utilities.js"]],function(e,d){var b=d.addEvent,
k=d.objectEach,a;(function(a){function d(){var a=this.waterfall.stacks;a&&(a.changed=!1,delete a.alreadyChanged)}function l(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function w(){for(var a=this.axes,b=this.series,c=b.length;c--;)b[c].options.stacking&&(a.forEach(function(a){a.isXAxis||(a.waterfall.stacks.changed=!0)}),c=0)}function r(){this.waterfall||(this.waterfall=new c(this))}var c=function(){function a(a){this.axis=a;this.stacks=
{changed:!1}}a.prototype.renderStackTotals=function(){var a=this.axis,b=a.waterfall.stacks,c=a.stacking&&a.stacking.stackTotalGroup,d=new e(a,a.options.stackLabels,!1,0,void 0);this.dummyStackItem=d;k(b,function(a){k(a,function(a){d.total=a.stackTotal;a.label&&(d.label=a.label);e.prototype.render.call(d,c);a.label=d.label;delete d.label})});d.total=null};return a}();a.Composition=c;a.compose=function(a,c){b(a,"init",r);b(a,"afterBuildStacks",d);b(a,"afterRender",l);b(c,"beforeRedraw",w)}})(a||(a=
{}));return a});z(e,"Series/Waterfall/WaterfallPoint.js",[e["Series/Column/ColumnSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,d,b){var k=this&&this.__extends||function(){var a=function(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,d)};return function(b,d){function e(){this.constructor=b}a(b,d);b.prototype=null===d?Object.create(d):(e.prototype=d.prototype,
new e)}}(),a=b.isNumber;return function(b){function e(){var a=null!==b&&b.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}k(e,b);e.prototype.getClassName=function(){var a=d.prototype.getClassName.call(this);this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a};e.prototype.isValid=function(){return a(this.y)||this.isSum||!!this.isIntermediateSum};return e}(e.prototype.pointClass)});z(e,"Series/Waterfall/WaterfallSeries.js",[e["Core/Axis/Axis.js"],
e["Core/Chart/Chart.js"],e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"],e["Core/Axis/WaterfallAxis.js"],e["Series/Waterfall/WaterfallPoint.js"]],function(e,d,b,k,a,r,q){var l=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=
null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),w=k.seriesTypes,y=w.column,c=w.line,m=a.arrayMax,h=a.arrayMin,n=a.correctFloat;w=a.extend;var x=a.merge,z=a.objectEach,J=a.pick;a=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.options=void 0;b.points=void 0;b.stackedYNeg=void 0;b.stackedYPos=void 0;b.stackKey=void 0;b.xData=void 0;b.yAxis=void 0;b.yData=void 0;return b}l(d,a);d.prototype.generatePoints=function(){var a;y.prototype.generatePoints.apply(this);
var b=0;for(a=this.points.length;b<a;b++){var c=this.points[b];var d=this.processedYData[b];if(c.isIntermediateSum||c.isSum)c.y=n(d)}};d.prototype.translate=function(){var a=this.options,b=this.yAxis,c,d=J(a.minPointLength,5),e=d/2,h=a.threshold,k=a.stacking,l=b.waterfall.stacks[this.stackKey];y.prototype.translate.apply(this);var n=c=h;var m=this.points;var q=0;for(a=m.length;q<a;q++){var t=m[q];var w=this.processedYData[q];var r=t.shapeArgs;var D=[0,w];var x=t.y;if(k){if(l){D=l[q];if("overlap"===
k){var F=D.stackState[D.stateIndex--];F=0<=x?F:F-x;Object.hasOwnProperty.call(D,"absolutePos")&&delete D.absolutePos;Object.hasOwnProperty.call(D,"absoluteNeg")&&delete D.absoluteNeg}else 0<=x?(F=D.threshold+D.posTotal,D.posTotal-=x):(F=D.threshold+D.negTotal,D.negTotal-=x,F-=x),!D.posTotal&&Object.hasOwnProperty.call(D,"absolutePos")&&(D.posTotal=D.absolutePos,delete D.absolutePos),!D.negTotal&&Object.hasOwnProperty.call(D,"absoluteNeg")&&(D.negTotal=D.absoluteNeg,delete D.absoluteNeg);t.isSum||
(D.connectorThreshold=D.threshold+D.stackTotal);b.reversed?(w=0<=x?F-x:F+x,x=F):(w=F,x=F-x);t.below=w<=J(h,0);r.y=b.translate(w,0,1,0,1);r.height=Math.abs(r.y-b.translate(x,0,1,0,1));if(x=b.waterfall.dummyStackItem)x.x=q,x.label=l[q].label,x.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[q],this.stackedYPos[q])}}else F=Math.max(n,n+x)+D[0],r.y=b.translate(F,0,1,0,1),t.isSum?(r.y=b.translate(D[1],0,1,0,1),r.height=Math.min(b.translate(D[0],0,1,0,1),b.len)-r.y):t.isIntermediateSum?(0<=
x?(w=D[1]+c,x=c):(w=c,x=D[1]+c),b.reversed&&(w^=x,x^=w,w^=x),r.y=b.translate(w,0,1,0,1),r.height=Math.abs(r.y-Math.min(b.translate(x,0,1,0,1),b.len)),c+=D[1]):(r.height=0<w?b.translate(n,0,1,0,1)-r.y:b.translate(n,0,1,0,1)-b.translate(n-w,0,1,0,1),n+=w,t.below=n<J(h,0)),0>r.height&&(r.y+=r.height,r.height*=-1);t.plotY=r.y=Math.round(r.y)-this.borderWidth%2/2;r.height=Math.max(Math.round(r.height),.001);t.yBottom=r.y+r.height;r.height<=d&&!t.isNull?(r.height=d,r.y-=e,t.plotY=r.y,t.minPointLengthOffset=
0>t.y?-e:e):(t.isNull&&(r.width=0),t.minPointLengthOffset=0);r=t.plotY+(t.negative?r.height:0);this.chart.inverted?t.tooltipPos[0]=b.len-r:t.tooltipPos[1]=r}};d.prototype.processData=function(b){var c=this.options,d=this.yData,e=c.data,h=d.length,k=c.threshold||0,v,l,m,q,r;for(r=l=v=m=q=0;r<h;r++){var t=d[r];var w=e&&e[r]?e[r]:{};"sum"===t||w.isSum?d[r]=n(l):"intermediateSum"===t||w.isIntermediateSum?(d[r]=n(v),v=0):(l+=t,v+=t);m=Math.min(l,m);q=Math.max(l,q)}a.prototype.processData.call(this,b);
c.stacking||(this.dataMin=m+k,this.dataMax=q)};d.prototype.toYData=function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y};d.prototype.updateParallelArrays=function(b,c){a.prototype.updateParallelArrays.call(this,b,c);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null};d.prototype.pointAttribs=function(a,b){var c=this.options.upColor;c&&!a.options.color&&(a.color=0<a.y?c:null);a=y.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a};d.prototype.getGraphPath=
function(){return[["M",0,0]]};d.prototype.getCrispPath=function(){var a=this.data,b=this.yAxis,c=a.length,d=Math.round(this.graph.strokeWidth())%2/2,e=Math.round(this.borderWidth)%2/2,h=this.xAxis.reversed,k=this.yAxis.reversed,l=this.options.stacking,n=[],m;for(m=1;m<c;m++){var q=a[m].shapeArgs;var r=a[m-1];var t=a[m-1].shapeArgs;var w=b.waterfall.stacks[this.stackKey];var x=0<r.y?-t.height:0;w&&t&&q&&(w=w[m-1],l?(w=w.connectorThreshold,x=Math.round(b.translate(w,0,1,0,1)+(k?x:0))-d):x=t.y+r.minPointLengthOffset+
e-d,n.push(["M",(t.x||0)+(h?0:t.width||0),x],["L",(q.x||0)+(h?q.width||0:0),x]));t&&n.length&&(!l&&0>r.y&&!k||0<r.y&&k)&&((r=n[n.length-2])&&"number"===typeof r[2]&&(r[2]+=t.height||0),(r=n[n.length-1])&&"number"===typeof r[2]&&(r[2]+=t.height||0))}return n};d.prototype.drawGraph=function(){c.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})};d.prototype.setStackedPoints=function(){function a(a,b,c,d){if(B)for(c;c<B;c++)F.stackState[c]+=d;else F.stackState[0]=a,B=F.stackState.length;
F.stackState.push(F.stackState[B-1]+b)}var b=this.options,c=this.yAxis.waterfall.stacks,d=b.threshold,e=d||0,h=e,k=this.stackKey,l=this.xData,n=l.length,m,q,r;this.yAxis.stacking.usePercentage=!1;var t=q=r=e;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var w=c.changed;(m=c.alreadyChanged)&&0>m.indexOf(k)&&(w=!0);c[k]||(c[k]={});m=c[k];for(var x=0;x<n;x++){var y=l[x];if(!m[y]||w)m[y]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:w&&m[y]?m[y].label:
void 0};var F=m[y];var z=this.yData[x];0<=z?F.posTotal+=z:F.negTotal+=z;var G=b.data[x];y=F.absolutePos=F.posTotal;var J=F.absoluteNeg=F.negTotal;F.stackTotal=y+J;var B=F.stackState.length;G&&G.isIntermediateSum?(a(r,q,0,r),r=q,q=d,e^=h,h^=e,e^=h):G&&G.isSum?(a(d,t,B),e=d):(a(e,z,0,t),G&&(t+=z,q+=z));F.stateIndex++;F.threshold=e;e+=F.stackTotal}c.changed=!1;c.alreadyChanged||(c.alreadyChanged=[]);c.alreadyChanged.push(k)}};d.prototype.getExtremes=function(){var a=this.options.stacking;if(a){var b=
this.yAxis;b=b.waterfall.stacks;var c=this.stackedYNeg=[];var d=this.stackedYPos=[];"overlap"===a?z(b[this.stackKey],function(a){c.push(h(a.stackState));d.push(m(a.stackState))}):z(b[this.stackKey],function(a){c.push(a.negTotal+a.threshold);d.push(a.posTotal+a.threshold)});return{dataMin:h(c),dataMax:m(d)}}return{dataMin:this.dataMin,dataMax:this.dataMax}};d.defaultOptions=x(y.defaultOptions,{dataLabels:{inside:!0},lineWidth:1,lineColor:b.neutralColor80,dashStyle:"Dot",borderColor:b.neutralColor80,
states:{hover:{lineWidthPlus:0}}});return d}(y);w(a.prototype,{getZonesGraphs:c.prototype.getZonesGraphs,pointValKey:"y",showLine:!0,pointClass:q});k.registerSeriesType("waterfall",a);r.compose(e,d);"";return a});z(e,"Extensions/Polar.js",[e["Core/Animation/AnimationUtilities.js"],e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Extensions/Pane.js"],e["Core/Pointer.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Renderer/SVG/SVGRenderer.js"],e["Core/Utilities.js"]],function(e,
d,b,k,a,r,q,l,w){var y=e.animObject;q=q.seriesTypes;var c=w.addEvent,m=w.defined,h=w.find,n=w.isNumber,x=w.pick,z=w.splat,J=w.uniqueKey;e=w.wrap;var H=r.prototype;a=a.prototype;H.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};H.getConnectors=function(a,b,c,d){var e=d?1:0;var f=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>f-1?a.length-(1+e):f-1;e=f+1>a.length-
1?e:f+1;var g=a[b];e=a[e];var h=g.plotX;g=g.plotY;var p=e.plotX;var k=e.plotY;e=a[f].plotX;f=a[f].plotY;h=(1.5*e+h)/2.5;g=(1.5*f+g)/2.5;p=(1.5*e+p)/2.5;var l=(1.5*f+k)/2.5;k=Math.sqrt(Math.pow(h-e,2)+Math.pow(g-f,2));var m=Math.sqrt(Math.pow(p-e,2)+Math.pow(l-f,2));h=Math.atan2(g-f,h-e);l=Math.PI/2+(h+Math.atan2(l-f,p-e))/2;Math.abs(h-l)>Math.PI/2&&(l-=Math.PI);h=e+Math.cos(l)*k;g=f+Math.sin(l)*k;p=e+Math.cos(Math.PI+l)*m;l=f+Math.sin(Math.PI+l)*m;e={rightContX:p,rightContY:l,leftContX:h,leftContY:g,
plotX:e,plotY:f};c&&(e.prevPointCont=this.getConnectors(a,b,!1,d));return e};H.toXY=function(a){var b=this.chart,c=this.xAxis,d=this.yAxis,e=a.plotX,g=a.plotY,h=a.series,k=b.inverted,l=a.y,m=k?e:d.len-g;k&&h&&!h.isRadialBar&&(a.plotY=g="number"===typeof l?d.translate(l)||0:0);a.rectPlotX=e;a.rectPlotY=g;d.center&&(m+=d.center[3]/2);n(g)&&(d=k?d.postTranslate(g,m):c.postTranslate(e,m),a.plotX=a.polarPlotX=d.x-b.plotLeft,a.plotY=a.polarPlotY=d.y-b.plotTop);this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%
360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};q.spline&&(e(q.spline.prototype,"getPointSpline",function(a,b,c,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),b=a.prevPointCont&&a.prevPointCont.rightContX,c=a.prevPointCont&&a.prevPointCont.rightContY,a=["C",n(b)?b:a.plotX,n(c)?c:a.plotY,n(a.leftContX)?a.leftContX:a.plotX,n(a.leftContY)?a.leftContY:a.plotY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,d);return a}),q.areasplinerange&&(q.areasplinerange.prototype.getPointSpline=
q.spline.prototype.getPointSpline));c(r,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var d=this.points,e=d.length;e--;)this.toXY(d[e]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&d[e].y<this.yAxis.min&&(d[e].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(c(this,"afterRender",
function(){if(a.polar){var c=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:c[0],y:c[1],r:c[2]/2,innerR:c[3]/2}):this.clipCircle=a.renderer.clipCircle(c[0],c[1],c[2]/2,c[3]/2);this.group.clip(this.clipCircle);this.setClip=b.noop}})))}},{order:2});e(q.line.prototype,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,
0,b[e]);var f=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));f&&b.pop();return d});var t=function(a,c){var d=this,e=this.chart,f=this.options.animation,g=this.group,h=this.markerGroup,k=this.xAxis.center,l=e.plotLeft,m=e.plotTop,n,q,r,t;if(e.polar)if(d.isRadialBar)c||(d.startAngleRad=x(d.translatedThreshold,d.xAxis.startAngleRad),b.seriesTypes.pie.prototype.animate.call(d,c));else{if(e.renderer.isSVG)if(f=y(f),d.is("column")){if(!c){var w=
k[3]/2;d.points.forEach(function(a){n=a.graphic;r=(q=a.shapeArgs)&&q.r;t=q&&q.innerR;n&&q&&(n.attr({r:w,innerR:w}),n.animate({r:r,innerR:t},d.options.animation))})}}else c?(a={translateX:k[0]+l,translateY:k[1]+m,scaleX:.001,scaleY:.001},g.attr(a),h&&h.attr(a)):(a={translateX:l,translateY:m,scaleX:1,scaleY:1},g.animate(a,f),h&&h.animate(a,f))}else a.call(this,c)};e(H,"animate",t);if(q.column){var A=q.arearange.prototype;q=q.column.prototype;q.polarArc=function(a,b,c,d){var e=this.xAxis.center,f=this.yAxis.len,
g=e[3]/2;b=f-b+g;a=f-x(a,f)+g;this.yAxis.reversed&&(0>b&&(b=g),0>a&&(a=g));return{x:e[0],y:e[1],r:b,innerR:a,start:c,end:d}};e(q,"animate",t);e(q,"translate",function(a){var b=this.options,c=b.stacking,d=this.chart,e=this.xAxis,g=this.yAxis,h=g.reversed,k=g.center,l=e.startAngleRad,q=e.endAngleRad-l;this.preventPostTranslate=!0;a.call(this);if(e.isRadial){a=this.points;e=a.length;var r=g.translate(g.min);var t=g.translate(g.max);b=b.threshold||0;if(d.inverted&&n(b)){var x=g.translate(b);m(x)&&(0>
x?x=0:x>q&&(x=q),this.translatedThreshold=x+l)}for(;e--;){b=a[e];var y=b.barX;var z=b.x;var A=b.y;b.shapeType="arc";if(d.inverted){b.plotY=g.translate(A);if(c&&g.stacking){if(A=g.stacking.stacks[(0>A?"-":"")+this.stackKey],this.visible&&A&&A[z]&&!b.isNull){var B=A[z].points[this.getStackIndicator(void 0,z,this.index).key];var G=g.translate(B[0]);B=g.translate(B[1]);m(G)&&(G=w.clamp(G,0,q))}}else G=x,B=b.plotY;G>B&&(B=[G,G=B][0]);if(!h)if(G<r)G=r;else if(B>t)B=t;else{if(B<r||G>t)G=B=0}else if(B>r)B=
r;else if(G<t)G=t;else if(G>r||B<t)G=B=q;g.min>g.max&&(G=B=h?q:0);G+=l;B+=l;k&&(b.barX=y+=k[3]/2);z=Math.max(y,0);A=Math.max(y+b.pointWidth,0);b.shapeArgs={x:k&&k[0],y:k&&k[1],r:A,innerR:z,start:G,end:B};b.opacity=G===B?0:void 0;b.plotY=(m(this.translatedThreshold)&&(G<this.translatedThreshold?G:B))-l}else G=y+l,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,G,G+b.pointWidth);this.toXY(b);d.inverted?(y=g.postTranslate(b.rectPlotY,y+b.pointWidth/2),b.tooltipPos=[y.x-d.plotLeft,y.y-d.plotTop]):b.tooltipPos=
[b.plotX,b.plotY];k&&(b.ttBelow=b.plotY>k[1])}}});q.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b};A&&(A.findAlignments=q.findAlignments);e(q,"alignDataLabel",function(a,b,c,d,e,h){var f=this.chart,g=x(d.inside,!!this.options.stacking);f.polar?(a=b.rectPlotX/Math.PI*180,f.inverted?(this.forceDL=f.isInsidePlot(b.plotX,Math.round(b.plotY)),g&&
b.shapeArgs?(e=b.shapeArgs,e=this.yAxis.postTranslate(((e.start||0)+(e.end||0))/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),e={x:e.x-f.plotLeft,y:e.y-f.plotTop}):b.tooltipPos&&(e={x:b.tooltipPos[0],y:b.tooltipPos[1]}),d.align=x(d.align,"center"),d.verticalAlign=x(d.verticalAlign,"middle")):this.findAlignments&&(d=this.findAlignments(a,d)),H.alignDataLabel.call(this,b,c,d,e,h),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,d,e,h)})}e(a,"getCoordinates",
function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});l.prototype.clipCircle=function(a,b,c,d){var e=J(),f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=d?this.arc(a,b,c,d,0,2*Math.PI).add(f):
this.circle(a,b,c).add(f);a.id=e;a.clipPath=f;return a};c(d,"getAxes",function(){this.pane||(this.pane=[]);this.options.pane=z(this.options.pane);this.options.pane.forEach(function(a){new k(a,this)},this)});c(d,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});c(r,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});e(d.prototype,"get",function(a,b){return h(this.pane||[],function(a){return a.options.id===
b})||a.call(this,b)})});z(e,"masters/highcharts-more.src.js",[e["Core/Globals.js"],e["Core/Axis/RadialAxis.js"],e["Series/Bubble/BubbleSeries.js"]],function(e,d,b){d.compose(e.Axis,e.Tick);b.compose(e.Chart,e.Legend,e.Series)})});
//# sourceMappingURL=highcharts-more.js.map